### ISSUE TITLE
sp_AllNightLog - Databases left in a questionable state if database is not able to be backed up

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1005]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a database is not able to be backed up for any reason (stuck in RESTORING, invalid folder path, etc.) the first time sp_AllNightLog attempts to back it up, no full backup is created.

However, the queue table marks it as having a valid full backup timestamp, so all future backups are attempted as log backups, which fail.

**What is the expected behavior?**
On a failure of the full backup, further attempts to take a backup should continue to attempt full backups.

**Comment by BrentOzar** [comment]
Thinking through ways we'll want to test this:

- Database temporarily unable to be backed up (like in recovery at startup, or a mirror, or a database is restoring because a new database is being restored to create another one)
- Database permanently unable to be backed up (like set offline, or restoring from another server)
- Full backup fails (backup target doesn't have enough space, Hekaton corruption, etc)

**Comment by BrentOzar** [comment]
Hmm, I'm trying to test this and I don't see the issue. There's no logic in sp_AllNightLog that decides whether to take a full backup or not. Whenever we go to take a log backup, we're calling DatabaseBackup with @ChangeBackupType = 'Y' - which will automatically escalate to a full backup if necessary. The queue table marks it as having a full backup, but that doesn't affect the code's attempts to keep trying a full backup every time.

I bet you've got a specific scenario where it does break though - can you elaborate on that or give me a repro?

**Comment by BrentOzar** [comment]
While researching the issue, I think it DOES happen with the first full restore attempt (if that fails, we don't try it again properly) so I put logic in there to handle that. Haven't done a PR yet though because I think we might have more work to do on backups.

**Comment by BrentOzar** [comment]
From the discussion in Slack - I bet it's because the databases you're adding are based on full restores, restoring as a new database name. Ola's DatabaseBackup @ChangeBackupType = 'Y' just looks at that metadata and says there's no need to do a full backup.

So I'd created this new value for the param, @ChangeBackupType = 'MSDB' here:
https://github.com/olahallengren/sql-server-maintenance-solution/pull/13

But I'm not passing that into Ola's stuff. So I added a new parameter for sp_AllNightLog @ChangeBackupType, defaults to Y. I just now realized I shouldn't have coded it that way - I should remove the parameter, and make this database-driven. Will knock that out first thing tomorrow, will be an easy tweak.

**Comment by BrentOzar** [comment]
Note that this requires the updated version of Ola Hallengren's DatabaseBackup that accepts @ChangeBackupType = 'MSDB' - it's not in his public version yet. Here's our updated version of his code for now:

https://github.com/BrentOzarULTD/sql-server-maintenance-solution

Here's the pull request we've sent to Ola to get this into his main branch:

https://github.com/olahallengren/sql-server-maintenance-solution/pull/13
