### ISSUE TITLE
sp_AllNightLog_Setup - unable to disable restoring jobs

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1016]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running sp_AllNightLog_Setup to disable the restore jobs, the following command is executed:
`EXEC sp_AllNightLog_Setup @UpdateSetup = 1, @EnableRestoreJobs = 0, @EnableBackupJobs = 1;`

This generates the following error:
`Database 'msdbCentral' cannot be opened. It is in the middle of a restore.`

Root cause appears to be the fact that, while restore jobs are running, MSDBCentral is in RESTORING mode by design, causing the following line to fail (line 1045 at time of submitting this issue):
`IF OBJECT_ID('msdbCentral.dbo.backup_configuration') IS NOT NULL`

**What is the expected behavior?**
The procedure should complete as expected.

**Comment by BrentOzar** [comment]
Did some quick digging on this - the @UpdateSetup = 1 branch of code updates the database records for configs, which requires checking for existence of the msdbCentral database and records inside of it. We're going to need a couple of different try/catch areas in here - one to update the tables, and one to enable/disable the jobs.

It's doable, but it's just not quite doable today (I have meetings starting in about an hour) so I need to punt this.

**Comment by BrentOzar** [comment]
I was overthinking this. The easier way is just to say, if @EnableRestoreJobs = 1 but msdbCentral is anything other than online, do something.

We could just tell the user to run restore with recovery on msdbCentral, but I figured we might as well just go ahead and do it in the script. (I wouldn't wanna run restore with recovery on any other user databases, but this one seems pretty safe.)

Then, after running restore with recovery on msdbCentral, I'll check to see if it's online. If not, throw an error, but otherwise we can keep moving forward with enabling jobs.
