### ISSUE TITLE
sp_BlitzCache - warn on high variation between estimated rows vs average returned rows

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1030]
**Do you want to request a *feature* or report a *bug*?**
Feature. And I know it's gonna be hard, but this would be so worth it.

**What is the current behavior?**

- sp_BlitzCache shows the average rows returned (and total/min/max).
- This is where things get way harder: the plan XML also shows the estimated number of rows (I know, a plan could have lots of statements in the batch)
- It would be amazeballs if we could warn on high variation between estimates & average rows returned

**Comment by BlitzErik** [comment]
There is a little bit of backstory on a similar idea. Was toying around with doing this at the operator level, but it was horribly slow, and it was nearly impossible to correctly connect nodes outside of a serial plan. Not saying this will have that problem, because I think what you want is a query level check for estimated rows, and then to bump that up against DMV values returned. 

Using [this plan](https://www.brentozar.com/pastetheplan/?id=HJCFsH9Hb) as an example. We can grab StatementEstRows from the StmtSimple (basically the top line of XML) node. For this plan, it's 14.4. sp_BlitzCache has average rows returned as 515. That gets figured out like so:

![image](https://user-images.githubusercontent.com/11590415/28273612-d7b243e8-6adc-11e7-83b3-806a0f4fe757.png)

This won't work for 2008, and some versions of 2008R2, but I'm not heartbroken about that. We can do this at the statement level easily (that's how most checks are done), and skip it for Stored Procs. Stored Procs have a lot of their metrics rolled up from information about statements within them anyway.

![image](https://user-images.githubusercontent.com/11590415/28273901-7a4e4890-6add-11e7-9bf1-0c4f668be278.png)

**Comment by BlitzErik** [comment]
I wrote all that, and like a big dummy forgot to ask the one question I had: at what variation do you want to flag this?

**Comment by BrentOzar** [comment]
AWWWW YEAH, awesome! How about 10000x for starters? It may be a problem at lower variations, too, but at 10000x, I'm definitely concerned.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by BlitzErik** [comment]
I have an initial implementation of this, but I'm not happy with how we're figuring out wide variance, exactly. I'm going to push it out and keep an eye on it.

`is_bad_estimate = CASE WHEN estimated_rows * 10000 < AverageReturnedRows OR estimated_rows > AverageReturnedRows * 10000 THEN 1 END`

Gives us this. Not that I think any of these are particularly "bad", but we'll see what pops up in the wild.

![image](https://user-images.githubusercontent.com/11590415/28325112-0baf6c9c-6bab-11e7-8807-89d6791063bb.png)
