### ISSUE TITLE
sp_AllNightLog: add native encryption support for backups

### ISSUE THREAD

**Issue by Cadius1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1037]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Currently, the DatabaseBackup parameters are hard coded in _sp_AllNightLog.sql_:
```
EXEC master.dbo.DatabaseBackup @Databases = @database, --Database we're working on
   @BackupType = 'LOG', --Going for the LOGs
   @Directory = @backup_path, --The path we need to back up to
   @Verify = 'N', --We don't want to verify these, it eats into job time
   @ChangeBackupType = 'Y', --If we need to switch to a FULL because one hasn't been taken
   @CheckSum = 'Y', --These are a good idea
   @Compress = 'Y', --This is usually a good idea
   @LogToTable = 'Y'; --We should do this for posterity
```

**What is the desired behavior?**
It would be useful if we could set these parameters (and perhaps other optional Ola parameters?) via _sp_AllNightLog_Setup.sql_, storing them as values in the` dbo.backup_configuration` table. This would mean they were no longer hard-coded in the stored procedure.

**Comment by jstanford-kcura** [comment]
Just to add to this, even if it's hard to add full customization of all parameters to this, adding the ability to specify a certificate with which to encrypt the backups would be fantastic.

**Comment by BlitzErik** [comment]
@jstanford-kcura I believe you also need to specify an algorithm if you specify a certificate, no?

**Comment by jstanford-kcura** [comment]
@BlitzErik Yep, I should have said "the options necessary to encrypt backups".

**Comment by BlitzErik** [comment]
Note to self: when implementing this, pull Ola's parameter validation checks so we don't pass in anything wonky and end up with a bunch of errors.

**Comment by BrentOzar** [comment]
Requesting comments on how we implement this - there's a lot of gotchas.

**Ola's DatabaseBackup has 36 parameters** - and we should expect the parameter names, possible input values, and validations to change without requiring updates to sp_AllNightLog. We shouldn't copy the exact same validations in. Plus, they affect both the backup process and the restore process (meaning this also requires changes to sp_DatabaseRestore, but we'll do that as a separate Github issue since it'll require different code & testing.)

The msdbCentral.dbo.backup_configuration and msdb.dbo.restore_configuration tables allow us to set global config options already:

![config_options](https://user-images.githubusercontent.com/245462/29995710-8a5d20ec-8fb5-11e7-8f25-7cf2fcbb7dc6.png)

So how about this:

 - Any configuration_name rows that start with DatabaseBackup@ (like DatabaseBackup@Encrypt means @Encrypt is a parameter to be passed to the DatabaseBackup proc, with the value of configuration_setting as the param value)
 - Same with sp_DatabaseRestore@ rows - those get passed to sp_DatabaseRestore (which has its own set of params, and I've added #1096 for that
 - We won't do any validation on these - if you pass in a bogus parameter or value, it's just going to fail

**Comment by BrentOzar** [comment]
Tagging @Cadius1, @jstanford-kcura, and @BlitzErik for thoughts.

**Comment by BlitzErik** [comment]
Perhaps _us_ adding all 36 (since params may come and go) is a mistake. 

We could allow users to send in a line called, say `@AdditionalParams`, and let them specify anything after `@Directory` (referencing the code block in the first issue. 

We'd build dynamic SQL that would start with a base like

`EXEC master.dbo.DatabaseBackup @Databases = @database,
   @BackupType = 'LOG'
   @Directory = @backup_path`

Then tack on a comma and `@AdditionalParams` if it's not `NULL`. 

An example would be `EXEC dbo.AllNightLog [pretend I have all the required params right here], @AdditionalParams = N'@Verify = 'Y', @CleanupTime = 1, @CheckSum = 'Y', @LogToTable = 'Y''

This makes us not responsible for ongoing support of Ola's variables, and alleviates a whole metric elephant turd of code we'd have to write.

**Comment by BlitzErik** [comment]
Another thought on the above: it gives users a much easier time of just copying and pasting _current_ Ola configs right into this job from current job steps.

**Comment by BrentOzar** [comment]
Copy/paste params - ooo, that's a great point. Love that.

I was stretching to come up with reasons why we shouldn't let them just pass in @AdditionalParameters as a big list, and the only two reasons I came up with was possible SQL injection, and errors if they specify params in that list and we later end up adding them directly into sp_AllNightLog. Those are both total stretches though.

**Comment by scorellis** [comment]
as long as we never call this from a web page, SQL injection won't be an issue.  A SQL job is a vehicle for SQL injection, right?

**Comment by BrentOzar** [comment]
This is gonna sound crazy, but yeah, if someone has permissions to insert into the master.backup_configuration or msdb.restore_configuration table (but not SA), then they could commandeer SA through the execution of stuff via these jobs. They could update rows in these tables, and then whatever commands they put in 'em would be executed. (sigh) No rest for the wicked.

**Comment by BlitzErik** [comment]
Is that much more of a possibility for this than with the lines we already have in there? I mean, the RPO/RTO number, whatever, but the path could be used maliciously, change to a different location/IP address, etc.

**Comment by BrentOzar** [comment]
@BlitzErik yeah, like I said, I was reaching - but with this, you could execute alter login commands, that kind of thing. I still like this as the best solution I can think of though, given the pros and cons.

**Comment by jstanford-kcura** [comment]
The additionalparameters solution seems fine to me.

That said, if we're worried about SQL injection, would an additional table work?  Two columns, ParameterName and ParameterValue, with the first only being used if whitelisted, and the second only being used as a parameter, not as part of the string building?

Thinking through that solution, that seems like a fair bit of work, for what sounds like an edge case (How many non-administrators can write to msdb?  Don't answer that, it'll probably depress me).

**Comment by BrentOzar** [comment]
@jstanford-kcura yeah, I agree. I'll stick the SQL injection note as a known issue in the documentation, but seems like it's worth the risk. If you let non-admins write to msdb, you're probably boned to begin with. Alright, coding it today.

**Comment by BrentOzar** [comment]
(sigh) Well, good news and bad news.

The good news is that we now have encryption support: there are now rows in msdbCentral.dbo.backup_configuration for encryption, encryptionalgorithm, and servercertificate. All three have to be configured to get encryption.

The bad news is that we only have support for those three parameters. I tried doing dynamic parameters this morning, but it turns out that calling a stored proc dynamically using EXEC means that I can't surface all errors easily. For example, someone could put in bogus parameter names that don't exist, and their backups would fail, and it'd be really hard for us to surface why. I'll leave that for somebody smarter than me - for now, we'll just include support for these three params.

The great news is that we don't have to touch restores at all - as long as the certificate exists in the master database, SQL Server automatically uses it! Yay! No extra coding required at all on the restore side.

**Comment by BrentOzar** [comment]
Helpful scripts for anyone who wants to play around with the feature:

```
/* Configure encryption poorly: */
UPDATE msdbCentral.dbo.backup_configuration SET configuration_setting = 'Y' WHERE database_name = 'all' AND configuration_name = 'encrypt';
GO
/* Should get a setup error here: */
EXEC sp_AllNightLog @Backup = 1, @Debug = 1
GO

/* Configure the rest of encryption: */
USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'KillVMa1m';
GO
CREATE CERTIFICATE Backup_Encryption_Certificate
   WITH SUBJECT = 'To Whom It May Concern';
GO
UPDATE msdbCentral.dbo.backup_configuration SET configuration_setting = 'AES_256' WHERE database_name = 'all' AND configuration_name = 'encryptionalgorithm';
GO
UPDATE msdbCentral.dbo.backup_configuration SET configuration_setting = 'Backup_Encryption_Certificate' WHERE database_name = 'all' AND configuration_name = 'servercertificate';
GO
SELECT * FROM msdbCentral.dbo.backup_configuration
GO
EXEC sp_AllNightLog @Backup = 1, @Debug = 1
GO
```

**Comment by BrentOzar** [comment]
I've also added documentation here: https://www.brentozar.com/sp_allnightlog/
