### ISSUE TITLE
sp_DatabaseRestore: @Debug = 1 needs to only print commands, not execute them

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1185]
Sometimes I just want to see the script, without actually running it,

**Comment by BrentOzar** [comment]
OK, cool, sounds legit. In order to do it, I'd suggest using the Debug parameter - right now, it says "Debug 1 will print the commands," but that doesn't appear to be entirely true at first glance. If you just wanna patch up that logic so that it works as described, that would accomplish the goal.

Here's the contribution guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Do you want to tackle this? (If not, we'll close it.)

**Comment by ShawnCrocker** [comment]
Yes, I'll do this

**Comment by scorellis** [comment]
I think this should be a separate option, such as debug =2.  I like to debug when things are running.

**Comment by BrentOzar** [comment]
@scorellis can you elaborate on that? Right now @debug = 1 is supposed to print the commands without executing them. What are you suggesting that @debug = 1 do instead, and what should @debug = 2 do?

**Comment by scorellis** [comment]
Well, we've already talked about a log to table in issue #1191, which I will soon resurrect.  Perhaps I should just create a "logCommandToTable" bit that is completely separate from debug, and let you guys worry about what debug will do.  It doesn't seem like a feature I would ever use, since you know me, I like to run with scissors.  

Regarding what @debug does, at least in sp_allnightlog where I've looked, it doesn't appear to have any logic that escapes EXEC commands.  Maybe I'm blind and am not seeing it, but I am running it right now on a test system, in @debug = 1, and I am getting log backups.

**Comment by BrentOzar** [comment]
Yep, totally! That's what this ticket is about.

**Comment by loosleef** [comment]
> `SELECT unsolicited_comment FROM #randomDude`

1. `dbo.CommandExecute` already has the ability to log commands but not execute (`@Execute` parameter).  So could just drive that from the `@debug` param.
```sql
DECLARE
  @exec NVARCHAR(1) = N'Y',
  @extendedInfo = NULL
SELECT
  @exec = N'N',
  @extendedInfo = (SELECT @debug AS '@debug' FOR XML PATH('spDatabaseRestore') --to identify
WHERE @debug = 1
...
EXEC dbo.CommandExecute ... @Execute = @exec, @ExtendedInfo = @extendedInfo
```

2. Additionally, in debug mode, `dbo.CommandExecute` `@Mode` can be set to 2 to throw errors instead of returning as output params (which are not handled in sp_DatabaseRestore anyway).  This may require putting in outer TRY/CATCH ...which probably should already be there for the `BackupFiles` cursor.

**Comment by BlitzErik** [comment]
@loosleef take a look this pull request - I made some of those changes #1249

**Comment by BlitzErik** [comment]
Going to close this out for now. When you're ready to work on it, feel free to reopen the issue.
