### ISSUE TITLE
sp_BlitzCache - Reports Many Indexes Modified

### ISSUE THREAD

**Issue by JimmyParker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1256]
[usp_CheckForVoterFraud.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1511923/usp_CheckForVoterFraud.txt)
**Do you want to request a *feature* or report a *bug*?**
Bug
5.9.5 released on Nov 15 2017 12:00AM

**What is the current behavior?**
sp_BlitzCache reports many indexes modified when no physical tables are modified in a procedure.  The procedure does contain a table variable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Using the StackOverflow database in a training class executing procedure usp_CheckForVoterFraud.  See attached script.  Query plan is here https://www.brentozar.com/pastetheplan/?id=ByJpiPoxf

**What is the expected behavior?**
Do not report Many Indexes Modified when none are made.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2017/Windows Server 2016 Datacenter.  I don't know if this worked in prior versions.

**Comment by BlitzErik** [comment]
Great catch!

Long story short, the section of the code that handles this was joining on SqlHandle (which is common to all statements in the proc), and counting the INSERT and UPDATE of the table exponentially for every statement in the batch. This lead to the warning being triggered. Joining instead on QueryHash generated the correct results (the hash is per-statement in the batch). 

So, while it showing up here IS a bug, it should technically be considered because you modify a table variable twice. Heaps being modified are checked as part of the process, and a table variable without an index is still a heap.

![image](https://user-images.githubusercontent.com/11590415/33351339-46e2a05c-d471-11e7-9b95-90399bb24fa1.png)

As for the wording: when I was writing this section, I considered saying "objects modified" or "tables modified" to cover Heaps, but that sounded ambiguous to me, like you're altering tables or something. If you have a better (and still pithy) suggestion, I'm all ears.

Thanks!

**Comment by SimonHellings** [comment]
Funny - In class when we saw this we joked that you'd be on straight away and it would be 'fixed' by morning.  2 hours...  Impressive.

As for suggestions on wording, personally I agree 'objects' is quite ambiguous, 'tables' however could fir the bill.

I spent quite some time looking at it thinking "where are these indexes?  Are they hidden as its a table variable?"

**Comment by JimmyParker** [comment]
Thanks Erik!
