### ISSUE TITLE
sp_BlitzCache: Add Param to Exclude Database

### ISSUE THREAD

**Issue by KevinKelso** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1258]
I'd like to have the ability to exclude a database from the results. We have one database that a lot of junk gets put in. It's used for a lot of random analysis by our analysts. I'd like to exclude it since most object in this database are considered temporary.

**Comment by BlitzErik** [comment]
Your best bet is to use the `@DatabaseName` to filter to a specific database you _do_ want to look at.

Otherwise, this is a great first pull request for you to work on! The code changes are minimal. 

Just make sure to read the [Contributing](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) guide first.

I'd suggest a parmeter called `@DatabaseNameExclude`, then it'd be one-place code addition. 

Plop your new variable name in, and change the ` = DB_ID(` to ` <> DB_ID(`

```
IF @DatabaseName IS NOT NULL OR @DatabaseName <> ''
	BEGIN 
    RAISERROR(N'Filtering database name chosen', 0, 1) WITH NOWAIT;
	SET @body += N'               AND CAST(xpa.value AS BIGINT) = DB_ID('
                 + QUOTENAME(@DatabaseName, N'''')
                 + N') ' + @nl;
	END; 
```

**Comment by SQLGumbo** [comment]
Tossing this out here; may be overkill depending on scope.

If excluding a database, how about excluding a pattern (in the db name) too?  Similar code for both.   Pass the wildcarda into the parm.

**Comment by BlitzErik** [comment]
I'm fine with people contributing code that helps them, whether it's exclude, include, or both. The way `sp_foreachdb` works is a good example. 

Just because I haven't done it doesn't mean it's not worthwhile. I mainly focus on improvements and additions to stuff we look for in the plan xml and metadata. 

Just make sure you read and understand how the current code works first, and what your changes would entail.

Thanks!

**Comment by BlitzErik** [comment]
Haven't heard back on this in a while, so closing it out. If you decide you want to try to implement it, feel free to reopen.

Thanks!
