### ISSUE TITLE
CPU Weight is not a percentage anymore

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1352]
Brent had me add this issue while on a call with a client.

**Do you want to request a *feature* or report a *bug*?**
BUG: Latest version is showing a very low decimal value for CPU Weight column when it should be a much higher percentage value.

**What is the current behavior?**

It returns a decimal value and not a percentage.

**What is the expected behavior?**

To return a percentage value.

**Comment by BlitzErik** [comment]
Can I get a screen cap or something? I've never changed anything remotely related to this part of the code.

**Comment by TaraKizer** [comment]
I'm watching Brent do his thing and notice the CPU Weight looks okay in the xpm sort. It was in the cpu sort that he saw the issue. I'll try to grab a screenshot when he goes back.

He did mention that he has seen this with a few clients and just hadn't entered an issue yet, so this has likely been like this for a bit and nothing to do with the latest version.

**Comment by TaraKizer** [comment]
<img width="812" alt="2017-12-21 05_40_55-cisco webex meeting center" src="https://user-images.githubusercontent.com/16884153/34258274-0fb867c6-e612-11e7-8c75-4e11251e651e.png">

**Comment by TaraKizer** [comment]
![image](https://user-images.githubusercontent.com/16884153/34258316-38b8cfda-e612-11e7-835b-9975c9a6b433.png)

**Comment by BlitzErik** [comment]
What's the number of executions on those?

**Comment by TaraKizer** [comment]
These were in the thousands/minute. These were all functions, but I doubt that's what was observed on other servers where he's seen this issue. Maybe though.

**Comment by BlitzErik** [comment]
Okay, just to scope this a little:

Here's the definition (it's the same across all the weights)

![image](https://user-images.githubusercontent.com/11590415/34259243-862a1d74-e62f-11e7-8a29-1cec23334f01.png)

Here are the columns:

![image](https://user-images.githubusercontent.com/11590415/34259333-e3ea0884-e62f-11e7-9451-d711abf63c32.png)

Here's the initial calculation:

![image](https://user-images.githubusercontent.com/11590415/34259391-160df5b4-e630-11e7-8002-d5c8eabc3dfb.png)

The calculation of percent cpu is more complicated:

This temp table is populated:

![image](https://user-images.githubusercontent.com/11590415/34259526-946e3d92-e630-11e7-9516-5369a93c3b7c.png)

Then two aggregations run to assign values:

![image](https://user-images.githubusercontent.com/11590415/34259550-b25af53e-e630-11e7-9f34-5663d586ece7.png)

One for stored procs (plan handle is not null), and then the exact same thing for statements (plan handle is null).

Gotta run for now.

**Comment by BlitzErik** [comment]
Somebody? Anybody? @BrentOzar ?

**Comment by 619619** [comment]
I've tried to look at this, let me recap the whole calculation as some additional information may help us crack this:

Let's start by how @total_cpu is calculated:

![image](https://user-images.githubusercontent.com/1709105/35184817-b71182fa-fdfa-11e7-8ff1-0e0d232df113.png)

TotalCPU in #P is the 1st occourrence of "TotalCPU" for each SqlHandle ordered by whatever field we decided to order the result.
This correlates the SortOrder with the CPU Weight results, because for the same SqlHandle depending on how the results are ordered, the TotalCPU value that we fetch is different:

![image](https://user-images.githubusercontent.com/1709105/35184965-7248ee9a-fdfc-11e7-86d5-54081ee329d4.png)

This explains why @TaraKizer reported that the issue _looks_ ok in the xpm sort while it doesn't in the CPU sort, that's because we're actually fetching the highest CPU values per SqlHandle and since in the last step we're going to divide by this value, we get smaller numbers.
This is especially true for statements that are part of stored procedures, since depending on how we order the results the Weight calculation may get different values for TotalCPU as the parent Procedure and each Statement share the same SqlHandle
Then, the @total_cpu variable is calculated as the sum of the TotalCPU selected for each handle in the step before.

![image](https://user-images.githubusercontent.com/1709105/35184825-ca370670-fdfa-11e7-860a-17b458af49b8.png)

And finally it's used in the actual update of the results table as showed by @BlitzErik  above:

![image](https://user-images.githubusercontent.com/1709105/35185028-bb05aa28-fdfd-11e7-8ae8-47ac505d898f.png)


So, what do we want the CPUWeight to be _exactly_ ?
Are we expecting it to be a percentage repartition of the CPU Cost between the @Top rows selected? (Which now it isn't in most cases, and to do so we could easily calculate this in a different way right before we present the results)
Or something else?

**Comment by BlitzErik** [comment]
Right -- all of the weights (not just CPU) are defined loosely as:

![image](https://user-images.githubusercontent.com/11590415/35190129-526ef8c2-fe28-11e7-8cd3-0b70c3a299ee.png)

It seems a lot like query bucks in that it may not reflect reality, but it's a reliable guess.

**Comment by mikhailshilkov** [comment]
I get consistently wrong weight while running on one of our test servers (actually it's Azure SQL Database). For the screenshot below, I cleaned the plan cache and ran a load test for 10 minutes. The things that seem off are in red rectangles:

1. Executions / minute are mostly correct except e.g. row 5, where 10 minute ratio suddenly breaks. Execution weight might be off too: it should be more than e.g. row 7. But at least it's consistent with executions / minute.

2. CPU, Duration, and Read weights for marked rows are way too low, if I look purely at Total numbers relative to other rows.

Any obvious reason for that? Am I misreading something?

![image](https://user-images.githubusercontent.com/1454008/35569672-0aa808a6-05cd-11e8-892d-c060f827eb39.png)

**Comment by BrentOzar** [comment]
@mikhailshilkov - we actually don't support Azure SQL DB (check the readme), but to check executions per minute, you'll want to look at the Creation and Last Execution dates - scroll to the right. Something may have cleared one of the lines from the cache.

**Comment by mikhailshilkov** [comment]
@BrentOzar I take the dice roll for now, it's the best I have so far...
Checked that, the Created At and Last Execution are perfectly same for all rows

**Comment by BrentOzar** [comment]
OK, cool. If you want to work on Azure support for it, go ahead and start a separate issue for that but only as long as you're working on it - we literally don't use Azure SQL DB at all. Nothing against it, just have to pick our battles.

**Comment by mikhailshilkov** [comment]
OK, another example of odd CPU Weights, now from a SQL Server 2014 database:

![image](https://user-images.githubusercontent.com/1454008/36412858-3cb3003a-161c-11e8-9f9c-76ea017b49a8.png)

**Comment by BrentOzar** [comment]
Closing this for now - if other folks want to tackle the code, that's cool, but I feel guilty leaving it open when I reported it and I'm not actively working on it.

**Comment by BlitzErik** [comment]
I figured this out by accident. 

We can resolve this by deleting out of the global temp table immediately after inserting to `#p` like this:

```
WITH d AS (
SELECT  SPID,
        ROW_NUMBER() OVER (PARTITION BY SqlHandle ORDER BY #sortable# DESC) AS rn
FROM    ##bou_BlitzCacheProcs
WHERE SPID = @@SPID
)
DELETE d
WHERE d.rn > 1
AND SPID = @@SPID
OPTION (RECOMPILE);
```
Doing this has the added bonus of leaving us with far fewer plans to analyze the XML for, that we don't end up using anyway. The proc runs much faster overall.

The downside is that we no longer show individual statements from inside stored procedures separately. Again, this makes things faster because we're not double working one proc, but I know there was some value in seeing the most resource intensive statement in a proc.

We could get around that by using QueryHash in the partitioning, but that undoes some of the efficiency gains, and throws off the weights a little bit.

**Comment by BrentOzar** [comment]
I'm so torn. I really, really like showing the individual statements. Maybe put that in ExpertMode only?

**Comment by BlitzErik** [comment]
If you wanna test: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/1734
