### ISSUE TITLE
BlitzFirst - PowerBi - Rewrite the @OutputTableNamePerfmonStats_Deltas view to be less of a pain

### ISSUE THREAD

**Issue by EmanueleMeazzo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1388]
**Do you want to request a *feature* or report a *bug*?**
It's more of a performance issue than a bug, the feature works correctly but performance are unbearable.

**What is the current behavior?**

For a decent datasize, due to the nature of the view, it takes on my (decent) machine 20/30 minutes to read all the rows from the "@OutputTableNamePerfmonStats_Deltas" view (i.e. 30 minutes of wait time after pressing "refresh" on the PowerBi report just to load this data)

**What is the expected behavior?**

Load the data in seconds as opposed to half an hour.

**Proposed Solution**

Change the existing View to something like this:

```
WITH CheckDates as
(
        SELECT 
                [CheckDate], 
                LAG([CheckDate],1) OVER (ORDER BY [CheckDate]) as PreviousCheckDate
        FROM [dbo].[BlitzFirst_PerfmonStats]
        GROUP BY [CheckDate]
)
SELECT
       pMon.[ServerName]
      ,pMon.[CheckDate]
      ,pMon.[object_name]
      ,pMon.[counter_name]
      ,pMon.[instance_name]
      ,DATEDIFF(SECOND,pMonPrior.[CheckDate],pMon.[CheckDate]) AS ElapsedSeconds
      ,pMon.[cntr_value]
      ,pMon.[cntr_type]
      ,(pMon.[cntr_value] - pMonPrior.[cntr_value]) AS cntr_delta
  FROM [dbo].[BlitzFirst_PerfmonStats] pMon
  JOIN CheckDates Dates
  ON Dates.CheckDate = pMon.CheckDate
  JOIN [dbo].[BlitzFirst_PerfmonStats] pMonPrior
  ON  Dates.PreviousCheckDate = pMonPrior.CheckDate
      AND pMon.[ServerName]    = pMonPrior.[ServerName]   
      AND pMon.[object_name]   = pMonPrior.[object_name]  
      AND pMon.[counter_name]  = pMonPrior.[counter_name] 
      AND pMon.[instance_name] = pMonPrior.[instance_name]
```

For 350K perfmon rows, I've verified the output of both queries and they are the same, this version however completes in 3 seconds as opposed as 30 minutes

This code will substitute the view creation currently at line 2830-ish in the BlitzFirst stored procedure.

**Comment by BlitzErik** [comment]
Lag isn't available in pre-2012 versions. Unfortunately we have to support those until they leave mainstream support. Do you have a workaround for earlier versions?

**Comment by 619619** [comment]
Good ol' ROW_NUMBER instead of LAG?

```
WITH RowDates as
(
        SELECT 
                ROW_NUMBER() OVER (ORDER BY [CheckDate]) ID,
                [CheckDate]
        FROM [dbo].[BlitzFirst_PerfmonStats]
        GROUP BY [CheckDate]
),
CheckDates as
(
        SELECT ThisDate.CheckDate,
               LastDate.CheckDate as PreviousCheckDate
        FROM RowDates ThisDate
        JOIN RowDates LastDate
        ON ThisDate.ID = LastDate.ID + 1
)
SELECT
       pMon.[ServerName]
      ,pMon.[CheckDate]
      ,pMon.[object_name]
      ,pMon.[counter_name]
      ,pMon.[instance_name]
      ,DATEDIFF(SECOND,pMonPrior.[CheckDate],pMon.[CheckDate]) AS ElapsedSeconds
      ,pMon.[cntr_value]
      ,pMon.[cntr_type]
      ,(pMon.[cntr_value] - pMonPrior.[cntr_value]) AS cntr_delta
  FROM [dbo].[BlitzFirst_PerfmonStats] pMon
  JOIN CheckDates Dates
  ON Dates.CheckDate = pMon.CheckDate
  JOIN [dbo].[BlitzFirst_PerfmonStats] pMonPrior
  ON  Dates.PreviousCheckDate = pMonPrior.CheckDate
      AND pMon.[ServerName]    = pMonPrior.[ServerName]   
      AND pMon.[object_name]   = pMonPrior.[object_name]  
      AND pMon.[counter_name]  = pMonPrior.[counter_name] 
      AND pMon.[instance_name] = pMonPrior.[instance_name]
```

**Comment by BrentOzar** [comment]
When people do a filter on the view for a date range, like where checkdate between '2017/12/01' and '2018/01/01', is the predicate pushed down through the underlying tables, or does this query do the group-by across all rows, and then filter? 

Just double checking - I'm assuming you've got a lot of data so you can check this easily. (Like compare logical reads before & after, show query plans before & after with PasteThePlan, etc.) Just wanna make sure you'll get the results you want - wouldn't wanna change this more than once. Thanks!

**Comment by 619619** [comment]
A weird issue that I had is that with the ROW_NUMBER generated "CheckDates" CTE, while identical in data to the one generated with LAG, is that SQL Server for some reason decided first to join on all the other fields (exploding the record count) and only then by checkdate:

Query 1 (LAG): https://www.brentozar.com/pastetheplan/?id=HJ33CV2Nf (**Execution time, 3 Seconds**)
Query 2(ROW_NUMBER): https://www.brentozar.com/pastetheplan/?id=B1jZfSnEf (**Execution time, 3+ minutes**; 10x better than the original one, but 60x worse than the LAG one)

I've tried do rewrite is as a CROSS APPLY, but nothing, same result, so i fiddled around a little bit more and found out that forcing a **HASH JOIN** on my CheckDates table brought the performances back in par with the LAG one:  https://www.brentozar.com/pastetheplan/?id=S19UZrnNz
I don't really like hints, but this should be supported from SQL 2008 and still in 2017 CU3 without the query optimizer starts multiplying rows like crazy.

Back to the original question; As far as page reads goes, here are the IO stats for a select without any predicate:

```
(341243 rows affected)
Table 'BlitzFirst_PerfmonStats'. Scan count 36, logical reads 30440, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'Worktable'. Scan count 0, logical reads 0, physical reads 0, read-ahead reads 10652, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'Workfile'. Scan count 64, logical reads 6824, physical reads 757, read-ahead reads 6067, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

 SQL Server Execution Times:
   CPU time = 4796 ms,  elapsed time = 3533 ms.
```

And here what I get by filtering the View by a CheckDate range: https://www.brentozar.com/pastetheplan/?id=BJweZrn4f

```
(28826 rows affected)
Table 'BlitzFirst_PerfmonStats'. Scan count 36, logical reads 30440, physical reads 0, read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'Worktable'. Scan count 0, logical reads 0, physical reads 0, read-ahead reads 6078, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.
Table 'Workfile'. Scan count 14, logical reads 288, physical reads 15, read-ahead reads 273, lob logical reads 0, lob physical reads 0, lob read-ahead reads 0.

 SQL Server Execution Times:
   CPU time = 2079 ms,  elapsed time = 766 ms.
```

The predicate filtering is done indeed in the CTE branch of the plan, what's more bothersome is that the cost estimation and memory grants are totally off the hook (causing TempDB spills)
It shouldn't really be much of an issue since I don't expect people to run this every 2 seconds in production (or run this in production at all), but still, not cool.
What do you guys think?

**Comment by BlitzErik** [comment]
I have a blog post coming up about this, but the short of it is that when you use window functions in a view, cte, or derived table, predicates can't be pushed unless they're in the partition by clause of the WF.

In the case of lag, it's effectively partitioned in the function. In the RN one, it's only in the order by. That makes it ineligible to be safely pushed.
