### ISSUE TITLE
sp_DatabaseRestore: add @CustomPostRestoreSQL parameter

### ISSUE THREAD

**Issue by ShawnCrocker** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1430]
Each site may have some post-restore actions to carry out

Examples: 
- ensure the database owner is "sa" (although could be a separate parameter)
- Invoke anonymisation script (I work for a Swiss bank)
- "Unlive" a database eg remove live email addresses or live paths from a database restored to a test server
- run a backup of the restored database

I don't think it should replace other parameters (such as @ForceSimpleRecovery) though for clarity, logging, confusion, risk of errors etc. It really should be for site customisations.

**Comment by BrentOzar** [comment]
Why should sp_DatabaseRestore do that work? Why not do it in whatever tool is calling sp_DatabaseRestore, like an Agent job?

**Comment by ShawnCrocker** [comment]
Personal preference? I often prefer one-stop scripts and a simpler calling mechanism

Changing owner to sa could be in scope though.
This  is a one line commands that could be implemented as a new flag

**Comment by BrentOzar** [comment]
I hear ya, but the problem is error handling - something that sp_DatabaseRestore doesn't do well to begin with. To do it right, you'd also need to surface which part of the proc failed - the database restore, or the post script, and what the message was. Is that really something you wanna tackle? 

(If so, I like where you're going with it - just worried about the supportability when the script fails, and users start complaining, and it turns out that their post-restore script had a bug.)

**Comment by ShawnCrocker** [comment]
Good points: it's way too ambitious for public use.
