### ISSUE TITLE
Bug Version 20180301 - Zeile 4841,4826,4829   Ungültiger Spaltenname 'database_id'.

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1465]
**Do you want to request a *feature* or report a *bug*?**
Bug Version 20180301

**What is the current behavior?**
says "Meldung 207, Ebene 16, Status 1, Prozedur sp_Blitz, Zeile 4841 Ungültiger Spaltenname 'database_id'.
Meldung 207, Ebene 16, Status 1, Prozedur sp_Blitz, Zeile 4826 Ungültiger Spaltenname 'database_id'. Meldung 207, Ebene 16, Status 1, Prozedur sp_Blitz, Zeile 4829 Ungültiger Spaltenname 'database_id'."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 10.50.6220 on Server 2008 R2 Standard Edition

**Comment by BrentOzar** [comment]
Hola! Brent here. Because this is an open source script, and because we don't have remote access to the server, you can jump start the troubleshooting by opening the script and looking at what's being done on the lines where the error fires. Then, run that script by itself - outside of sp_Blitz - to figure out where the error is coming from.

Once you've found that out, come back here and report back with those details. I'll leave the issue open for a couple/few days. If you're too busy or don't want to dig into it, no problem - we'll close the issue. Thanks!

**Comment by MisterZeus** [comment]
Using a bit of sneaky T-SQL:
SELECT * FROM sys.messages WHERE message_id = 207
we see that in German-language builds of SQL Server, the "database_id" column referenced on line 4841 of sp_Blitz is considered invalid.

This seems to point to the sys.dm_exec_sessions DMV within Check #215.

I really hope Microsoft doesn't change system DMV column names between different-language SQL instances!

**Comment by BrentOzar** [comment]
@MisterZeus OK, great, thanks for the issue. Going forward, keep in mind that the folks on the other side of the screen are volunteers too. The more information you can give them to help things work better on your system, the faster you can get the results you want. Enjoy the free software, and hope it makes your job easier.
