### ISSUE TITLE
sp_blitz should ignore soft-NUMA for odd cores check

### ISSUE THREAD

**Issue by jobbish-sql** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1474]
**Do you want to request a *feature* or report a *bug*?**
I am reporting what I believe to be a bug in version 6.3 of sp_blitz.

**What is the current behavior?**
The check for odd number of cores in a NUMA node doesn't account for soft-NUMA. The comment for the section in question is:
/*Perf - Odd number of cores in a socket*/

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Install SQL Server 2016 or later on a bare metal machine with 10 or 14 physical cores per socket with hyperthreading disabled or on a VM with access to 10 or 14 logical CPUs per memory node. Auto soft-NUMA will create NUMA nodes with odd numbers of schedulers and you'll see an error about odd numbers of schedulers per NUMA node.

Here's an example:

https://dba.stackexchange.com/questions/196327/automatic-soft-numa-results-in-odd-number-of-cores/

**What is the expected behavior?**

Based on the code and comments, the intention is to look at the number of schedulers per memory node instead of per soft-NUMA node. A query like the below should work, but I'm unable to test it at the moment:

SELECT  1
FROM    sys.dm_os_schedulers dos
INNER JOIN sys.dm_os_nodes don ON dos.parent_node_id = don.node_id
WHERE   dos.is_online = 1
AND dos.scheduler_id < 255
AND don.memory_node_id < 64
GROUP BY don.memory_node_id,
dos.is_online
HAVING  ( COUNT(dos.cpu_id) + 2 ) % 2 = 1;

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This mostly affects SQL Server 2016 and 2017 with the release of auto soft-NUMA. There could have problems in previous versions with manual soft-NUMA.

**Comment by BlitzErik** [comment]
Sounds like a VM problem.

**Comment by jobbish-sql** [comment]
I'd like to speak to the manager.

**Comment by BrentOzar** [comment]
Hello, and welcome to Blitz Burgers. I apologize for our front-line cashier. We have to hire whatever help is available here locally, and sometimes, like our meat, they're sub-prime.

Now that we've got that out of the way, as we say here, "Let's Go Get Blitzed!" 

Yeah, I agree - I'm guessing that the original intent of this rule was to find NUMA nodes with odd (relative to the others) numbers of cores - like one with 4 cores, and another with 3 cores. I'm afraid to go back through the code because I was probably the one who wrote this originally, hahaha. I tweaked it now to achieve that goal instead:

 - On a normally configured server or VM, the priority 10 "Uneven Core Distribution Across NUMA Nodes" warning shouldn't show up.
 - Create a VM with a low but odd number of cores, like 3 or 5, and it still shouldn't show up because you'd only have one NUMA node. (Even if you do something dorky like set it up as a single-core-per-CPU VM, then you'd end up with an odd number of NUMA nodes, but I'm not even going near that.)
 - Create a VM with a high and odd number of cores and multiple CPU sockets, like 19 or 31 or 1,973, and the priority 10 "Uneven Core Distribution Across NUMA Nodes" will show up.

How's that sound instead?

**Comment by jobbish-sql** [comment]
All of that sounds good. I took a quick look at the new code and see that you still use parent_node_id instead of memory_node_id. Do you mind explaining why?

**Comment by BrentOzar** [comment]
I don't have a reason off the top of my head - I'm vaguely remembering something about AMD CPUs having a gotcha with this, but I don't know well enough to say either way. Should we be using memory_node_id? I'll take your word if you say yeah.

**Comment by jobbish-sql** [comment]
Good point. There's something different about AMD but I couldn't tell you how that works. Never tested on that. As is, the code will throw the error if someone has a 2 X 22 with auto soft-NUMA. Is that ok?

**Comment by BrentOzar** [comment]
OK, to reduce the back-and-forth (I'm totally tied up this week), can you write the change in the check that you would want to see, keeping in mind that we need to alert people when they have unevenly distributed cores in a VM? (I just had another user this past week with a VM with 4 cores in 1 CPU, and 3 cores in the 2 other CPUs.)

**Comment by jobbish-sql** [comment]
Sure. My earlier hesitation stemmed from not being able to test on AMD. As far as I understand it, memory_node_id is closer to a physical socket than node_id. Using it should work in the most common case: intel CPUs on a VM with or without auto soft-NUMA. My sources tell me that some AMD chips are effectively two chips glued together in a single socket, so you can get two different memory_node_ids within SQL Server even with just one physical socket on the host. I think that the query will still work, but I can't test it.

Here's a simple version:

SELECT MIN(schedulers) as bottom, MAX(schedulers) AS topper
FROM (
SELECT memory_node_id, SUM(online_scheduler_count) schedulers
FROM sys.dm_os_nodes
WHERE  memory_node_id < 64
GROUP BY memory_node_id) AS nodes
HAVING MIN(schedulers) <> MAX(schedulers)

**Comment by BlitzErik** [comment]
After talking with Joe, I think the best thing to do (with minimal changes) is to add an EXISTS check to the query. This is tough because I don't have a machine I can easily mimic the issue on.

When I try to change VMs to have lopsided CPUs, Hyper V and Virtual Box seem to thwart me and put things where they should be.

```
SELECT 1
FROM
       (   SELECT    memory_node_id, SUM(online_scheduler_count) AS schedulers
           FROM      sys.dm_os_nodes
           WHERE     memory_node_id < 64
           GROUP  BY memory_node_id ) AS nodes
HAVING MIN(nodes.schedulers) <> MAX(nodes.schedulers);
```

**Comment by jobbish-sql** [comment]
Have you tried using CPU affinity to put one of the schedulers offline?

**Comment by BlitzErik** [comment]
That's what I did to test the original code, but that seems to not be what you're after here?
