### ISSUE TITLE
sp_Blitz enhancement - include information if server part of an Availability Group

### ISSUE THREAD

**Issue by JulieOKC** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1475]
************************** Script included! **************************

 **Do you want to request a *feature* or report a *bug*?**
Enhancement: add information if server is a part of an Availability Group. Is the connection to a node or a listener. Is it a primary or secondary node.

 **What is the current behavior?** No information is given regarding AGs

 **Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?** Has not been a part of sp_Blitz. I ran the script below against SQL 2005 through 2016 with AGs in SQL 2012, 2014 & 2016. No errors resulted.

Script will need to be updated for Finding (optional), URL, and CheckID. This can be found in the last SELECT statement.

```
/** TSQL script below *************************************************************************?

DECLARE @strData as nvarchar(125);
DECLARE @NodeListener AS nvarchar;
DECLARE @ListenerConnect as BIT;
SET @strData = '';
SET @NodeListener = '';
SET @ListenerConnect = 0;

IF EXISTS (SELECT 1 FROM msdb.sys.system_objects
  WHERE NAME='dm_hadr_availability_replica_states')
BEGIN -- Server is AG
     SELECT @strData = 'This server is a ' + role_desc  + ' node of the Availability Group.'
     FROM sys.dm_hadr_availability_replica_states
     WHERE is_local = 1

     SELECT @ListenerConnect = COUNT(agl.dns_name)
     FROM sys.availability_group_listeners agl
     JOIN sys.availability_group_listener_ip_addresses aglip ON agl.listener_id = aglip.listener_id
     JOIN sys.dm_exec_connections ec ON aglip.ip_address = ec.local_net_address
     WHERE ec.session_id = @@SPID

    SELECT @strData = @strData +
       CASE @ListenerConnect
          WHEN 1 THEN ' Connected to the listener.'
          WHEN 0 THEN ' Connected to the server and not the listener.'
       END -- CASE
       WHERE @strData IS NOT NULL AND @strData <> ''
       
END -- Server is AG
ELSE
     BEGIN -- Server is not AG
        SET @strData = ''
     END -- Server is not AG
SET @strData = RTRIM(LTRIM(@strData));
 
SELECT @@SERVERNAME, 200, 'Informational','Server is part of AG cluster'
, NULL, 'https://BrentOzar.com/',
@strData, NULL, NULL, 9999 --Update CheckID
WHERE @strData IS NOT NULL AND @strData <> '';
```

**Comment by BrentOzar** [comment]
Howdy ma'am! Thanks for the contribution.

There's a problem though: a server can have multiple (indeed, many) rows in sys.dm_hadr_availability_states when multiple AGs are involved. Take this cluster:

![replicas](https://user-images.githubusercontent.com/245462/37456428-5796f5ac-280d-11e8-9c20-131f04b3bf11.png)

In that case, when it's run on different servers, it should list the role_desc, but also the AG name (which means joining to more DMVs, heh.) For example:

- Node 1 should report that it's a primary for AG: Payroll, secondary for AG: Web
- Node 2 should report that it's a primary for AG:WebSite, secondary for AG: Payroll
- Node 3 should report that it's a primary for AG:Reports, secondary for AG: Payroll

Etc. But to do that, it's going to need to be set-based instead of using a single strdata variable. Can you tackle that? I'd do it, but I don't have any AGs handy.

**Comment by JulieOKC** [comment]
I am working on another issue today, but will have time next week to work on it then.

**Comment by BlitzErik** [comment]
@JulieOKC going to close this out for now. Feel free to reopen it when you're ready to work on it.
