### ISSUE TITLE
sp_Blitz: DBCC event counter (check 203) does not ignore TRACEON and TRACEOFF events generated by SQL 2014 Setup

### ISSUE THREAD

**Issue by Totty1973** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1519]
**Do you want to request a *feature* or report a *bug*?**
I think its a bug in sp_blitz in Version '6.0' / '20171201' and 'DEV', 
I think it does report "benign" events
and it does count each of them twice
and it does report wrong time.

**What is the current behavior?**
Check 203 reports "6 DBCC events have taken place between Apr  3 2018 10:56AM and Apr  3 2018 10:56AM. This does not include CHECKDB and other usually benign DBCC events.	NULL	NULL	203", the only three (not six) entries i can find are "DBCC TRACEON 4606, server process ID (SPID) 7. This is an informational message only; no user action is required." and "DBCC TRACEOFF 4606, server process ID (SPID) 7. This is an informational message only; no user action is required." and "DBCC TRACEOFF 1717, server process ID (SPID) 7. This is an informational message only; no user action is required." and all of these three events happenend around 10:06 (and not 10:56)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
Install SQL 2014 SP2-CU11 (integrated with "Setup.exe /Action=Install /UpdateEnabled=TRUE /UpdateSource=".\Updates")

**What is the expected behavior?**
should not report these events 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Install SQL 2014 SP2-CU11 Standard-Edition on Server 2012 R2 Standard-Edition.

**Comment by BrentOzar** [comment]
Sure, sounds good! You're free to start coding it per the contributing guide:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you've got any questions, holler. Thanks! If you didn't plan on coding it yourself, just let me know and I can close the issue - we don't really take requests, but you might be able to recruit someone else to code it for you in the #FirstResponderKit channel in SQLslack.com.

**Comment by Totty1973** [comment]
I dont know how to debug check 203, looks rather complicated, and I really think its a bug, Its a newly installed SQL-server on a newly installed Windows-Server running only AdventureWorks and nothing else.

**Comment by BrentOzar** [comment]
I understand, but the way open source works is that we're all volunteers here. I totally get where you're coming from - "Brent's script has a bug, he needs to drop everything and fix it" - but in this case, the bug isn't really a big deal for me personally. If it's a big deal to you, and you want to devote the effort to fixing it, great! Go for it. Otherwise, I'm going to let this one be as-is.

Every day, I have to make tough decisions between doing my day job, doing my hobbies, and spending time with my family - just like you have to. I do really appreciate that you took the time to file the bug, but if neither of us have the time to fix it, then we'll just go ahead and close this as a known issue. There are a few in sp_Blitz - I know, hard to believe, right? ;-)

**Comment by BrentOzar** [comment]
Closing this based on the other issues. Thanks though!
