### ISSUE TITLE
BlitzLock - filter out check id 2 for index deadlocks on heaps

### ISSUE THREAD

**Issue by jadarnel27** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1569]
**Do you want to request a *feature* or report a *bug*?**  
Report a bug (at least I think it's a bug...probably something Erik could fix while drinking on an airplane).

**What is the current behavior?**  
If you have a page deadlock on a heap, an odd-looking row is reported in the second resultset in the check_id 2 section.  It's an index named "UNKNOWN," probably due to the null entry in sys.indexes for heaps.  Here's a screenshot:

![lock-heap](https://user-images.githubusercontent.com/13036637/39790785-e4069326-5305-11e8-98e2-738420ad102a.PNG)

The "object deadlocks" row is correct (all of my deadlocks were page locks in the TableWithFragmentedIndex table).  The "index deadlock" row is incorrect, I think.  There were no index deadlocks.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**  
1. Cause a deadlock that involves a heap (pages in the table)
2. Run sp_BlitzLock

**What is the expected behavior?**  
I think this row should probably just be gone.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**  
I don't think this worked in previous versions.  I imagine it affects all supported versions of SQL Server for this script.

**Comment by BrentOzar** [comment]
Howdy, and welcome to the First Responder Kit repo!

The "UNKNOWN" row refers to the heap. (Heaps are technically indexes in the sense that they're stored in sys.indexes as index id 0 for that table.)

If you want to remove that row, that's probably fair - I don't think any of us would fight you too hard on that. I'm fine with the row being in there, or not being there, either way.

To see the contributing guide, go to the home page of the repo ( http://firstresponderkit.org ) and scroll down to the "How to Get Support" question. You've done exactly the right first step - filing an issue to discuss the change you want to make. You're now green-lighted to make the change, heh. (Or you can pop into the Slack room to discuss it further with folks - I don't think you're going to get a lot of discussion on it because I'm guessing folks will be fine with this either way, if the line is there or not there.)
