### ISSUE TITLE
sp_BlitzFirst @BlitzCacheSortOrder changed to "memory grant" on less than 20GB free memory

### ISSUE THREAD

**Issue by dbadave87** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1580]
**Do you want to request a *feature* or report a *bug*?**
Bug (typo?) in sp_BlitzFirst - (v6.5)

**What is the current behavior?**
When triggering sp_BlitzFirst as part of a SQL Agent job, this fails at the same time every day with this error:

> "Your version of SQL does not support sorting by memory grant or average memory grant. Please use another sort order."

While this error is valid based on the triggered query (i.e. sp_BlitzCache @SortOrder = 'memory grant'), as this server is version 12.0.4522.0, it prompted investigations into potential memory grant issues. These investigations highlighted an issue with when the @BlitzCacheSortOrder uses "memory grant".

I believe the @BlitzCacheSortOrder was triggered under the wrong  circumstances. Based on this comment: "If Free Memory is >20GB, and >= 30% of Total Memory..." (taken from: https://www.brentozar.com/blitz/too-much-free-memory/), I believe the following line, within the "/* Server Performance - Too Much Free Memory - CheckID 34 */" section of sp_blitzFirst:

**AND CAST(cTotal.cntr_value AS BIGINT) > 20480000000**

...should in fact be:

**AND CAST(cFree.cntr_value AS BIGINT) > 20480000000**

Instead, based on the 27GB memory of this server, this is in fact triggering the change to @SortOrder when 'Free memory (KB)' perf counter is ~9GB. While this is still cause for investigation on my side, this shouldn't have triggered.

**What is the expected behavior?**
This should only update the @SortOrder and run sp_BlitzCache @SortOrder = 'memory grant' when free memory over 20GB.

Or perhaps the paragraph on https://www.brentozar.com/blitz/too-much-free-memory/ is incorrect?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I have only recently installed blitz scripts on this machine. 

I am yet to read through contribution guide and get familiar with GitHub so if someone is able to pick up and fix, it would be appreciated.

**Comment by BrentOzar** [comment]
Howdy! Dang it, I was so excited when I read this because I love your troubleshooting process, but it turns out the code is correct. Here's that section of code:

```
AND CAST(cTotal.cntr_value AS BIGINT) > 20480000000
AND CAST(cTotal.cntr_value AS BIGINT) * .3 <= CAST(cFree.cntr_value AS BIGINT)
```

The first line is checking to make sure you have at least 20GB of RAM. We don't want to complain about free memory on tiny servers.

The second line is checking where free memory is >= 30% of your total memory. 

So if you had exactly 20GB, then we'd be alerting whenever you had 6GB memory free - which is typically due to queries asking for large workspace grants.

I'm going to close this because it's behaving as-designed, but by all means, you can continue asking clarification questions on it. I love your troubleshooting thought process, and you were very close.

**Comment by BrentOzar** [comment]
Well, I say that - but now that I read the page more closely, I think you're right!
