### ISSUE TITLE
Ignore TempDB on CheckId 80

### ISSUE THREAD

**Issue by LinkOps** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1584]
In accordance with TempDB advice taken from Kendra Little TempDB should be set to a static size in a multi-file configuration and have auto-growth turned off. This is to prevent one tempdb file being used more preferably over the others.

Therefore TempDb should be excluded from CheckId 80 (Max File Size Set) as it highlights a red herring.

**Comment by BrentOzar** [comment]
I'm going to play devil's advocate here. I'm guessing that Kendra's talking about a specific volume dedicated to TempDB - in which case you grow the files out to fill up the volume. In that case, it doesn't matter whether auto-growth is on or off - it has no effect.

If, on the other hand, you've got TempDB on a volume that isn't dedicated just to it, how do you know what the right max size is? Figure that out, and then we can tell the users to set it to that. (I haven't been able to figure that out myself yet.) Otherwise, leaving auto-growth on is how you prevent outages from TempDB filling up.
