### ISSUE TITLE
Add a primary key to SqlServerVersions

### ISSUE THREAD

**Issue by reharmsen** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1663]
**Do you want to request a *feature* or report a *bug*?**
Request a feature 

**What is the current behavior?**
SqlServerVersions does not contain a primary key, this won't allow us to replicate this table through our central DBADA database.

**What is the expected behavior?**
SqlServerVersions should contain a primary key.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2014 SP2-CU9

I see two options:
1) Add an extra ID column with AutoID and make it the primary key
This can be done by adding this to the table creation

[ID] [int] IDENTITY(1,1)

PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)

2) Add a primary key with the columns 'MajorVersionNumber', 'MinorVersionNumber' and 'ReleaseDate'
This can be done by adding this to the table creation

 CONSTRAINT [PK_SqlServerVersions] PRIMARY KEY CLUSTERED 
(
	[MajorVersionNumber] ASC,
	[MinorVersionNumber] ASC,
	[ReleaseDate] ASC
)

**Comment by BrentOzar** [comment]
I wouldn't add a field since the table's out already in the wild, but you're welcome to add the clustered key. For implementation, you'd just want to either only do it when the table is created, or else add a check for the existing table to see if the key exists, and make sure no duplicate data exists, then add it.

Here's the contributing guide for instructions on making the change:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Thanks!

**Comment by BlitzErik** [comment]
I disagree -- if you want this modification made, you should create an issue on @jadarnel27 's repo for the project:

https://github.com/jadarnel27/SqlServerVersionScript

**Comment by reharmsen** [comment]
@BlitzErik I'll file an issue @jadarnel27 's repo
