### ISSUE TITLE
dacpac based deployment - VS SSDT project

### ISSUE THREAD

**Issue by gephartr** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1710]
I work at a shop where all of our database code is in SSDT projects and are deployed incrementally through the sqlpackage/msbuild/tfs methods.  I have had my own maintenance project for a decade or so, but it is far easier to stay current by using the great code of the community.  My first step was replacing my own indexing/consistency checks with Ola's - and I would like to replace my performance warehousing and reporting with the First Responder Kit.

My first step with Ola's was to create a fork and turn his code into a VS project that creates a dacpac that becomes a part of my deployed database.  The next step would be to do the same with the code here.

Would the community here like to have a VS project / dacpac output of the first responder kit - instead of my just doing it privately at work?

**Comment by BrentOzar** [comment]
That's a great question. The tough part is that we need to be able to deploy the updated scripts every month in as little time as possible. Is there an automated way that we could do this without anyone else's involvement? 

(I'd hate to have people get hooked on it, and then if you're busy or on vacation, have the monthly release get delayed. I'd also hate to have an out-of-date deployment kit sitting out there with known bugs.)

**Comment by gephartr** [comment]
"Is there an automated way?"  Sure - scripting will let you do anything you want to do, assuming the proper tooling is available.

"In as little time as possible."  So, there is nothing faster than just executing a script.  The question is, how fast is fast enough - and do the benefits outweigh the difference in deploy time.  So, say that you can deploy the script in 50 ms and a dacpac deploy would complete in 30 seconds (or 60 seconds) is that still fast enough?

In my mind, if you wanted to do this my thought would be you have the project file (and maybe a couple example deployment scripts) - and then you would have the files for your objects (and maybe a dacpac for Ola's work).  You could keep all of the objects in a single file or do a file per object (which might be easier for people doing updates to single items of change).  All up to you.

So I don't think there would be any specific reliance on me any (after whomever is familiar with the process).

(In theory, a custom program / script could be made that uses dacfx to deploy / update.)

**Comment by BrentOzar** [comment]
> So I don't think there would be any specific reliance on me any (after whomever is familiar with the process).

So what you're saying is, we need to start doing the additional process. That's the part where I need to hit the brakes - we already do a ton of volunteer work for the community, and we can't take on additional work as part of a monthly release process at this time. If it isn't an automated solution that doesn't require additional work on our part, then we need to take a pass.

That's totally okay - it just means that it would be a separate Github project that you'd manage. Our stuff is completely open source (MIT licensed), which means you're welcome to tackle that. You can keep it as up to date as you want, whenever you've got time. You can also bundle other peoples' open source work, too, like Ola's scripts.

I'll close this issue just because it's not a good fit for this particular repo, but I wanna make it clear that you are 100% welcome to do it in your own repo. (This is one of the things I love about open source - you can take our work and run with it.)
