### ISSUE TITLE
sp_BlitzIndex - shows duplicate keys alert for indexes in different databases

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1712]
**Do you want to request a *feature* or report a *bug*?**
Bug. Not really big bug, like a West-Nile-infested Miami mosquito, and not even a cockroach. Just one of those insects where you go, "Oh hey, I don't really want you in the house, but I'm going to watch you hang out for a minute." Maybe like a ladybug.

**What is the current behavior?**
If you have 2 databases where object IDs are the same (like two restored copies of the same database), sp_BlitzIndex reports duplicate keys, but the database names are different. See 20180808_132522 in our client files for an example.

**What is the expected behavior?**
Only show dupes if the index is in the same database.

**Comment by RichBenner** [comment]
I've made a test case for this and tried to replicate it but it's not reporting the issue you mentioned. Could you share the parameters that might be causing this?

**Comment by BrentOzar** [comment]
It's sp_BlitzIndex @GetAllDatabases = 1, @Mode = 4.

**Comment by RichBenner** [comment]
Yeah, that's what I've been trying but it's not showing the issue on mine. I'll keep working to see if i can replicate.

**Comment by BrentOzar** [comment]
(And I totally agree - a straightforward repro isn't doing it, but we've got the data seeing it in action, so I just gotta figure out what the underlying data is that's causing it. Not sure what yet. I wish I could share the client data, but can't do that.)

**Comment by RichBenner** [comment]
Totally understood. I've got quite a few development servers that have duplicated object id's (copies of the same backup for testing) so i'll test it on any I can find. Hopefully narrow it down if I can find one of the little buggers

**Comment by BlitzErik** [comment]
Is this still active?

**Comment by BrentOzar** [comment]
Yeah, we've had clients hit it, I just haven't had the time to dig into the analysis of why yet.

**Comment by BlitzErik** [comment]
I think I figured this out!

It's not actually catching cross-database dupes, it just looks like it is. 

In our first CTE, we're getting all possible dupes, and when we join outside of it it, we're filtering on this:

`WHERE ips.total_reserved_MB >= CASE WHEN (@GetAllDatabases = 1 OR @Mode = 0) THEN @ThresholdMB ELSE ips.total_reserved_MB END`

In some cases, we'll only find one index that has a size > 250MB when we get all databases. This doesn't happen in Mode 4 standalone (obviously). I'm looking at some client data showing this exact issue.

Here are the index sizes:
![image](https://user-images.githubusercontent.com/11590415/45563338-0c03bf00-b81b-11e8-80bf-eef3902af06b.png)

Only the one > 250MB shows up in the dupes. It's just more clear here because it looks like the restored copy and the regular copy have slightly different indexes.

Which makes me think that we need to also do this filtering in the CTE that gets the initial set of objects, too. Creating a PR for testing.
