### ISSUE TITLE
sp_Blitz only needs 3 tiny changes to make it run OK in SQL 2005

### ISSUE THREAD

**Issue by MisterZeus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1738]
**Do you want to request a *feature* or report a *bug*?**
Bug: even though we don't support SQL 2005, we can get sp_Blitz to run OK in it by changing 3 lines of code.

**What is the current behavior?**
Run the sp_Blitz creation script on a SQL 2005 server.

**What is the expected behavior?**
It should create the sp_Blit sproc OK and the sproc should run OK too.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2005. Not sure for how long this has been broken.

**Comment by MisterZeus** [comment]
Fixed in pull request #1737 !

**Comment by BrentOzar** [comment]
Howdy, and thanks for the contribution. Unfortunately, that's not the only change required - when you go to output the data to table, 2005 fails due to the SYSDATETIMEOFFSET we're using. (There are also gotchas around old compatibility levels in user databases, too.)

If these changes make it work well enough for your needs, you're totally okay to keep using it - this is one of the things I love about open source. However, I don't want to force other folks to change their coding styles in order to support 2005.

Next time, to save yourself a little heartache, check out the contributing guide. It lays out how to go about proposing a change here in an issue first before coding it, and letting the community discuss it.

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

**Comment by MisterZeus** [comment]
Ah, makes sense, since there are extra hidden SQL 2005 problems that my limited testing didn't catch...
Thanks for considering it anyway!
