### ISSUE TITLE
sp_AllNightLogSetup don't create agent jobs for Restore if only being used for backup

### ISSUE THREAD

**Issue by gavdraper** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1742]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
sp_AllNightLogSetup creates agent jobs for both restore and backup even if you're only setting it up for backups and the other way round if you're just configuring a server with it for restore it ends up with the backup agent jobs. I realise there is a switch to have them disabled.

**What is the expected behavior?**
If no restore path is specified I guess this implies it's being used for backup only and it could just not create the agent jobs for restore?

**Comment by BrentOzar** [comment]
Yes, because after failover, you may end up doing log shipping going in the other direction. If you don't need the extra jobs, you can delete those after installation.

If you'd like to code this yourself, though, you can: check out the Contributing.md file for how to get started.

If you want to code this yourself, leave a comment here and we'll reopen the issue and assign it to you.

Thanks!
