### ISSUE TITLE
sp_Blitz - dbo.sp_MSforeachdb vs master.sys.sp_MSforeachdb (?)

### ISSUE THREAD

**Issue by hamidmira** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1752]
Hello, 
In the script file sp_Blitz.sql, I suggest, for greater clarity, that your replace 
`EXEC dbo.sp_MSforeachdb '...'`
by
`EXEC master.sys.sp_MSforeachdb '...'`

Thank you very much for your contributions

**Comment by BrentOzar** [comment]
Thanks, glad you like our work! We're going to decline this for now just because it doesn't add functionality or fix a bug. We only have so many hours per week, and we need to focus on things that add value to the community scripts. If you'd like to tackle this yourself, though, you're welcome to read the contributing guide and get started. Thanks again!
