### ISSUE TITLE
sp_AllNightLog Is Somehow Missing Logs

### ISSUE THREAD

**Issue by gavdraper** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1768]
**Do you want to request a *feature* or report a *bug*?**
Bug in sp_AllNightLog Version 2.9 (And possibly other versions)

**What is the current behaviour?**
I have it setup to restore logs for several databases every 30 seconds. It works fine most of the time but overnight one of  the databases goes through batch processing and generates about 15GB of logs in 10 minutes, this seems to have a knock on effect that sp_AllNightLog sets a last start restore time ahead of a log file it has not restored which then causes no logs from this point on to get restored on that DB.

msdb.dbo.restore_worker at this point still thinks everything is running fine and continues to update Start and finish times.

If I then update msdb.dbo.restore_worker and set the last start time to before the last file that it's not restored then it recovers and carries on about it's business.

I've no idea if this could make a difference but logs are being restored from a network share so the process of restoring the log can take a bit longer once the 15GB logs have dropped.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2017

**Comment by BrentOzar** [comment]
Oh no, sorry to hear that! We (Brent Ozar Unlimited) aren't using sp_AllNightLog on any current projects, so I'm afraid we can't be too much help troubleshooting it at the moment.

If I were you, since you're experiencing the issue in production, I'd continue to keep digging and see if you can track down the issue. You could also set up a job to periodically check for restores that aren't happening, and kick start 'em.

Sorry I don't have an easier answer, but I just don't want you sitting on the other side of the screen thinking that we can leap into action to fix this. :-D I wish I could, but our knowledge of sp_AllNightLog has just gotten pretty stale. Other folks might hop into the ticket to help, though.
