### ISSUE TITLE
Add a slicer by server name to the Power BI Template

### ISSUE THREAD

**Issue by ck75** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1827]
**Do you want to request a *feature* or report a *bug*?**
Feature: Add a slicer by server name to the Power BI Template

**What is the current behavior?**
As Discussed on the #FirstResponder Slack Channel
I've setup a job on multiple servers to capture the blitz data for that particular SQL Server and then connect Power BI to the database that stores the information. This is resulting in multiple Power Bi Reports for our SQL estate. 
Can I request a slicer based upon server name, that way it's just a drop down to change the data you're looking at?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

**Comment by EmanueleMeazzo** [comment]
You're right, I've added the server selector on the new report pages, but it's missing in the original overview.
Since the process for sending PowerBI changes consists in listing the modifications to made, this pull request is basically already written.

However, one thing comes up in my mind, should we synchronize the server slicer in every page (in order to have it already on the previously selected server when changing page)? Or leave it wild and free?

**Comment by BlitzErik** [comment]
@ck75 you haven't responded to @EmanueleMeazzo in about a month -- should we close this issue out?
