### ISSUE TITLE
Make sp_BlitzQueryStore installable on versions lower than 2016 but failing

### ISSUE THREAD

**Issue by jeffchulg** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1961]
**Is your feature request related to a problem? Please describe.**
I would like to be able to install all the stored procedures from this package.
In other FRK scripts, when something is not "as expected", the SP fails, like in sp_BlitzIndex when the script is outdated.

Plus, the FRK would have only one "all-in-one" installation script. 

**Describe the solution you'd like**
As the QueryStore feature is not available below 2016, the condition defined before the SP creation could be integrated inside its code, and `DROP IF EXISTS` statement should be put in dynamic statements `EXEC sp_executesql N'DROP IF EXISTS;';`.
I've tested on a SQL Server 2014 and it works like a charm.

**Describe alternatives you've considered**
Let as is

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

Yes, accepted (and see above).

**Comment by BrentOzar** [comment]
Hi Jeff. Ooo, thanks for the commit, but here's the thing: dynamic SQL is a whole lot harder to write and troubleshoot.

I recognize that this change would make your life a little easier around installation time, but it makes the maintainers' and authors' lives a lot harder. I need to make authoring and testing as easy as practical, which means unless dynamic SQL is really needed desperately for something, then we'd probably rather avoid it.

Going forward, can you make an issue before you want to make a change, and then discuss the change you're looking for in the issue? We talk about this in the contributing guide (linked on the home page of the project.) I hate telling you that, because your code is great and you're a good contributor, but it'll just save you some heartache on changes like this.
