### ISSUE TITLE
BlitzFirst incorrectly skipping Plan Cache Analysis due to British Summer Time

### ISSUE THREAD

**Issue by planetmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2096]
**Version of the script**
7.7

**What is the current behavior?**
Running BlitzFirst with @CheckProcedureCache=1 never does the Plan Cache Analysis on systems where SYSDATETIMEOFFSET() returns a positive Time Zone offset value.

 Script constantly outputs

'Query Stats', 'Plan Cache Analysis Skipped', http://www.BrentOzar.com/go/topqueries', 'Due to excessive load, the plan cache analysis was skipped. To override this, use @ExpertMode = 1.

There are two issues.

1. Running with @ExpertMode = 1 does not override this.  The logic that outputs this message never checks the @ExpertMode flag.  Logic below shows no reference to @ExpertMode

  IF DATEDIFF(ss, @FinishSampleTime, SYSDATETIME()) > 10 AND @CheckProcedureCache = 1

2. @FinishSampleTime is first allocated the value of SYSDATETIMEOFFSET + @Seconds but in the above logic check, the DATEDIFF compares @FinishSampleTime which is a SYSDATETIMEOFFSET to SYSDATETIME.  On my system in the UK currently in British Summer Time, the @FinishSampleTime has a +01:00 time difference to SYSDATETIME which results in a DATEDIFF in seconds value of 3600 - @seconds.  This will always exceed the hardcoded 10 seconds and consequently the plan analysis never occurs. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run [sp_BlitzFirst] @expertmode = 1,@seconds = 5,@CheckProcedureCache=1 on any server with a positive current timezone offset value.

Below is a test rig replicated the flawed logic in Blitzfirst.  The final select should output -5 but outputs 3595

DECLARE @FinishSampleTime DATETIMEOFFSET
DECLARE @Seconds INT = 5
SELECT @FinishSampleTime = DATEADD(ss, @Seconds, SYSDATETIMEOFFSET())

SELECT SYSDATETIME() AS [SYSDATETIME],@FinishSampleTime AS [@FinishSampleTime]

SELECT (DATEDIFF(ss, @FinishSampleTime, SYSDATETIME()))

**What is the expected behavior?**
BlitzFirst does the Plan Cache Analysis when @CheckProcedureCache = 1 and process takes less than @Seconds, or BlitzFirst always does the Plan Cache Analysis if @ExpertMode = 1.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

Same result on 

Microsoft SQL Server 2012 - 11.0.2100.60 (X64) 
	Feb 10 2012 19:39:15 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

**Comment by ChadMasti** [comment]
I too confirm hitting the same bug, looking forward to a fix, TIA Brent :-)
Invocation to sp_BlitzFirst is via:
EXEC sp_BlitzFirst  @CheckProcedureCache = 1,  @CheckServerInfo = 1,  @ExpertMode =1 ;
Results of above queries in above mentioned bug/post is below (in order):
SYSDATETIME	@FinishSampleTime
2019-09-17 17:58:27.6815061	2019-09-17 17:58:32.6815061 +02:00
(No column name)
7195
My instance details below:
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64)   Aug 15 2017 10:23:29   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) 
I get the row below from call to sp_BlitzFirst:
Priority	FindingsGroup	Finding	URL	Details	HowToStopIt	CheckID	StartTime	LoginName	NTUserName	OriginalLoginName	ProgramName	HostName	DatabaseID	DatabaseName	OpenTransactionCount	QueryPlan	QueryText	PlanHandle	SqlHandle	StatementStartOffset	StatementEndOffset	Executions	ExecutionsPercent	Duration	DurationPercent	CPU	CPUPercent	Reads	ReadsPercent	PlanCreationTime	TotalExecutions	TotalExecutionsPercent	TotalDuration	TotalDurationPercent	TotalCPU	TotalCPUPercent	TotalReads	TotalReadsPercent	DetailsInt
210	Query Stats	Plan Cache Analysis Skipped	http://www.BrentOzar.com/go/topqueries	<?ClickToSeeDetails -- 
Due to excessive load, the plan cache analysis was skipped. To override this, use @ExpertMode = 1.
 -- ?>	NULL	18	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL

**Comment by BrentOzar** [comment]
Fixed in the dev branch. Thanks so much for the delightfully detailed bug report and easy repro script!
