### ISSUE TITLE
sp_Blitz and sp_BlitzFirst: add warning about high USERSTORE_TOKENPERM cache size

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2134]
Back when I wrote this check in, I apparently tacked it onto the warning about the plan cache being erased recently. I feel like that could easily get missed since the message for it is already pretty long.

If you look [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql#L3459), the code is already written to get the size. 

The question is: is this important enough to be its own check?

If so, is 2 GB the right size to warn at?

**Comment by RobAshton-IM** [comment]
"... is 2 GB the right size to warn at?"

Tough one. If it's 2 GB of 4 GB in total, then I'm interested for sure. If it's 2 GB of 256 GB, then probably not so much.

Is it worth pulling in from SQL OS how much memory is available for all memory caches to fight over to see if USERSTORE_TOKENPERM is using a lot more than its fair share of the available space?

[Looking at this post from Bulent Ozkir](https://blogs.technet.microsoft.com/bulentozkir/2014/01/09/tokenandpermuserstore-related-information-on-sql-server-2012/), and [this thread on SQL Server Central](https://www.sqlservercentral.com/forums/topic/userstore_tokenperm-is-huge) gives me a few ideas of variations on this theme to point out different reasons why USERSTORE_TOKENPERM has blown out of proportion. Perhaps there's a new group of checks here?

**Comment by erikdarlingdata** [comment]
@RobAshton-IM I don't think I'm going to work on this one. If you want to, feel free and let me know. Otherwise, I'll probably close this out.

**Comment by BrentOzar** [comment]
Yeah, I'll tackle it. I've got a client fighting this issue, and I'm pretty sure there's a bug in SQL Server around it. They have a Microsoft support call open, and we're still trying to track it down.

I just ran a quick analysis on the SQL ConstantCare data. There's a good chunk of the population where the USERSTORE_TOKENPERM cache size is >20% of the buffer pool. Unfortunately, sys.dm_os_memory_clerks is one of the larger tables we have in SQL ConstantCare (because I didn't do the right filtering in early exe versions), so the queries take a heck of a long time. (Like, an hour or more.) We just rolled out a newer version of the exe that won't gather as much data, so I should be able to start analyzing this faster. I wanna try to figure out if it correlates with a particular build or version - I'm seeing it on 2016 and 2017 for sure.

For now, I'm guessing we'll flag it at 10% or more of the buffer pool (to help catch the worst offenders) and get the dialog going. I'll code that for the March release - if anybody has input, holler.

**Comment by BrentOzar** [comment]
(Also, just to be horrifyingly clear - that >20% thing is hitting servers with 64GB+ RAM, too, not just small ones. I was excluding anything with less than 32GB RAM from my analysis.)

**Comment by erikdarlingdata** [comment]
Oh wow, 20 percent! that's nutso.

**Comment by erikdarlingdata** [comment]
I'm going to add a check in BlitzCache for this. Can you add it to the labels at some point?

**Comment by BrentOzar** [comment]
You bet! Added it, and got your sp_BlitzCache pull request in for the March release. Thanks sir!

**Comment by BrentOzar** [comment]
Coded in sp_Blitz, will add to sp_BlitzFirst later.
