### ISSUE TITLE
Writing Output to Azure Linked Server Fails

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2145]
**Version of the script**
Version 7.7 Date 20190826

**What is the current behavior?**
When attempting to write results to a linked server in azure the below error is thrown
Msg 50000, Level 16, State 2, Procedure dba.dbo.sp_BlitzIndex, Line 4985 [Batch Start Line 0]
Reference to database and/or server name in 'master.sys.sp_tables_info_90_rowset_64' is not supported in this version of SQL Server.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create linked server pointing to azure (tested that the user can read/write to destination)

executed:
exec dba.dbo.sp_BlitzIndex @OutputServerName = 'serverin-azure', @OutputDatabaseName = 'MyAzureDb', @OutputSchemaName = 'dbo', @OutputTableName = 'BlitzIndex', @Mode =2, @DatabaseName = 'MyOnPremDb'

**What is the expected behavior?**
expected that it would write the data to the table

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

so far I have only tested this against Microsoft SQL Server 2017 (RTM-CU7) (KB4229789) - 14.0.3026.27 (X64)   May 10 2018 12:38:11   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 Standard 6.2 <X64> (Build 9200: ).  

Im unsure if this worked before as it was something I was trying out.

**Comment by BrentOzar** [comment]
Ooo, just looking at the code - I can see that writing to Azure SQL DB won't work because it doesn't support fully qualified object names (server.database.schema.table.) To get this to work with Azure SQL DB, we would need to:

* Check the linked server config to see if it's an Azure SQL DB (I don't even know how to do that offhand, but it might be doable)
* Change the way we do the inserts to not use fully qualified names (which might not even work via a linked server - I don't know if you can skip the database name when doing inserts)

If this is something you wanna do, I'll leave it to you to tackle the code on it.

**Comment by BrentOzar** [comment]
@digitalohm did you want to tackle this, or do you want me to close it? I'm okay either way - I wouldn't tackle it myself because it'd be such a giant pain in the rear, and I odn't use Azure SQL DB for stuff like this.

**Comment by digitalohm** [comment]
no lol, after analyzing this for awhile I agree it would be quite a pain staking task to get done in any reasonable amount of time :(

**Comment by BrentOzar** [comment]
Yeah, figured - it's pretty ugly. Closing.
