### ISSUE TITLE
sp_Blitz: add new check for Enterprise Edition features by checking for the existence of Availability Groups

### ISSUE THREAD

**Issue by visionthroughdesign** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2148]
**Is your feature request related to a problem? Please describe.**
Currently the enterprise check runs against sys.dm_db_persisted_sku_features for any features being used against database level but there multiple AAG related features that are being missed (if AAG is being used) 

**Describe the solution you'd like**
https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups?view=sql-server-ver15 - Expand on the limitations posed by Standard vs Enterprise

**Are you ready to build the code for the feature?**
I'll work on this

**Comment by BrentOzar** [comment]
Interesting! OK, a few quick notes:

* Make sure the code runs on all supported versions of SQL Server (2012 & forward)
* Add new checks rather than edit the existing one (because each different query you run to do a feature check should be its own standalone check - it'll make for easier debugging)
* Make sure the code works on case-sensitive servers (don't use different casing for variables from one query to the next, for example)

Looking forward to seeing it! Thanks!

**Comment by BrentOzar** [comment]
It's been a month, so I'm going to go ahead and close this. Nothing personal, just keeping the issues list clean.

If you change your mind and want to work on it, feel free to reopen the issue and leave a note. Thanks.
