### ISSUE TITLE
Add new check: add NOEXPAND hint for indexed view for non enterprise instance

### ISSUE THREAD

**Issue by ktaranov** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2154]
**Is your feature request related to a problem? Please describe.**
Add check: `NOEXPAND hint is missing for indexed view on non Enterprise instance`
More details here: https://bornsql.ca/blog/using-indexed-views-dont-forget-this-important-tip/

**Are you ready to build the code for the feature?**
If it is relevant for `sp_Blitz` I can make it.

**Comment by BrentOzar** [comment]
To find it, you'd have to examine things like:

* Definitions for views, stored procs, and functions - which may not even be used
* Or examine the plan cache - and you'd only want to examine the top X most resource-intensive queries

I don't think sp_Blitz makes sense, but I could see this being a new warning in sp_BlitzCache. It's going to be tough, though, because you could be querying nested views. For example:

* I could have an indexed view named vwIndexed
* I could have another view called vwOuter that just says SELECT * FROM vwIndexed
* My query could be SELECT * FROM vwOuter
* To detect that it's a problem, you'd have to identify that my query isn't using the indexed view (which would be really tricky, since it's not named in the query, and may not even be in the plan)

And it'd be pretty hard to figure out that there's an indexed view named vwIndexed that needs to be fully qualified.

You could try coding it as a warning in sp_BlitzCache, but just giving you the heads up that it might be really challenging.

**Comment by BrentOzar** [comment]
It's been a month, so I'm going to go ahead and close this. Nothing personal, just keeping the issues list clean.

If you change your mind and want to work on it, feel free to reopen the issue and leave a note. Thanks.
