### ISSUE TITLE
Running sp_BlitzCache with SortOrder = All returns the top 10 plans for Memory Grants instead of Top 5

### ISSUE THREAD

**Issue by planetmatt** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2170]
**Version of the script**
7.8
**What is the current behavior?**
When running sp_BlitzCache with SortOrder = All, sp_BlitzCache should return the top 5 plans for each measure (CPU,Read,Write,Duration, Executions, Memory Grants).

Currently, Memory Grants returns the top 10 plans and not the top 5. 

**If the current behavior is a bug, please provide the steps to reproduce.**
	EXEC sp_BlitzCache
	@ExpertMode = 0, @HideSummary = 1,
        @SortOrder = 'all',
        @SkipAnalysis = 1,
         @MinutesBack = 15

I get 35 rows returned.  5 each for CPU, Reads, Writes, Duration, and Executions, and 10 for Memory Grants. 

**What is the expected behavior?**

30 rows returns, top 5 plans for CPU, Reads, Writes, Duration, Executions, and Memory Grants.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU3) (KB4458871) - 13.0.5216.0 (X64)   Sep 13 2018 22:16:01   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by BrentOzar** [comment]
Yeah, this is confusing - lemme dig into this, figure out what it's supposed to be doing, tweak it, and document it.

**Comment by BrentOzar** [comment]
So many interesting bugs at play here. I started a separate issue to track a few that I found while researching this one - those won't get fixed in this month's release:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2172

But with this particular bug, the memory grant sort appears to be producing 2x the number of rows as the @Top parameter. Digging deeper...

**Comment by BrentOzar** [comment]
Woohoo! Fixed. The plans that were from @SortOrder = 'spills' were being incorrectly labeled as 'memory grant'. 

Now, this does lead to another bug: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2174

But I'm going to leave that as a separate issue since I won't get that one out for the October release - it'll be just a little more ambitious.

**Comment by BrentOzar** [comment]
Also, while I was in here, updated the documentation for SortOrder = all in the readme.
