### ISSUE TITLE
sp_blitz: backup location minor issue (specific scenario)

### ISSUE THREAD

**Issue by gory31270** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2178]
**Version of the script**
SELECT @Version = '7.9', @VersionDate = '20191024'

**What is the current behavior?**
Minor issue: sp_Blitz detects backups on the same drive as the data, based on the drive letter.
In our failover cluster, we have mount-points. 
So technically different drives using the same letter. The alert is a false positive in our case.

![image](https://user-images.githubusercontent.com/57088188/67664196-73b99280-f967-11e9-8cbb-6b91101d511d.png)

**Comment by BrentOzar** [comment]
Hi! Yep, that issue has been reported a few times - just make sure to search past issues before you submit a new one. For example:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/896

If you'd like to code it, check the Contributing Guide on how to get started. (This wouldn't be something I'd tackle personally since I don't use mount points - nothing against 'em, I just don't have a use for 'em in my own daily work.)

**Comment by gory31270** [comment]
Oops, sorry i'm new to github.
Thanks for the great work on the tools :)

**Comment by BrentOzar** [comment]
My pleasure! I'll go ahead and close this, but if you change your mind and wanna work on the code, leave a note and I can reopen it.
