### ISSUE TITLE
sp_BlitzIndex - add OutputDatabaseName, SchemaName, TableName

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#221]
Write the output to table like we do with sp_Blitz and sp_BlitzFirst. Can rip the code straight out of there.

**Comment by BrentOzar** [comment]
Added parameters in v4, not functional yet.

**Comment by tjbillybob** [comment]
Any update on this one Brent, really keen to start getting this one outputting to a master database as we have SP_Blitz doing. Really good tool which we are keen to start using more.

**Comment by BrentOzar** [comment]
Hi! No, sorry no update on this. If you'd like to contribute code, you can check out the contributing guidelines here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

The code has already been adding to sp_Blitz, so it might be a great place for you to jump in and start contributing. We'd love the help - and it might be a great way for you to give back to the community that has given so much to you. ;-)

**Comment by PerfektNerd** [comment]
I'm actually working on this one, Brent; I'm doing this next along with the @OutputServerName enhancement at the same time.

As soon as I finish, and once we get #419 tested and pushed, I'll create a pull request for it.

Just as a heads up: some complications around this one are making it take a bit longer to code. Each mode has it's own table structure; so they won't stack. The way I'm solving this is that each mode will have it's own DDL and insert statements. I don't see a way to use a single table to be able to hold the output of all 3 modes, at least not cleanly. 

This requires some additional error checking too, since if you have selected an @OutputTableName that already exists, the SP should make sure it's the correct table structure for the mode you selected. This part is (relatively) easy, though.

If anyone has a better idea, or scathing critiques, please let me know ;D

**Comment by rwhoward** [comment]
Since this has been idle for quite a while I'm going to take a shot at it. First pass will probably end up just for mode 2 unless I get ambitious.

**Comment by saketmittaldba** [comment]
I have modified code for Mode=4 to get output in table. Attaching code
[sp_BlitzIndex-Saket.zip](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1852224/sp_BlitzIndex-Saket.zip)

**Comment by BlitzErik** [comment]
Hi @saketmittaldba -- this isn't really how we take code contributions.

Please read the [contributing guide](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md) if you'd like to add code.

**Comment by dianetrcka** [comment]
I just tried this in version 6.9.  Have any idea when it will be functional?

**Comment by BrentOzar** [comment]
@dianetrcka - hi! No, sorry no update on this. If you'd like to contribute code, you can check out the contributing guidelines here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

The code has already been adding to sp_Blitz, so it might be a great place for you to jump in and start contributing. We'd love the help - and it might be a great way for you to give back to the community that has given so much to you. ;-)
