### ISSUE TITLE
sp_BlitzFirst: add option to start & analyze an XE trace

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2267]
**Is your feature request related to a problem? Please describe.**
There are times when I'm facing issues that don't show up in the plan cache, like:

* Unparameterized queries coming through in bursts
* Repeated recompiles of the same query (like stats changes or temp tables)
* Blocking

**Describe the solution you'd like**
I'd like to add an sp_BlitzFirst parameter that starts an XE trace for some of these issues, and then stops it, and analyzes the contents afterwards looking for causes of the above issues.

**Describe alternatives you've considered**
A separate proc like sp_BlitzTrace, and that might still be involved - it might be that we call sp_BlitzTrace (or something like it) the same way we call sp_BlitzWho from sp_BlitzFirst.

**Are you ready to build the code for the feature?**
Yes - it won't be soon, but I'm going to gradually work on the specs first in here and work on it over the course of the coming months.

**Comment by erikdarlingdata** [comment]
I wouldn't write a piece of code this big into BlitzFirst. It's already pretty big, and targeted well. I'd be really into helping build a proc that'd make XE accessible to human beings, though (root cause: `xQuery` fetish).

Other stuff that'd make it really cool: 
 * Watch a specific SPID/proc/login's queries/plans
 * Grab query plans for anything over a certain duration
 * Spikes in wait stats (the random problem scenario)
 
BlitzTrace would be a good start to look at expanding, though.

**Comment by BrentOzar** [comment]
Yeah, the more I think about it, the less sense this makes in sp_BlitzFirst, and the less inclined I am to code it. I do still run into this issue now and then, but I'm going to cry mercy on this one and stick a fork in it.
