### ISSUE TITLE
sp_BlitzLock using @OutputDatabaseName gives "Invalid column name 'database_name'."

### ISSUE THREAD

**Issue by biohazardxxx** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2276]
**Version of the script**
@Version = '2.92', @VersionDate = '20200123';

**What is the current behavior?**
command exec dbo.sp_BlitzLock @OutputDatabaseName = 'admin'
Gives output:
found synonym
Grab the initial set of XML to parse at Feb  4 2020  1:42:55:210PM
Parse process and input buffer XML Feb  4 2020  1:43:03:787PM
Parse execution stack XML Feb  4 2020  1:43:03:907PM
Grab the full resource list Feb  4 2020  1:43:03:917PM
Parse object locks Feb  4 2020  1:43:03:937PM
Parse page locks Feb  4 2020  1:43:03:973PM
Parse key locks Feb  4 2020  1:43:04:003PM
Parse RID locks Feb  4 2020  1:43:04:033PM
Parse row group locks Feb  4 2020  1:43:04:070PM
Parse parallel deadlocks Feb  4 2020  1:43:04:117PM
Get rid of parallel noise Feb  4 2020  1:43:04:170PM
Get rid of nonsense Feb  4 2020  1:43:04:170PM
Update some nonsense part 1 Feb  4 2020  1:43:04:177PM
Update some nonsense part 2 Feb  4 2020  1:43:04:180PM
Get Agent Job and Step names Feb  4 2020  1:43:04:187PM
Check 1 Feb  4 2020  1:43:04:207PM
Check 2 objects Feb  4 2020  1:43:04:210PM
Check 2 indexes Feb  4 2020  1:43:04:217PM
Check 3 Feb  4 2020  1:43:04:220PM
Check 4 Feb  4 2020  1:43:04:227PM
Check 5 Feb  4 2020  1:43:04:230PM
Check 6 Feb  4 2020  1:43:04:237PM
Check 7 part 1 Feb  4 2020  1:43:04:257PM
Check 8 Feb  4 2020  1:43:04:277PM
Check 9 Feb  4 2020  1:43:04:287PM
Check 10 Feb  4 2020  1:43:04:290PM
Check 11 Feb  4 2020  1:43:04:300PM
Check 12 Feb  4 2020  1:43:04:303PM
Results 1 Feb  4 2020  1:43:04:310PM
Msg 207, Level 16, State 1, Procedure sp_BlitzLock, Line 1150
Invalid column name 'database_name'.

**If the current behavior is a bug, please provide the steps to reproduce.**
exec dbo.sp_BlitzLock @OutputDatabaseName = 'admin'

**Server infos:**
collation is Latin1_General_BIN2
**What is the expected behavior?**
No error.
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
version:12.0.4100.1 it is a new functionality

**Comment by BrentOzar** [comment]
Hi. To use the Output parameters, you need to pass in all 3: OutputDatabaseName, OutputSchemaName, and OutputTableName. You can read the documentation for more details here by scrolling down: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/tree/master

**Comment by biohazardxxx** [comment]
If I replace "database_name" with "db_name" it works fine (with this one param as the others have a default value).

**Comment by biohazardxxx** [comment]
Can this be reopened please?
As wrote OutputSchemaName, and OutputTableName have default values.

**Comment by BrentOzar** [comment]
I'm going to be honest: this isn't something I'm going to work on, because I gave you instructions on how to get it to work. If you'd like to adapt the code to get it to work the way you want, you're welcome to give it a shot. Open the Contributing Guide in the root of the repo.

Open source isn't free outsourced development. If you want to do something a different way, you'll need to pick up the pieces and give 'er a shot.

Let me know if you have questions.

**Comment by TurnerBurn** [comment]
Just in case others are searching on this issue, I ran into this problem as well but it just has to do with the database collation being set to one that is case sensitive (i.e. Latin1_General_BIN). 

The code in sp_BlitzLock builds the target table with a column name of "Database_Name" (caps on 'D' and 'N') and then later in the code, when it tries to insert data, it dies because it is looking for a column named "database_name" (No caps). The simple workaround is to edit the target table and change the name to all lowercase and it will work fine.
