### ISSUE TITLE
sp_BlitzQueryStore only runs against the database it is installed in on Azure SQL MI

### ISSUE THREAD

**Issue by chargerback-ron** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2281]
**Version of the script**
3.92

**What is the current behavior?**
I have installed this script in a Utility database on Azure SQL Managed Instance. When I run it, it ignores `@DatabaseName` and instead always runs against the Query Store for the Utility database, even when that is not the current database in SSMS.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a database in Azure SQL MI named Utility. Install sp_BlitzQueryStore in that database. Now create another database in the same instance named Production. From SSMS click New Query, change the current database to Production, enter the following code and click Execute. 

`
DECLARE	@return_value int,
		@Version varchar(30),
		@VersionDate datetime

EXEC	@return_value = [Utility].[dbo].[sp_BlitzQueryStore]
		@DatabaseName = N'Production',
		@Version = @Version OUTPUT,
		@VersionDate = @VersionDate OUTPUT

SELECT	@Version as N'@Version',
		@VersionDate as N'@VersionDate'

SELECT	'Return Value' = @return_value

GO
`

**What is the expected behavior?**
I expect it to run against the Query Store of the Production database. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Azure SQL Managed Instance. Unknown whether previous versions of the script worked or not.

**Comment by BrentOzar** [comment]
Hi Ralph. Thanks for the bug report, but in the readme, we flat out say that we don't support Azure. Things in there change pretty fast and furious without warning.

If you'd like to make the code changes yourself so that it'll work, you're welcome to, though. Read the contributing guide here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you decide you want to tackle the work, follow those instructions and leave a note here, and I can reopen this.
