### ISSUE TITLE
sp_DatabaseRestore: add logging functionality (because we no longer call Ola's scripts)

### ISSUE THREAD

**Issue by RobAshton-IM** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2306]
**Version of the script**
7.92, 20200123

**What is the current behavior?**
Removal of usages of Ola Hallengren's CommandExecute and DatabaseIntegrityCheck stored procedures has lost functionality for the sp_DatabaseRestore stored procedure.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Make a call onto the sp_DatabaseRestore stored procedure
2. Check the CommandLog table for the record for that call - no record is found

**What is the expected behavior?**
The corresponding record for the call should be found in the CommandLog table

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All supported versions of SQL Server and OS.
This worked in the previous version of the sp_DatabaseRestore stored procedure.

**Comment by BrentOzar** [comment]
Hi! Yeah, we removed the calls to Ola's scripts because he added a parameter that broke everything that called it.

We don't want to add that dependency back in because it'll cause issues the next time he makes a change to his procedures. We're all volunteers here, and we can't stop-and-drop-everything when someone else makes a change to their code.

I understand that logging may be an important feature for you, and if you'd like to add that code in, there are a couple of ways you could do it. You could log to Ola's tables, but the problem obviously comes in that if he changes the table structure (the way he's changed the proc parameters), then our code would break again, and obviously that wouldn't be desirable.

Or, you could add logging code in with the @OutputDatabaseName, @OutputSchemaName, and @OutputTableName parameters the way we do in the rest of the procs. That way, you could design a logging table that works well for your needs, define what gets logged, and make sure that changes in other procs won't break this one.

If you want to tackle that, here's the contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

If you don't want to tackle that, I totally understand - everybody's busy these days. It's just that open source != free development, so if there's a feature that's important to you, you may need to roll up your sleeves and code it, or else sponsor someone in the community to build it for you. (We cover that over in the contributing guide too.)

If I don't hear back from you within a few days about how you want to move forward, I'll close the issue.

**Comment by RobAshton-IM** [comment]
I'm right about to pull the latest dev branch state for the FRK into my own fork, yep :)

I totally get not wanting to be broken by changes from other frameworks that have been built into this one, but Ola's maintenance routines haven't been completely removed from the FRK yet; sp_AllNightLog still talks to Ola's DatabaseBackup for example. Are we as a community planning on replacing all the work that stored proc does with an equivalent one in the FRK that then needs to be maintained as well?

Shouldn't we instead be accepting a fork of Ola's code from prior to the breaking change that _did_ work for the FRK and making _that_ something deployed by the FRK? That way, the FRK has a known and stable version of the other framework to be based upon, and we can accept a breaking change like this DatabaseContext parameter in a more comprehensive way as part of a true merge/fix release?

**Comment by BrentOzar** [comment]
I'm going to be brutally honest here just to minimize the back-and-forth and honor your time: our priorities are making sure that our code works with as little intervention as possible. I have a day job (just like you do), and when we get an urgent request saying someone else's code broke ours, that's a problem.

sp_DatabaseRestore is something that just needs to work, full stop. We don't do a lot of active development on it, and the community hasn't been helping - as evidenced by the repeated requests for folks to test the open pull requests for it, and nobody's doing that.

Because of that, I'm not open to taking dependencies on things that are changing w/o warning and breaking it. 

If you need logging, you basically have two choices:

- Fork the prior version of sp_DatabaseRestore from before the change, and edit it yourself to support Ola's changes (which is totally fine, since the project is MIT-licensed)
- Design a logging mechanism in sp_DatabaseRestore that works standalone, without dependencies on Ola's scripts or tables, and submit that via a pull request here (but I'd recommend talking through the structure you wanna use here just to get other folks to chime in too)

However, updating sp_DatabaseRestore to call Ola's scripts again isn't something I'm open to integrating into this repo. You're absolutely welcome to do it in your own repo, but I can't maintain that. If you want to start, you can start by working on testing the existing pull requests that are already open for sp_DatabaseRestore. (I don't use that proc anymore, so I just don't have the bandwidth to volunteer more time for testing a stored proc I don't use.) I hope that's fair.

**Comment by BrentOzar** [comment]
@RobAshton-IM did you want to move forward with this? If not, I totally understand.

**Comment by RobAshton-IM** [comment]
@BrentOzar Hi Brent. Personally, no.

As you said, I had two choices, either fork and go my own way, or fix the lack of logging in the sp_DatabaseRestore process the way that the FRK project wants to go.

Unfortunately, that decision was made for me at the point where I realised that Ola's change broke the version of the FRK I have deployed on my servers; I had to hotfix my own toolkit in order to handle an immediate issue with a broken log shipping configuration in production. Since I've already invested a lot of effort in a monitoring solution that sits on top of Ola's CommandLog table, I came looking to see if anyone else had run into the same issue as me and it was fixed by the most recent dev build, and here we are.

I think I have to spend a lot of time refactoring my toolkit's dependencies around logging and monitoring before I can come back to this issue myself, but this issue is definitely worthy of someone's attention so that the FRK's various elements have a consistent approach to logging.

**Comment by BrentOzar** [comment]
OK, cool. Understood - I'll go ahead and close this. If someone wants to put the work into that, I'm totally all for it - it's just that open source doesn't mean free development. If you value something, you gotta put the work into it (or else buy something off the shelf that does what you want.)
