### ISSUE TITLE
Install-All-Scripts does not install all scripts

### ISSUE THREAD

**Issue by kevonh** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2322]
**Version of the script**
3.93

**What is the current behavior?**
The module 'sp_AllNightLog' depends on the missing object 'master.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists.
The module 'sp_AllNightLog' depends on the missing object 'master.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists.
The module 'sp_BlitzFirst' depends on the missing object 'sp_BlitzWho'. The module will still be created; however, it cannot run successfully until the object exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. execute Install-All_scripts 
2. witness errors above

**What is the expected behavior?**
Install-All-Scripts should also install sp_databaserestore and sp_blitzwho

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server 2019, Windows Server 2019.  I don't know if it worked in the past, this is my first time trying.

**Comment by BrentOzar** [comment]
It does restore the other scripts. You can test it by deleting all of the procs, and then running the install-all-scripts proc and look at your list of procs afterwards.

The errors are simply because the objects are created in alphabetical order, and the scripts don't all exist yet. 

If you'd like to resort the order that the scripts are created, here's the PowerShell script I use to build the installer script:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/Development/Merge%20Blitz.ps1

And here's the contributing guide that explains how to contribute fixes:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/CONTRIBUTING.md

If you want to make that code change, you can open an issue volunteering for that, and you can go from there. Thanks!
