### ISSUE TITLE
sp_BlitzIndex - SQL version detection breaks on 2014/2016

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#235]
IF (SELECT LEFT(@SQLServerProductVersion,
             CHARINDEX('.',@SQLServerProductVersion,0)-1
             )) <> 11 --Anything other than 2012
       BEGIN

**Comment by BlitzErik** [comment]
In one database, I have a number table partitioned with 15,000 rows, one row per partition.

![01 2016-06-17_12-03-18](https://cloud.githubusercontent.com/assets/11590415/16156769/c01db3ce-3483-11e6-92e2-bcb5d9ff7a01.jpg)

When we get to this part, we have a choice of running two nearly identity queries. The only difference is LEFT JOIN vs OUTER APPLY.

`
/*QUERY ONE*/
SELECT
    columns...
FROM
    [sys].[dm_db_partition_stats] AS [ps]
    JOIN [sys].[partitions] AS [par]
    ON [ps].[partition_id] = [par].[partition_id]
    JOIN [sys].[objects] AS [so]
    ON [ps].[object_id] = [so].[object_id]
       AND [so].[is_ms_shipped] = 0 /*Exclude objects shipped by Microsoft*/
       AND [so].[type] <> 'TF' /*Exclude table valued functions*/
    LEFT JOIN [sys].[dm_db_index_operational_stats](DB_ID(), NULL, NULL, NULL)
    AS [os]
    ON [ps].[object_id] = [os].[object_id]
       AND [ps].[index_id] = [os].[index_id]
       AND [ps].[partition_number] = [os].[partition_number]
WHERE
    1 = 1
ORDER BY
    [ps].[object_id] ,
    [ps].[index_id] ,
    [ps].[partition_number]
OPTION
    ( RECOMPILE );

/*QUERY TWO*/
SELECT
   columns...
FROM
    [sys].[dm_db_partition_stats] AS [ps]
    JOIN [sys].[partitions] AS [par]
    ON [ps].[partition_id] = [par].[partition_id]
    JOIN [sys].[objects] AS [so]
    ON [ps].[object_id] = [so].[object_id]
       AND [so].[is_ms_shipped] = 0 /*Exclude objects shipped by Microsoft*/
       AND [so].[type] <> 'TF' /*Exclude table valued functions*/
    OUTER APPLY [sys].[dm_db_index_operational_stats](DB_ID(),
                                                      [ps].[object_id],
                                                      [ps].[index_id],
                                                      [ps].[partition_number])
    AS [os]
WHERE
    1 = 1
ORDER BY
    [ps].[object_id] ,
    [ps].[index_id] ,
    [ps].[partition_number]
OPTION
    ( RECOMPILE );`

The first query runs in under one second. The second query takes nearly six minutes. The problem, as far as I can tell from the execution plan, is that the OUTER APPLY optimizes to a nested loops join. For this many rows, that sucks. The first query uses a hash join. One and done. The query plans are identical otherwise. In plan explorer, the costs are 25/75, respectively.

Here's plan one:

![02 2016-06-17_12-10-38](https://cloud.githubusercontent.com/assets/11590415/16156979/9bf6034c-3484-11e6-9972-b3323b9adc65.jpg)

Here's plan two:

![03 2016-06-17_12-11-02](https://cloud.githubusercontent.com/assets/11590415/16156985/a35867e2-3484-11e6-8e88-c704c7f09220.jpg)

I think the best option here is to skip the version check entirely and default to the LEFT JOIN query. 

I'll wait for feedback before making the change and closing.

**Comment by BrentOzar** [comment]
Wow, I like the sounds of that. Agreed on defaulting to the LEFT JOIN.

**Comment by BlitzErik** [comment]
Closing with fix to only use the OUTER APPLY if the version number is > 2147483647. I want to leave this in in case we find a regression.
