### ISSUE TITLE
sp_BlitzQueryStore: slow speed on Azure Managed Instances

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2351]
In Slack, Kamil Nowinski found that when he fully qualified the proc name he was looking for (by adding the schema), his execution time dropped from 5 minutes to <100ms. Update the documentation including https://www.brentozar.com/first-aid/sp_blitzquerystore/ .

**Comment by NowinskiK** [comment]
It's me again. Sorry, my bad. Even though the SP takes <100ms to execute - there were no results. So I was happy too early. 
**Please, do not change documentation. The SP is not supporting fully qualified the proc name (although I haven't check that in on-prem version).**
My mistake comes from the fact that I was testing it with SentryOne, which is a great tool, but I haven't seen the output.
Unfortunately, when you run SP with filtering by SP with schema name - you got only one row: 
`We couldn't find the Stored Procedure [test.usp_etl_11] in the Query Store views for [{database}] between {date} and {date}. Try removing schema prefixes or adjusting dates. If it was executed from a different database context, try searching there instead. `
I spent some time today to investigate the issue and I found that the main problem is causing by the following condition in several queries:
`AND qsp.query_plan IS NOT NULL`
Once I removed that - a query executes very fast rather than 13 seconds each.
I tried to redesign the query, but with no success.
I will investigate it further.

**Comment by BrentOzar** [comment]
Ah, thanks for the followup!

**Comment by erikdarlingdata** [comment]
@NowinskiK -- yeah, I've run into the [same thing](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2068) before. It's a weird moving target, and it doesn't always work. There are lots of parts of the WHERE clause that can end up being just as slow. It's not specific to the query plan check.

If you wanna take it out and deal with potentially `NULL` plans in other ways, go for it. Just be aware that you can still hit weirdbad performance issues.

**Comment by NowinskiK** [comment]
Great! But... not really great. Anyway, good to know, thanks @erikdarlingdata. So, I'm not gonna spend time on the issue if you already did. Out of curiosity: is it something where Microsoft can help?

**Comment by erikdarlingdata** [comment]
If you have someone at Microsoft to work with, maybe. I'm not a paying customer so they don't care about me.

**Comment by BrentOzar** [comment]
I'm going to go ahead and close this, but if Kamil, if you want to revisit it (maybe with Microsoft's help), you're totally welcome to. I just don't technically support these on Azure SQL* because I don't run 'em myself.
