### ISSUE TITLE
sp_BlitzFirst: new update-stats check can produce >4000 characters, breaking insert to table

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2409]
**Version of the script**
Dev branch

**What is the current behavior?**
If you had >4K of updated stats, you'll get a string-truncation error when the Agent job runs because the Details column is only 4K long.

**What is the expected behavior?**
Trim the updated-stats message to just 4K long, since we're sorting by table rows anyway.

**Comment by BrentOzar** [comment]
Thanks @camaro322hp! It's merged into the dev branch, and I'll do an urgent release for it today or tomorrow just to get that out into the wild, and put you in the release notes for next month's release.

Now I gotta know: do you have pics of the 322hp Camaro? I'm jealous. :-)

**Comment by camaro322hp** [comment]
No problem.  Happy to help.  

I feel like this is getting off topic, but since you asked: (this is back when it was a lot newer and cleaner - now it's just a 20 year old beater, but still fun)
![Z28](https://user-images.githubusercontent.com/66386436/83687646-ebf0d200-a5a0-11ea-952a-f64555c9e0b1.png)

**Comment by BrentOzar** [comment]
Woohoo! Nice. That's peak 1990s there too - another 5-10 years, and it's going to look SO different from everything else on the road. Bonus points for the T-tops.
