### ISSUE TITLE
sp_BlitzFirst is reporting Queries with "10000x cardinality misestimations" for the sp_BlitzFist query to find cardinality misestimations

### ISSUE THREAD

**Issue by gdoddsy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2420]
Not sure if this should be a suggestion or a bug. I won't mind if you just want to close it either.

**Version of the script**
Version: 7.95, Date: 20200506

**What is the current behavior?**
When you run sp_BlitzFirst, one of my top warnings is that I have "Queries with 10000x cardinality misestimations", but the query is the query that finds misestimation-ed queries.

**If the current behavior is a bug, please provide the steps to reproduce.**
First time that I've seen it, all I did was run sp_blitzfirst. Not sure why it came up this time.

**What is the expected behavior?**
Either that the query doesn't misestimate, or the query doesn't report itself as being a problem.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Happening in SQL 2019, I haven't noticed it before.

**Comment by BrentOzar** [comment]
Ouch! I popped open the code and I see what's happening. This is only happening when sp_BlitzFirst is running simultaneously from different sessions. When we populate the @bad_estimate table variable that's used to find these issues, we already have this filter:

`WHERE deqp.session_id <> @@SPID`

So that means you're seeing the sp_BlitzFirst running from another session, like the one you so cleverly set up to run automatically every 15 minutes. I know because I've seen this same thing happen when I've been teaching the Mastering classes.

I would love to exclude that query, but to do it, we (and by we I mean you) would have to examine the contents of the query itself, and at the point where we fill the @bad_estimate table, we haven't joined to the text of the currently running query. If we (and by we I mean you) wanted to do this, we (you get the point) would need to:

* Add a join to something to get the text of the currently running query
* Examine it to see if it's the sp_BlitzFirst query (and to do that you may wanna add an obvious comment to the dynamic SQL that's getting built, like /* From sp_BlitzFirst */, and then look for that)

If you're interested in doing that, holler, but otherwise I'm going to close this because it's more work than I wanna do, because I'm wearing a bathrobe. ;-)

**Comment by gdoddsy** [comment]
![image](https://user-images.githubusercontent.com/25063374/84729985-5b6eb480-afd8-11ea-87ea-8478a04dbf6b.png)

It's not happening at the moment, but I feel like it was picking up the session that I was in. Let me see if I can get it to happen again.

**Comment by gdoddsy** [comment]
Was able to reproduce on Stack Overflow database on the VM I used for the Mastering classes. It's all about memory starvation:

1. Set memory to a low-ish number (e.g. 10GB)
1. run `exec sp_BlitzFirst @ExpertMode=1, @Seconds=30`
1. in another session, run a query that will consume all memory, e.g.:
```
SELECT		*
FROM		Posts
INNER JOIN	PostHistory
		ON	PostHistory.PostId = Posts.Id

INNER JOIN	Comments
		ON	Comments.PostId = PostHistory.PostId
```
In my test I was running sp_BlitzFirst on SPID 55, and I get this result in that same window:
![image](https://user-images.githubusercontent.com/25063374/84836239-afc97100-b078-11ea-9a59-3bd3687eccc6.png)

![image](https://user-images.githubusercontent.com/25063374/84836213-a3ddaf00-b078-11ea-9084-2fa856d8e060.png)


If you've got any suggestions on where to look, I'm happy to dig into it a little bit, but if it's still going to be digging in to text of currently running queries then go ahead and close it.

**Comment by BrentOzar** [comment]
GET OUTTA HERE! That's awesome. That's enough info that I should be able to dig into it. Thanks, sir!

**Comment by urizen-source** [comment]
I saw the stream on YouTube where this was discussed and I was bored enough to go look at it to see if I could fix it, but I think the issue is broad than just it incorrectly targetting sp_blitzFirst, it seems to target alot more unintended "victims".

Extracting part of the @Bad_estimate-populating query and running 100 times against a server with some load, with * instead of specific fields and a WHERE-clause to only include the ones that by the queries logic is considered bad estimates:
` 

                           SELECT  CASE WHEN deqp.row_count > ( deqp.estimate_row_count * 10000 )
                                     THEN 1
                                     WHEN deqp.row_count < ( deqp.estimate_row_count * 10000 )
                                     THEN 1
                                     ELSE 0
                                END AS estimate_inaccuracy,*
                         FROM   sys.dm_exec_query_profiles AS deqp
				WHERE deqp.session_id <> @@SPID 	 AND CASE WHEN deqp.row_count > ( 
                            deqp.estimate_row_count * 10000 )
                                     THEN 1
                                     WHEN deqp.row_count < ( deqp.estimate_row_count * 10000 )
                                     THEN 1
                                     ELSE 0 END = 1
                            GO 100
`

Reveals alot that probably should not be considered inaccurate estimate.
![image](https://user-images.githubusercontent.com/65188814/84942798-af19f480-b0e3-11ea-9d58-cc4c6095d287.png)

7 < (5 * 10000) which means it is considered inaccurate, while 7 vs 5 seems quite okay to me.

Apart from the above logical issue, dm_exec_query_profiles is populated on the fly, meaning that as soon as an estimate is done (estimating say 2 million rows) but before it has had time to retrieve a significant amount of rows, it will be considered inaccurate and alert.

The check if row_count*10000 > estimate_row_count seems sound still as that will always be a red flag, but the other way around will for the first few milliseconds of queries with decently high estimates always warn(if the logic in the CASE WHEN was corrected) and I think that should be removed, which in some testing on my end seems to fix the issue with the incorrect flagging of sp_blitzfirst as well.

I submitted a pull request with this suggestion, take it or leave it, but the above info should explain why :) 
#2437

**Comment by gdoddsy** [comment]
Just a stab in the dark here, but could you combine both of the lines into something like `abs(deqp.row_count -  deqp.estimate_row_count) > 10000` to cover both cases? So the 7 vs 5 case wouldn't come up, if you over or under estimate by more than 10,000 then it would?

**Comment by urizen-source** [comment]
That would return misestimates more than 10000, yep, but not 10000x. So we would get back 100010001 vs 100000000 which is a pretty good estimate, what it should be looking for is 130 vs 1400000 type of misestimates.

I do not see how this could be done from a live DMV as it will be incorrect in the beginning of the execution(except a row_count > estimated*10000 as mentioned, which will always be incorrect).
I looked around some and execution plan DMVs and query store DMVs do not appear to contain actual row count so we cannot get it from there either.

I can't find any other anyway, pointed in the right direction I'm sure I could implement some other way of doing it but right now I'm out of ideas :)

**Comment by BrentOzar** [comment]
@urizen-source this observation:

> I do not see how this could be done from a live DMV as it will be incorrect in the beginning of the execution(except a row_count > estimated*10000 as mentioned, which will consistently indicate a problem).

Is utterly brilliant and correct for UNDER-estimations, but we can still do it for OVER-estimations. I'm going to fork that off into a separate issue: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2438

**Comment by BrentOzar** [comment]
@gdoddsy - can you try the current dev branch and see if you can repro the issue now? Thanks!

**Comment by gdoddsy** [comment]
Can't recreate it anymore. Thanks @urizen-source & @BrentOzar
