### ISSUE TITLE
sp_BlitzIndex write-to-table errors due to new column is_in_memory_oltp

### ISSUE THREAD

**Issue by rebambus** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2511]
**Version of the script**
Problem occurred after upgrading to 7.97 (2020-07-12) from 7.93 (2020-02-17).

**What is the current behavior?**
When calling this:
```
EXEC dbo.sp_BlitzIndex @Mode = 2,
                       @OutputDatabaseName = 'DBAtools',
                       @OutputSchemaName = 'dbo',
                       @OutputTableName = 'BlitzIndex';
```

It errors with the following:
```
...
Update #PartitionCompressionInfo.
Update #IndexSanity for filtered indexes with columns not in the index definition.
@Mode=2, here's the details on existing indexes.
Failure analyzing temp tables.
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 5220 [Batch Start Line 0]
Invalid column name 'is_in_memory_oltp'.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Make the above call on an old version of sp_BlitzIndex.
Upgrade sp_Blitzindex to 7.97
Make the same call again.

**What is the expected behavior?**
The output table I'm writing to should maybe be modified to add the new column? Maybe dropped and recreated? Failing more gracefully would also be good.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I think the problem is introduced in commit fd38659.

**Comment by BrentOzar** [comment]
I apologize for that. Yes, you'll want to add a new column to your output table.

If you want the code to gracefully do that for you, you can submit a pull request with your code. Here's the contributing guide: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md 

I don't personally have the time to code that right now (I really would like to, I just have other priorities right now), but your code would totally be welcome. If you want to tackle that, just leave a note here and I'll reopen the issue and assign it to you. Otherwise I'll go ahead and close it, assuming that you just added the column.

Thanks again, and sorry for the inconvenience.
