### ISSUE TITLE
Add a new check for sys.databases's is_query_store_on vs. sys.database_query_store_options desired/actual state

### ISSUE THREAD

**Issue by WaldenL** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2525]
**Is your feature request related to a problem? Please describe.**
sys.databases maintains a "cached" bit indicating whether query store is enabled for a given database, however this value can be out of sync with reality. Database mirroring failover seems to disable query store in the database but does not update the bit in sys.databases, perhaps other stuff does too. A naïve scan of sys.databases where is_query_store_on = 1 therefore returns incorrect information. 

**Describe the solution you'd like**
Add a check in sp_Blitz for the bit in sys.databases not being in sync with the actual state in database_query_store_options.

**Describe alternatives you've considered**
No real alternatives to the check, other than obviously not checking. :-) 

**Are you ready to build the code for the feature?**
Happy to build the fix and provide a PR. Per instructions in the check docs I'm opening the Issue first to discuss general interest in adding the check and what the right check values would be. 

The check # would simply be the next number available. For priority, I'm thinking either 200 or a new 205? 200 is the priority for the current check if query store is enabled at all (check 163). For Findings Group it's probably Performance (like 163), but perhaps Informational?

**Comment by BrentOzar** [comment]
Sure, sounds good. A few quick notes:

* Use sp_MSforeachdb if you need to run per-database checks - we do have sp_ineachdb in this repo, but we can't guarantee that it's installed for all servers.
* Performance probably makes sense for the group.
* Priority - let's not create new ones. (If I could go back in time, I'd have just made these priorities 1-10, heh.) I'd put it up in 150 because it does indicate a problem that the user might want to address.

Thanks!

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merged into the dev branch, and will be in the September release with credit to you in the release notes.
