### ISSUE TITLE
expand Github issue #598 to include the 19 new database scoped configurations that can be changed in SQL 2019

### ISSUE THREAD

**Issue by mtndew01** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2573]
**Is your feature request related to a problem? Please describe.**
Currently sp_BlitzFirst only looks at the database scoped configurations of MAXDOP, LEGACY_CARDINALITY_ESTIMATION, PARAMETER_SNIFFING, and QUERY_OPTIMIZER_HOTFIXES. 

**Describe the solution you'd like**
SQL 2019 introduces the following options for database scoped configurations
IDENTITY_CACHE
INTERLEAVED_EXECUTION_TVF
BATCH_MODE_MEMORY_GRANT_FEEDBACK
BATCH_MODE_ADAPTIVE_JOINS
TSQL_SCALAR_UDF_INLINING
ELEVATE_ONLINE
ELEVATE_RESUMABLE
OPTIMIZE_FOR_AD_HOC_WORKLOADS
XTP_PROCEDURE_EXECUTION_STATISTICS
XTP_QUERY_EXECUTION_STATISTICS
ROW_MODE_MEMORY_GRANT_FEEDBACK
ISOLATE_SECURITY_POLICY_CARDINALITY
BATCH_MODE_ON_ROWSTORE
DEFERRED_COMPILATION_TV
ACCELERATED_PLAN_FORCING
GLOBAL_TEMPORARY_TABLE_AUTO_DROP
LIGHTWEIGHT_QUERY_PROFILING
VERBOSE_TRUNCATION_WARNINGS
LAST_QUERY_PLAN_STATS

**Are you ready to build the code for the feature?**
Lets do this!

**Comment by BrentOzar** [comment]
Sure, sounds good. Just make sure it can be run repeatedly without errors, works on case-sensitive servers, on 2008+, etc. Looking forward to the PR - thanks!

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, and will be in the October release with credit to you in the release notes.

Small tweak - the new checks also have to be added in the Documentation folder, but I'll knock that out today since it also involves pulling URLs for each of 'em so folks know where to learn more.
