### ISSUE TITLE
Consultant Toolkit fails if older sp_Blitz is installed

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2590]
**Version of the script**
`SELECT @Version = '7.99', @VersionDate = '20200913';`

**What is the current behavior?**
When I call sp_Blitz as a stored proc, it runs fine. When it's called via the collector, or using the script in the collector, it fails.

![image](https://user-images.githubusercontent.com/2136037/93369390-501c6680-f81d-11ea-9f19-92509a76b966.png)

![image](https://user-images.githubusercontent.com/2136037/93370997-a25e8700-f81f-11ea-8849-9280d1acf737.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Running the CTK/script on SQL Server 2017 (3281.6) or 2019 (4063.15) will generate the error. I'm not sure about other versions. 

I've tried some basic troubleshooting -- looking for a column called SIZE, and executing the statements that print around the time the error occurs, but they aren't generating anything. Since I'm on with a client, I can't spend too much time on it right now.

When I skip check 226, the script and CTK succeed. I just don't know where it's happening inside that check.

**What is the expected behavior?**
Errorless

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
2017/2019

**Comment by BrentOzar** [comment]
HO HO HO, I think I've tracked it down.

In this pull request:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/2566/files

The definition of the temp table #driveInfo was changed. It used to have a "Size" column, and now it no longer does.

That wouldn't seem to matter, but here's what's happening:

* The new Consultant Toolkit version runs, kicking off the non-stored-procedure version of sp_Blitz
* It creates the new #driveInfo table WITHOUT a size column
* Check 226 runs, and as part of that, it tries to check the versions of all installed Blitz procs
* It executes sp_Blitz @VersionCheckMode = 1
* That SHOULDN'T hit the #driveInfo part of the code - it's supposed to simply return, and it's the very top thing in the stored procedure
* But because SQL Server immediately validates the temp tables that exist throughout the entire proc - even the parts you're not calling - sp_Blitz fails.

Neato! Possible solutions:

* In this one case - add a useless "size" column to sp_Blitz, and do a new build of the Consultant Toolkit - this doesn't actually work, because if you run an OLDER version of the Consultant Toolkit, and a NEWER version of sp_Blitz, then sp_Blitz fails again because the temp table definitions are different.
* Make everybody update all their scripts all the time - yeah, never gonna happen.
* Add a new parameter for sp_Blitz to skip the version checking, and have the Consultant Toolkit default to that.
* Have the Consultant Toolkit create a temp table for the SkipChecks feature, populate the list of checks to skip. This is what I'm going to try first because I think it may come in handy if we need to skip another check again later.

**Comment by BrentOzar** [comment]
Forgot to add: here's a simple repro that doesn't require running the Consultant Toolkit:

```
CREATE TABLE #driveInfo (id INT);
GO
sp_Blitz @VersionCheckMode = 1

```

**Comment by erikdarlingdata** [comment]
Oh that's hilarious. I didn't think to check in the old version of Blitz on there. 

I suppose you could wrap that in a try-catch block, too, if you're feeling spry.

**Comment by BrentOzar** [comment]
Alright, here we go - try this new build:
https://www.brentozar.com/training/consultant-toolkit/download-the-consultant-toolkit/

**Comment by erikdarlingdata** [comment]
To continue the hilarity, the link on that page to download is a bit wonky. It's missing the : somehow.
![image](https://user-images.githubusercontent.com/2136037/93468681-57934c80-f8bd-11ea-9738-8a0b20674c7f.png)

**Comment by PierreLetter** [comment]
Maybe put the size column back in? I renamed it to make it clear which one is availableMb and which one is totalMb but since it's under the hood, not really important to have it that clean.

**Comment by BrentOzar** [comment]
@erikdarlingdata sorry about that - fixed.

@PierreLetter - we would still have the problem if someone has a NEWER sp_Blitz, and an OLDER Consultant Toolkit (which wouldn't have the available_mb column.) So I'd rather fix it this way by disabling the version checks. Thanks though!

**Comment by erikdarlingdata** [comment]
confirming the new build works over here. thanks!

**Comment by BrentOzar** [comment]
Perfect! Sorry about that, closing.
