### ISSUE TITLE
sp_BlitzFirst: When running on "ExpertMode=1", should not sp_BlitzWho inside sp_BlitzFirst run as "ExpertMode=1" too. 

### ISSUE THREAD

**Issue by CarlosBenito** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2595]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When running sp_BlitzFirst in ExpertMode=1, I think that sp_BlitzWho should run in ExpertMode=1 too. In previous versions of sp_BlitzFirst before the creation and calling sp_BlitzWho that was the behavior. 

**Describe alternatives you've considered**
Modify the download version of sp_BlitzFirst

**Are you ready to build the code for the feature?**
I have not problem doing this but I would have to become familiar with the process of how to do it. 

Here is the code:
line 135

Before
@BlitzWho NVARCHAR(MAX) = N'EXEC dbo.sp_BlitzWho @ShowSleepingSPIDs = ' + CONVERT(NVARCHAR(1), @ShowSleepingSPIDs) + N';',

After
@BlitzWho NVARCHAR(MAX) = N'EXEC dbo.sp_BlitzWho @ShowSleepingSPIDs = ' + CONVERT(NVARCHAR(1), @ShowSleepingSPIDs) + N', @ExpertMode = ' + CONVERT(NVARCHAR(1), @ExpertMode) + N';',

Thanks.

**Comment by BrentOzar** [comment]
Okay, so I'm going to be honest here: if your request isn't related to a problem, then we're probably not going to change the behavior of the existing code.

It doesn't make sense to pass @ExpertMode on to sp_BlitzWho because sp_BlitzWho is *only* called when sp_BlitzFirst is run with @ExpertMode = 1.

If you're having a problem - something that would justify changing the existing behavior that users are accustomed to - then definitely describe that problem, but otherwise, let's focus on problems rather than changes. Fair?

**Comment by CarlosBenito** [comment]
I understand but the behavior changed and the reason that I noticed was that a colleague was looking at one of your videos and the columns showing in the video did not match the columns on the current stored procedure.

Thanks

**Comment by BrentOzar** [comment]
And what year was that video from?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by CarlosBenito** [comment]
https://www.brentozar.com/archive/2016/09/learn-use-sp_blitz-sp_blitzcache-sp_blitzfirst-sp_blitzindex-tutorial-videos/

No worries. Thanks for all your contributions.

**Comment by BrentOzar** [comment]
OK, great thanks - I've deleted that four-year-old video since it doesn't reflect how sp_BlitzFirst calls sp_BlitzWho. Thanks!


---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws
