### ISSUE TITLE
sp_AllNightLog creation fails because of collation conflict

### ISSUE THREAD

**Issue by ChaosBladeCoder** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2606]
**Version of the script**
Version 3.98 
VersionDate 20200913

**What is the current behavior?**
Creation of the sp_AllNightLog procedure in a database which has a default collation which is different from the collation of the MSDB database fails with the following error:

Msg 468, Level 16, State 9, Procedure sp_AllNightLog, Line 545 [Batch Start Line 13]
Cannot resolve the collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CI_AS" in the equal to operation.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Set SQL Server default collation to SQL_Latin1_General_CP1_CI_AS
2. Create a new database with default collation Latin1_General_CI_AS
3. Run the sp_AllNightLog.sql script in the database created in step 2.

**What is the expected behavior?**
SP should be created (and function) without errors.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I am running SQL 2019 with CU6 on Windows Server 2016.

**Comment by BrentOzar** [comment]
sp_AllNightLog should be created in the master database. Your master and msdb databases should always have the same collation.

If you want sp_AllNightLog to work in a database outside of master, or if you want it to support different database collations amongst system databases, this would be something you would need to contribute code for.

I'm going to close this only because it's not something I would code, but if YOU want to contribute that code, you're totally welcome to. Leave a comment here if you want to tackle it, and I'll reopen the issue and assign it to you.

Thanks!
