### ISSUE TITLE
sp_BlitzLock -- addition of @OutputXMLasNVARCHAR parameter?

### ISSUE THREAD

**Issue by lewisrl3273** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2613]
I would like the ability to copy the sp_BlitzLock results to Excel.  It would be great if the deadlock_graph output can be manipulated like the QueryPlan is in sp_Blitz -->  CAST([QueryPlan] AS NVARCHAR(MAX)) AS QueryPlan.

**Comment by BrentOzar** [comment]
You got it. Took a quick look in there and it'll be easy, will do this afternoon.

**Comment by lewisrl3273** [comment]
Thank you so much, Brent.  I know that takes time from your already full day, and I really appreciate this.  I know a lot of your other users will, too.

We’re getting killed down here in Cozumel right now w/ hurricane delta.  I tried to video it at the heaviest last night... not so good.  🙄 But insane being out in that wind and water.  I love it!

**Comment by BrentOzar** [comment]
OK, done! The new parameter is @ExportToExcel because that's the functionality you really want if you're copy/pasting into Excel. (If I just cast it as NVARCHAR(MAX), then it'll still have CR/LFs in it, and it'll still break in Excel.)

Changes in the output:

* Query - abridged to 32K, stripped of CR/LF, other stuff that would break copy/paste to Excel
* Deadlock Graph - null
* Object Names - null. This one, somebody else could make work - we would just need to change it from an XML output to a comma-delimited list of object names. I'll leave that for someone else if they want to do it though - this should at least get you pretty close, since it's got the queries in there, and usually you can reverse engineer the object involved based on the running queries.

Give the one in the dev branch a shot and let me know if it works for you: https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/sp_BlitzLock.sql

And stay safe down there!

**Comment by BrentOzar** [comment]
Rebecca reports this is working like a shot of tequila, so closing.

**Comment by lewisrl3273** [comment]
More like two shots of tequila.  Thank you, Brent!!  Much appreciated.
