### ISSUE TITLE
sp_BlitzIndex - Include a Sort Direction parameter

### ISSUE THREAD

**Issue by DavidAPoole** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2651]
First time using GitHub and contributing, so apologies in advance if I am not doing this correctly.

**Is your feature request related to a problem? Please describe.**
When you have a number of +1TB databases (trying not to say large ;) ) that contain numerous indexes, looking for the least/most used/useful indexes by sorts on ratio, reads, size etc, would be easier if there was a sort direction parameter included to use alongside the current sort ordering one.

**Describe the solution you'd like**
A @SortDirection parameter that would allow alternative ASC and DESC sorting.

e.g.
sp_BlitzIndex @Mode = 2, @SortOrder = 'reads', @SortDirection = 'ASC';
sp_BlitzIndex @Mode = 2, @SortOrder = 'reads', @SortDirection = 'DESC';

**Describe alternatives you've considered**
Current alternatives are:
1. Copy and paste into a spreadsheet and sorting by column to alternate between ascending and descending;
2. Scrolling down to the bottom of the SSMS result pane when using the current @SortOrder parameter because it currently only sorts in one direction, descending.

**Are you ready to build the code for the feature?**
Already coded and tested. The amended sp_BlitzIndex procedure is in the attached text file. (GitHub would not allow me to upload in the .sql extension?)

[sp_BlitzIndex with SortDirection.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/5460447/sp_BlitzIndex.with.SortDirection.txt)

**Comment by DavidAPoole** [comment]
[Uploading sp_BlitzIndex with SortDirection.txt…]()

**Comment by BrentOzar** [comment]
Hi, and welcome to Github! For your next contribution, can you read the contributing guide on how to get started? That explains how to use Github and do pull requests: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

Otherwise, if you just upload a file, the problem is that other people have also changed that same file, so we can't just take your code changes as-is. It requires a ton of work on my side.

For this one, I'll go ahead and code it myself - but thanks for the suggestion!

**Comment by BrentOzar** [comment]
(Just to be clear - the only reason I'm coding it myself is because sp_BlitzIndex has changed since you started working on it, so if I just have the text file alone, it's a big pain in the rear to merge the changes.)
