### ISSUE TITLE
sp_BlitzCache errors with @ignore_query_hashes set on SQL 2016

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#276]
Executing sp_BlitzCache v2.5.1
Setting up temporary tables for sp_BlitzCache
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Adding SQL to collect trigger stats.
Collecting execution plan information.
Msg 4104, Level 16, State 1, Line 83
The multi-part identifier "qs.query_hash" could not be bound.
Msg 8156, Level 16, State 1, Line 89
The column 'query_hash' was specified multiple times for 'qs'.
Msg 4104, Level 16, State 1, Line 188
The multi-part identifier "qs.query_hash" could not be bound.
Msg 4104, Level 16, State 1, Line 294
The multi-part identifier "qs.query_hash" could not be bound.
Computing CPU, duration, read, and write metrics
Warning: Null value is eliminated by an aggregate or other SET operation.
Checking for downlevel cardinality estimators being used on SQL Server 2014.
Warning: Null value is eliminated by an aggregate or other SET operation.
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Building query plan summary data.
Displaying analysis of plan cache.

**Comment by BlitzErik** [comment]
This is broken on 2014, too. Looking into it.

**Comment by BlitzErik** [comment]
I figured out where the problem is, but don't have a fix yet. I wonder if this ever worked. Heh.

The dynamic SQL builds a left join on the temp table holding query hashes and adds it on to the select portion of the three inserts to ##blitzcache_procs. The problem is that it either adds the left join too early, or is incorrectly aliased.

![2016-06-17_15-31-26](https://cloud.githubusercontent.com/assets/11590415/16162358/e716d218-34a0-11e6-9ca1-26208640462e.jpg)

**Comment by BlitzErik** [comment]
This was fixeded.
