### ISSUE TITLE
sp_BlitzAnalysis - Money data type insufficient size causing arithmetic overflow

### ISSUE THREAD

**Issue by ianmanton** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2807]
Logging here as requested by Ade after discussion and resolution on Slack.

sp_BlitzAnalysis and BlitzWho_Deltas use a money datatype which is insufficient for the ms wait values I'm encountering (rightly or wrongly!) - possibly in conjunction with long running db integrity checks from hal ollangren but regardless need to cater for higher wait values:

**sp_BlitzAnalysis:**
Similar to your proposed amend but decimal 38,2 instead of 18,2 (otherwise still failed)
From _CAST(ISNULL((CAST([wait_time_ms_delta] AS MONEY)/NULLIF(CAST([waiting_tasks_count_delta] AS MONEY),0)),0) AS DECIMAL(18,2)) AS [wait_time_ms_per_wait]_
To  _CAST(ISNULL((CAST([wait_time_ms_delta] AS DECIMAL(38,2))/NULLIF(CAST([waiting_tasks_count_delta] AS DECIMAL(38,2)),0)),0) AS DECIMAL(38,2)) AS [wait_time_ms_per_wait]_

Then for **[BlitzWho_Deltas]** (as this would select from in isolation either) circa line 161 onwards change the money casts to decimal 38,2 also edits inline rather than before/after:

 _((CAST([request_logical_reads] AS
				   --MONEY
				   DECIMAL(38,2)
				   )* 8)/ 1024) [Logical_Reads_MB],

                               [request_writes],

			       ((CAST([request_writes] AS
				   --MONEY
				   DECIMAL(38,2)
				   )* 8)/ 1024) [Logical_Writes_MB],
			      
				   [request_physical_reads],

			      ((CAST([request_physical_reads] AS
				   --MONEY
				   DECIMAL(38,2)
				   )* 8)/ 1024) [Physical_reads_MB],
			      
				   [session_cpu],

			       [session_logical_reads],

			       ((CAST([session_logical_reads] AS
				   --MONEY
				   DECIMAL(38,2)
				   )* 8)/ 1024) [session_logical_reads_MB],
			      
				   [session_physical_reads],

			       ((CAST([session_physical_reads] AS
				   --MONEY
				   DECIMAL(38,2)
				   )* 8)/ 1024) [session_physical_reads_MB],
			      
				   [session_writes],

			       ((CAST([session_writes] AS
				   --MONEY
				   decimal(38,2)
				   )* 8)/ 1024) [session_writes_MB],_

**Comment by Adedba** [comment]
For sp_BlitzAnalysis we can lose the outer cast too as that will no longer be required due to casting to decimal(38,2) :on the inside.

Proposed:
`CAST(ISNULL((CAST([wait_time_ms_delta] AS DECIMAL(38,2))/NULLIF(CAST([waiting_tasks_count_delta] AS DECIMAL(38,2)),0)),0) AS DECIMAL(38,2)) AS [wait_time_ms_per_wait]`

Revised: 
`ISNULL((CAST([wait_time_ms_delta] AS DECIMAL(38,2))/NULLIF(CAST([waiting_tasks_count_delta] AS DECIMAL(38,2)),0)),0) AS [wait_time_ms_per_wait]`

This change looks good if you want to submit a pull request for the above? Otherwise I can go ahead an do it , just don't want to steal your good work :)

With regards to BlitzWho_Deltas , did you run into an error with the view or is this change to bring it in line with the decimal changes? All for it just want to be sure that we are documenting the change correctly. Ideally that change should have its own issue as we need to alter sp_BlitzFirst for that one. We probably do not need to go with DECIMAL(38,2) for BlitzWho_Deltas though, I imagine we can get away with a smaller decimal as the view is calculating read and write megabytes which should be considerably smaller than wait time milliseconds. You can squueze pretty big number into the money datatype so something like a DECIMAL(18,2) might suffice here . Let me know and we can get these changes in too on a new issue either way.

.

**Comment by ianmanton** [comment]
Hi @Adedba  - the change to BlitzWho_Deltas I believe I made because decimal 18,2 was insufficient there also  - however to evidence I changed it back and went to pick my problem day again however the 3 day retention period on that table has gone past now so sunday's big value has gone.   Referring back to screenshots in slack the value went to 3790006170 on wait_time_ms_deltas but this was obviously a) focused on wait time deltas in Blitzfirst wait stats deltas b) poss too narrow example of just wait stats as ultimately I changed the reads/writes also.

So... question back to you, is there likely to be any performance degradation from having it case as decimal 38,2 over 18,2 or negligible - to which adds a safety net I suppose if the bigger of the two. Certainly spblitz analysis would not run for that window until it was dec38, so my too-late-to-prove-now-I've-slept assumption is that I did the same to BlitzWho_Deltas to make it work. 

If you want certainty I can run again monday after the next weekly integrity checks and see what happens.  Or I can just log a separate request if necessary if there's no anticipated impact from the change beyond wider scope for values.

Main confusion however is clearly my largest value on waits was 10 digits long, even then multiplying by 8 as per the view code, it goes to 11 - so in my head decimal 18 would have been fine but clearly it did not work that way. Perhaps one of the other adjusted values was bigger. 

Cheers
Ian

**Comment by Adedba** [comment]
Lets get a new issue raised for sp_BlitzFirst to update the BlitzWho_Deltas view replacing Money with Decimal(38,2) i don't believe there will be a performance impact , gave it a quick test locally and seemed identical to be honest. At the time when i mentioned it I was thinking memory grant but doesn't look like this change makes any difference to the memory grant from what I could see  :) . Thanks again!

**Comment by ianmanton** [comment]
> Lets get a new issue raised for sp_BlitzFirst to update the BlitzWho_Deltas view replacing Money with Decimal(38,2) i don't believe there will be a performance impact , gave it a quick test locally and seemed identical to be honest. At the time when i mentioned it I was thinking memory grant but doesn't look like this change makes any difference to the memory grant from what I could see :) . Thanks again!

Thanks @Adedba - ok I'll submit in a mo - for BlitzWho Deltas the issue does remain with 18,2 being arithmetic overflow too - but it looks the cause is here is logical reads - I assume best to play safe and cast all though - my max values from period yesterday:

request_logical_reads 3285375934100111089,	  -- whoah that's a bg ol' numberino!
request_writes 145130,	
request_physical_reads	699110633	
session_logical_reads	160679220	
session_physical_reads	88855	
session_writes 4851356

**Comment by BrentOzar** [comment]
Thanks for the pull request! Merged into the dev branch, will be in the March release with credit to you.
