### ISSUE TITLE
Standardize tab/space/comma formatting across procs

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#287]
Try to format them with https://format-sql.com/ and see if that works. (Not sure if it'll throw errors based on the sizes & output of the scripts.) If that works, use that as the default, and document it in the README.md for now as part of our development standards.

I like using a site like that because it's free for anyone to use when they're developing.

**Comment by BrentOzar** [comment]
Hmmm, tried a bunch of online ones and couldn't get one that worked across all of the stored procedures. Changing this back to open, removing myself as the assignee, and removing the milestone.

If you want to tackle this ticket:
* Find an online formatter that you can just copy/paste each of the major stored procs into (sp_Blitz, sp_BlitzCache, sp_BlitzIndex)
* Format the SQL using the tool's defaults
* Take the output as-is, copy/paste it into SSMS, and make sure it actually runs

**Comment by nschonni** [comment]
I'd suggest adding an [EditorConfig](http://editorconfig.org/) file since GitHub respects those settings when previewing files on the web. There doesn't appear to be an SSMS plug-in at the moment, but you'll find it in most MS open source projects now so they might be open to creating a plug-in for it. 
I can do a do a quick PR to normalize this stuff, but I need to know
- Tabs vs Spaces
- Number of tab stops (2 or 4 usually)
- Leave trailing whitespaces
- Add/Remove blank EOF line

**Comment by BrentOzar** [comment]
Oh wow, didn't know about EditorConfig.

* Tabs vs Spaces - I'm a tab guy myself only because SSMS uses them by default, and I'm guessing most of the contributors are likely to use tabs. I'm open to either, though.
* Number of tab stops - I like 4.
* Leave trailing whitespaces - no, unless you know of a good reason to leave them in? (I've never thought about this before so I may be wacko here.)
* Add/Remove blank EOF line - I'll leave this one up to you because I don't know this one either, hahaha.

**Comment by Jorriss** [comment]
Not all of us use SSMS. Crazy, I know. and not all of us use the same tab stop settings.. Crazy, I know. With spaces the indenting never changes it's always x number of spaces. EditorConfig would help (a bunch) and we should create one, but until SSMS natively uses EditorConfig we're going to have formatting issues. We probably should draft a formatting document and reject PRs that don't adhere to it. Then we need to format the scripts accordingly because readability matters.

**Comment by BrentOzar** [comment]
Closing this, not going to try to force this on everybody.
