### ISSUE TITLE
sp_Blitz not skipping check 184 on Amazon RDS

### ISSUE THREAD

**Issue by rrankins** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2879]
**Version of the script**
Version = '8.03', @VersionDate = '20210420'

**What is the current behavior?**
Raises an permission error on xp_readerrorlog when it should be skipping this check on Amazon RDS

**If the current behavior is a bug, please provide the steps to reproduce.**
Run sp_blitz in an instance of SQL Server running under Amazon RDS
**What is the expected behavior?**
skip this check and avoid the error message

The problem is missing parentheses around the OR conditions.
This code:

					IF NOT EXISTS ( SELECT  1
									FROM    #SkipChecks
									WHERE   DatabaseName IS NULL AND CheckID = 184 )
							AND (@ProductVersionMajor >= 13) OR (@ProductVersionMajor = 12 AND @ProductVersionMinor >= 5000)

needs to be changed to this:

					IF NOT EXISTS ( SELECT  1
									FROM    #SkipChecks
									WHERE   DatabaseName IS NULL AND CheckID = 184 )
							AND ((@ProductVersionMajor >= 13) OR (@ProductVersionMajor = 12 AND @ProductVersionMinor >= 5000))

**Comment by BrentOzar** [comment]
Great catch! Fixed in the dev branch. In case you go looking at the changed code, I also had to tweak one other thing - it had the wrong CheckID in there. This check was supposed to be 193. (It had different references to different numbers in different places somehow over the years.) It'll be in the May release with credit to you in the release notes.
