### ISSUE TITLE
sp_BlitzCache: plan count bug (reported on dba.se)

### ISSUE THREAD

**Issue by erikdarlingdata** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2900]
**Version of the script**
The latest, according to this [very helpful user with phenomenal code formatting](https://dba.stackexchange.com/a/291612/32281)

**What is the current behavior?**
We count the wrong thing

**If the current behavior is a bug, please provide the steps to reproduce.**
Click the link above for more details. It's free.

**What is the expected behavior?**
Count the right thing

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Any and all.

**Comment by erikdarlingdata** [comment]
Well this gets more interesting! The code referenced in the answer is from [this page](https://www.brentozar.com/blitzcache/multiple-plans/), but the code in BlitzCache that does the same thing is even more wronger. It looks like it only counts plans that are in `##BlitzCacheProcs`, not the cache as a whole.

```
RAISERROR(N'Gathering high level plan information', 0, 1) WITH NOWAIT;
UPDATE  ##BlitzCacheProcs
SET     NumberOfDistinctPlans = distinct_plan_count,
        NumberOfPlans = number_of_plans ,
        plan_multiple_plans = CASE WHEN distinct_plan_count < number_of_plans THEN number_of_plans END
FROM (
        SELECT  COUNT(DISTINCT QueryHash) AS distinct_plan_count,
                COUNT(QueryHash) AS number_of_plans,
                QueryHash,
				DatabaseName
        FROM    ##BlitzCacheProcs
		WHERE SPID = @@SPID
        GROUP BY QueryHash,
		         DatabaseName
) AS x
WHERE ##BlitzCacheProcs.QueryHash = x.QueryHash
AND   ##BlitzCacheProcs.DatabaseName = x.DatabaseName
OPTION (RECOMPILE) ;
```

Gotta redo this section.

**Comment by BrentOzar** [comment]
This is so interesting! Here's the demo code I'm using to test:

`/* One time setup */
USE StackOverflow;
GO
CREATE INDEX Location ON dbo.Users(Location);
GO


/* Run this part for testing: */
DBCC FREEPROCCACHE;
GO
DROP TABLE IF EXISTS #Locations;
SELECT TOP 20 Location
	INTO #Locations
	FROM dbo.Users
	GROUP BY Location
	ORDER BY COUNT(*) DESC;
GO
DECLARE @Location NVARCHAR(100), @StringToExec NVARCHAR(4000);
DECLARE curses CURSOR FOR SELECT Location FROM #Locations;
OPEN curses;
FETCH NEXT FROM curses INTO @Location
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @StringToExec = N'SELECT TOP 101 * FROM dbo.Users WHERE Location = N''' + @Location + N''' ORDER BY Reputation DESC;'
	EXEC(@StringToExec);
	FETCH NEXT FROM curses INTO @Location;
END

CLOSE curses;
DEALLOCATE curses;
GO

EXEC sp_BlitzCache
GO
`

The current release of sp_BlitzCache does this, which is wrong:
<img width="935" alt="Screen Shot 2021-05-20 at 5 57 47 AM" src="https://user-images.githubusercontent.com/245462/118927312-1d3cec00-b931-11eb-8983-65562d1b1661.png">

* A - showing different queries (good)
* B - showing different query costs (good - just pointing out that one of the plans does table scans (~400 cost) and one does index seeks (~50-100 cost)
* C - "Multiple Plans (9)" - bad. This is where we're trying to correct it to show that there are actually 19-20 plans cached, which is why the new version hits the base view.

The new version that joins on QueryPlanHash does this:
<img width="921" alt="Screen Shot 2021-05-20 at 5 59 38 AM" src="https://user-images.githubusercontent.com/245462/118927521-6db44980-b931-11eb-8b66-0bef693964a6.png">

D - that's also wrong, but it's really close, but it also raises an interesting point: we effectively have 2 different plans here (the clustered index scan, and the index seek + key lookup plan). 

If I change the join & grouping to QueryHash, I get:
<img width="929" alt="Screen Shot 2021-05-20 at 6 01 57 AM" src="https://user-images.githubusercontent.com/245462/118927664-ab18d700-b931-11eb-838a-285904e187c4.png">
E - this is what I think we were originally going for, saying "Yo, this query has been cached 19 times," but now that I'm looking at it, a better return would probably be something like, "Multiple Plans (19 total, 2 distinct)".

Or should we just call it good with 19?
