### ISSUE TITLE
sp_Blitz: Add new check for Agent Jobs missing schedules

### ISSUE THREAD

**Issue by MikeScalise** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2903]
**Is your feature request related to a problem? Please describe.**
In my mind, the three main components of an Agent Job are its Step(s), Schedule(s), and Notification(s). sp_Blitz already has a check for Agent Jobs Without Failure Emails (Check #94), but not for missing steps or schedules. It would be beneficial to know if there are enabled jobs that are missing either one of these.

**Describe the solution you'd like**
A check for jobs that are enabled but missing a schedule.

Here's the code to create a job that would meet the criteria:

```
IF EXISTS (SELECT job_id FROM msdb.dbo.sysjobs_view WHERE name = N'AgentJobWithoutSchedules')
EXEC msdb.dbo.sp_delete_job @job_name=N'AgentJobWithoutSchedules', @delete_unused_schedule=1
GO

DECLARE @jobId BINARY(16);

EXEC msdb.dbo.sp_add_job @job_name=N'AgentJobWithoutSchedules', 
                                             @enabled=1,
					     @job_id = @jobId OUTPUT;

EXEC msdb.dbo.sp_add_jobstep @job_id=@jobId,
                                                    @step_name=N'StepOne', 
						    @step_id=1,
						    @subsystem=N'TSQL', 
						    @command=N'SELECT 1', 
						    @database_name=N'master';

EXEC msdb.dbo.sp_add_jobserver @job_id = @jobId,
                                                       @server_name = N'(local)';
```

**Describe alternatives you've considered**
Check each enabled job to see if they are have a schedule defined.

**Are you ready to build the code for the feature?**
Yes, I have a copy of it ready.

**Comment by BrentOzar** [comment]
I actually see a *lot* of jobs without schedules because they get kicked off manually by people or by code.

I totally hear you that it's something you're interested in finding, but I don't think it's a good idea to add this to sp_Blitz directly because it'll produce so many warnings at shops where this isn't a problem.

I'm going to close this, but it's a great topic for a blog post! I'd encourage you to write a blog post and share the code you've written as a standalone script.
