### ISSUE TITLE
New/Unknown wait_types?

### ISSUE THREAD

**Issue by mvomhau** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2930]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.

SELECT @Version = '8.04', @VersionDate = '20210530';

**What is the current behavior?**
we are running sp_BlitzCache on a regularly basis. 
With the SP version mentioned above, there are wait_types in the @OutputTableNameWaitStats-table that are not listed in the @OutputTableNameWaitStats_Categories-table.

**If the current behavior is a bug, please provide the steps to reproduce.**
we just call the SP like so

exec sp_BlitzFirst 
    @OutputDatabaseName = 'DBATools', 
    @OutputSchemaName = 'dbo', 
    @OutputTableName = 'DBABlitzFirst',
    @OutputTableNameFileStats = 'DBAFileStats',
    @OutputTableNamePerfmonStats = 'DBAPerfmonStats',
    @OutputTableNameWaitStats = 'DBAWaitStats',
    @OutputTableNameBlitzCache = 'DBABlitzCache'

**What is the expected behavior?**
I expect that all wait_types are in the @OutputTableNameWaitStats_Categories-table

**Which versions of SQL Server and which OS are affected by this issue?**
Microsoft SQL Server 2017 (RTM-CU24) (KB5001228) - 14.0.3391.2 (X64) 
	Apr 28 2021 10:32:18 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

**Did this work in previous versions of our procedures?**
yes

here are the unknown wait_types out server has collected:

BACKUPBUFFER
BACKUPTHREAD
BMPBUILD
BPSORT
CXROWSET_SYNC
DEBUG
EXECSYNC
EXTERNAL_SCRIPT_NETWORK_IO
FFT_RECOVERY
HTBUILD
HTDELETE
HTMEMO
MSQL_DQ
MSQL_XP
OLEDB
PERFORMANCE_COUNTERS_RWLOCK
PWAIT_ALL_COMPONENTS_INITIALIZED
QUERY_EXECUTION_INDEX_SORT_EVENT_OPEN
QUERY_TASK_ENQUEUE_MUTEX
SESSION_WAIT_STATS_CHILDREN
SLEEP_BPOOL_STEAL
SOS_SYNC_TASK_ENQUEUE_EVENT
WAIT_XTP_HOST_WAIT
WAIT_XTP_OFFLINE_CKPT_LOG_IO
WAIT_XTP_RECOVERY
WAIT_XTP_TASK_SHUTDOWN
XE_BUFFERMGR_ALLPROCESSED_EVENT
XTP_PREEMPTIVE_TASK

**Comment by BrentOzar** [comment]
Microsoft adds new wait types all the time without documenting them. There's no one permanent list that includes all possible wait types.

If you have a wait type you'd like to add, you're welcome to contribute that to the script. Here's the contributing guide: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

I'll go ahead and close this for now because it sounds like you expected someone else to code it for you, but if you change your mind and you'd like to work on the code, feel free to read the contributing guide and reopen the issue.

Thanks!
