### ISSUE TITLE
sp_BlitzCache  -  Arithmetic overflow error converting numeric to data type numeric.

### ISSUE THREAD

**Issue by mike-halford** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2932]
**Version of the script**
8.04 20210530

**What is the current behavior?**
sp_BlitzCache generates error - Arithmetic overflow error converting numeric to data type numeric.

Having looked at closed issues this is not the same as #2890 

Issue Details
In v8.03 the following temp table is created
CREATE TABLE #plan_usage
(
    duplicate_plan_handles BIGINT NULL,
    percent_duplicate NUMERIC(7, 2) NULL,
    single_use_plan_count BIGINT NULL,
    percent_single NUMERIC(7, 2) NULL,
    total_plans BIGINT NULL,
	spid INT
);

In v8.04 the following is created
CREATE TABLE #plan_usage
(
    duplicate_plan_hashes BIGINT NULL,
    percent_duplicate DECIMAL(5, 2) NULL,
    single_use_plan_count BIGINT NULL,
    percent_single DECIMAL(5, 2) NULL,
    total_plans BIGINT NULL,
	spid INT
);

Note change from NUMERIC to DECIMAL data types.

Reverting back to NUMERIC datatypes eradicates the error but am unsure why the change was made and any impact it might have elsewhere. Is only affecting one server out of 30 that we have but not sure why.

**Comment by erikdarlingdata** [comment]
I got this one.

Yeah, I made the change because the insert into plan usage looks like this:

```
INSERT
    #plan_usage
(
    duplicate_plan_hashes,
	percent_duplicate,
	single_use_plan_count,
	percent_single,
	total_plans,
	spid
)
SELECT
    m.duplicate_plan_hashes, 
    CONVERT
	(
	    decimal(5,2),
		m.duplicate_plan_hashes
		    / (1. * NULLIF(t.total_plans, 0))
    ) * 100. AS percent_duplicate,
    s.single_use_plan_count, 
    CONVERT
	(
	    decimal(5,2),
		s.single_use_plan_count
		    / (1. * NULLIF(t.total_plans, 0))
	) * 100. AS percent_single,
    t.total_plans,
	@@SPID
FROM many_plans AS m
CROSS JOIN single_use_plans AS s 
CROSS JOIN total_plans AS t;
```

And I figured "hey, those datatypes should match". But then some time later I found that the `* 100.` portion of the code actually ups the datatype implicitly and forgot to change the table definition.

![image](https://user-images.githubusercontent.com/2136037/121777504-77ac1f80-cb60-11eb-89c7-8bfa40be9076.png)

Under odd enough circumstances, the original table definition of `NUMERIC(7, 2)` could still overflow 😃

**Comment by BrentOzar** [comment]
Thanks guys! Merged into the dev branch, will be in the July release with credit to y'all in the release notes.
