### ISSUE TITLE
Is there a database repository to store the results of sp_blitzfirst

### ISSUE THREAD

**Issue by wycislo** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3004]
**Is your feature request related to a problem? Please describe.**

SQL Server on AWS does not allow you to add stuff to msdb, master. So I created my own database to store my own monitoring code into this database. But would like to have a standard way to do this and a way to report on this information. 

Watched an old video of Brent explaining how to store results of sp_blitz into a database called DBATools. But I don't see a create database or create tables to store this information. 

https://youtu.be/rBq2akWJvsA

**Describe the solution you'd like**
1) A specific database to run sp_blitz and all of Brent's awesome stuff from. 
2) Specific tables to store this stuff. 
3) a way to report on this. (Powerbi, excel, sql server data tools) 

**Describe alternatives you've considered**

**Are you ready to build the code for the feature?**
As much as we'd love to build everything that everyone wants for free, we need your help. Open source is built with your help and code. Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?

Yes. I would love to help build this feature.

**Comment by BrentOzar** [comment]
We used to have a PowerBI Dashboard for DBAs, and we actually deprecated it and removed it. The problem is support: there are just so many people who need their hands held when using reporting tools, and we didn't have the time to do that level of support.

If you'd like to build a separate open source project for storage & reporting, you're welcome to, but unfortunately that wouldn't be something that we could help with or distribute. The support workload is just too high.

Thanks for offering though!
