### ISSUE TITLE
@StopAt parameter should be a real point in time restore

### ISSUE THREAD

**Issue by daniel70** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3038]
The @StopAt parameter currently restores log files **before** the point-in-time.
If we take log backups every hour, on the hour, and the @StopAt value is '20211201104500' (10:45 AM), we restore to 10:00 AM losing 45 minutes of transactions.

In my company, we know which job has failed and want to restore to the point-in-time right before that job started, to 10:45 AM in this case.

Looking at the source code for sp_DatabaseRestore all that's needed is to restore one more log file with the STOPAT parameter that is documented [here](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-a-sql-server-database-to-a-point-in-time-full-recovery-model?view=sql-server-ver15#TsqlProcedure).

I would like to add that feature unless someone has a good use case against it.

**Comment by erikdarlingdata** [comment]
@daniel70 I've assigned the issue to you. Please keep us updated on progress. If this goes silent for ~30 days, I'll close it out.

Thanks!

**Comment by BrentOzar** [comment]
Thanks for the pull request. Looks good - I haven't tested it since I don't have a testbed for sp_AllNightLog or sp_DatabaseRestore, but conceptually it makes sense. Merging into the dev branch, will be in the next release with credit to you in the release notes.

**Comment by zbraddock** [comment]
Heya, I've noticed that when you try to restart log shipping after using a @StopAt Param to pause logshipping*, if there was a log file that was partially restored, when you pick logshipping back up the sp_DatabaseRestore proc doesn't go back and restore the rest of the partially restored file - it tries to restore the next one in the chain instead, which of course doesn't work. 
Is that intentional functionality? 

* For example, if you want your log ship target to be airgapped so it is always an hour behind your other servers

**Comment by zbraddock** [comment]
^^ Looks like thats only a problem if @SkipBackupsAlreadyInMsdb BIT = 1
