### ISSUE TITLE
sp_BlitzIndex does not output forwarded_fetches to OutputTable

### ISSUE THREAD

**Issue by pollusb** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3053]
Here's what I ran:
```
exec dbo.sp_BlitzIndex @GetAllDatabases = 1, @Mode = 2, @SortOrder = 'forward_fetches'
,@OutputDatabaseName = 'tempdb', @OutputSchemaName = 'dbo', @OutputTableName = 'BlitzIndex'
```
The resulting table does not hold the column [Forwarded Fetches]

**Comment by wqweto** [comment]
If you cannot fix this yourself than probably you shouldn't bother about any of the insights `forward_fetches` column brings anyway and that's the beauty of FRK -- its users can fix the code themselves while Brent will smugly accept a Pull Request produced by the party that must be most interested in an urgent quality fix.

**Comment by BrentOzar** [comment]
@pollusb howdy! I took a quick look at the code, and that's true, the Forwarded Fetch column isn't included in the output. There are a few things that are going to make a fix challenging:

* The table creation script needs to be changed - this part is relatively simple
* When sp_BlitzIndex runs, the table might already exist, in which case we have to alter the table if the column isn't there - this part is harder, but it's been done in other scripts like sp_BlitzCache, and that code can be used as a starting point template
* Sometimes the output table is on a different server altogether - note that sp_BlitzIndex can be called with an OutputServerName parameter, and the alter table will have to work there as well, or skip outputting the column - this part is probably the trickiest

Because of the complexity of this, it isn't something that I'd personally be able to do quickly. If it's important to you, you're absolutely welcome to tackle that task, but I gotta warn you that it won't be a 15-minute fix.

Is that something you'd like to work on?

**Comment by BrentOzar** [comment]
@wqweto I think the term "smugly" might not have translated well. Here's what smugly means: https://dictionary.cambridge.org/dictionary/english/smugly

I don't take excessive pride or confidence in other folks' code. I'm always really thankful that they take the time to contribute to open source projects like this. I do wish that I had an unlimited amount of free time to work on everyone's requests, but I do need to balance my work time with spending time with my loved ones. Otherwise, I might end up a bitter old person who goes around leaving nasty comments online, and I certainly wouldn't want to end up like that. ;-)

**Comment by pollusb** [comment]
> If you cannot fix this yourself than probably you shouldn't bother about any of the insights forward_fetches column brings anyway and that's the beauty of FRK -- its users can fix the code themselves while Brent will smugly gladly accept a Pull Request produced by the party that must be most interested in an urgent quality fix.

Wow, I am not in a hurry for a fix. I just wanted to report a bug. 
I didn't want to start a quarrel.
I like the word smugly, though.

>Because of the complexity of this, it isn't something that I'd personally be able to do quickly. If it's important to you, you're absolutely welcome to tackle that task, but I gotta warn you that it won't be a 15-minute fix. 
Is that something you'd like to work on?

Not really. I did check out the code and made an assessment of the effort I would need to put in. I came to the same conclusion as you.

For the record, I resolved that quickly with a few lines of PowerShell code
