### ISSUE TITLE
XML Parsing error with sp_BlitzLock

### ISSUE THREAD

**Issue by dbartv** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3114]
Version 8.09 VersionDate 20220408

**What is the current behavior?**
On line 332 the following code results in the error below:

SELECT CONVERT(XML, event_data) AS deadlock_xml
             FROM   sys.fn_xe_file_target_read_file(@EventSessionPath, NULL, NULL, NULL)

Grab the initial set of XML to parse at Jun 24 2022  3:38:22:833PM
Msg 9415, Level 16, State 1, Procedure sp_BlitzLock, Line 324 [Batch Start Line 0]
XML parsing: line 42, character 89, well formed check: no '<' in attribute value

**If the current behavior is a bug, please provide the steps to reproduce.**
When I try to format the XML  I get the following message:
The value of attribute "indexname" associated with an element type "keylock" must not contain the '<' character. 

Below is the text where I believe it goes wrong:
indexname="<Name of Missing Index, sysname,>" 

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2016 (SP2-CU4) (KB4464106) - 13.0.5233.0 (X64)   Nov  3 2018 00:01:54   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

So in my (very humble) opinion, the xml isn't formed correctly in a .xel file and as a result sp_BlitzLock fails.

**Comment by erikdarlingdata** [comment]
We had a similar issue to this before (#2358), but the only solution was to run a bunch of REPLACEs on the XML, which was el disastero for performance, because there are a lot of weird characters that can cause the issue. 

The deadlock XML is also [inconsistent in dealing with some control characters](https://www.brentozar.com/archive/2018/04/how-to-break-sql-servers-xml-data-collection/). 

If you can find a way to do this that doesn't trash performance, cool, but I'm spent on this one.

**Comment by BrentOzar** [comment]
@dbartv I'm going to go ahead and close this for now, but if you decide you want to work on it later, just leave a note here and we can reopen it. I try not to leave issues open if no one is working on them. Thanks!
