### ISSUE TITLE
sp_Blitz: show databases where compatibility level < maximum possible for instance

### ISSUE THREAD

**Issue by JohnPenn-PCG** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3200]
**Is your feature request related to a problem? Please describe.**
Currently, sp_Blitz lists databases with the finding "Old Compatibility Level" if their compatibility level is <= 90.  When triaging a new client's instance, I would find it helpful to know which databases are not set to the maximum level possible for the instance.

**Describe the solution you'd like**
Modify the "Old Compatibility Level" query to include databases with compatibility levels below the maximum possible.

**Describe alternatives you've considered**
I can manually query sys.databases, but it would be more convenient for sp_Blitz to include this information since it already does this to some extent.

**Are you ready to build the code for the feature?**
Yes, but I'm not sure of the best way to determine what the maximum compatibility level is for the instance.

**Comment by BrentOzar** [comment]
I actually don't recommend jumping to the latest compat level "just because." It has huge effects on execution plans. I wouldn't want folks thinking older compat levels are a problem that they need to fix.

Here's a post about it: https://www.brentozar.com/archive/2018/09/should-you-use-the-new-compatibility-modes-and-cardinality-estimator/

Because of that, I'd rather not "warn" folks about that "problem" in sp_Blitz. If you want to check on your own servers, the easy way to check is:

```
SELECT db.name, db.compatibility_level
FROM sys.databases m
INNER JOIN sys.databases db ON m.compatibility_level <> db.compatibility_level
WHERE m.name = 'master'
```

**Comment by JohnPenn-PCG** [comment]
Understood - I was thinking of it as just informational, like the server info, and not a "fix this now!" item.

**Comment by BrentOzar** [comment]
Yeah, I try not to add any new "hey just FYI" stuff in there because people already get overwhelmed with the level of detail we provide. You wouldn't believe how many consulting clients I get where people say, "We ran sp_Blitz and we're just overwhelmed with how much stuff is in there - help!"
