### ISSUE TITLE
DatabaseRestore: Include STATS

### ISSUE THREAD

**Issue by lowlydba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3205]
**Is your feature request related to a problem? Please describe.**
Adding a parameter to toggle the STATS option to report restore status at an interval between 1-100%

**Describe the solution you'd like**
Something like `@Stats` as a tinyint that would report back on stats for full or diff file restores. Not sure if there is value in adding it for the tlog restores too.

**Are you ready to build the code for the feature?**
Ready to go once a consensus is reached

**Comment by BrentOzar** [comment]
Why not use sp_WhoIsActive or sp_BlitzWho and check the percent completed?---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Jan 1, 2023, at 7:46 AM, John McCall ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
Adding a parameter to toggle the STATS option to report restore status at an interval between 1-100%
Describe the solution you'd like
Something like @Stats as a tinyint that would report back on stats for full or diff file restores. Not sure if there is value in adding it for the tlog restores too.
Are you ready to build the code for the feature?
Ready to go once a consensus is reached

**Comment by lowlydba** [comment]
Sure, someone can do that. But I'm looking to have it print its own progress with the stats interval option.

**Comment by BrentOzar** [comment]
In order to minimize complexity, let's not add in functionality that's already present in other procs. 

Nothing personal - there are just only so many hours in my day, and someone has to test this work. I've learned that other folks just won't test the restore procs for some reason. Not you, but someone has to test to verify that it works, and since nobody else steps up, that ends up being me, and I have really limited hours to work on this kind of thing.

Again, nothing personal, and thanks for volunteering to do it. Happy New Year!

**Comment by lowlydba** [comment]
Totally fair, been there myself.

It makes me sad though that it seems a lack of automated testing is holding back features/enhancements on a beloved suite of scripts. If you're interested in partnering on adding a testing framework that would allow you to enforce contributions to have test coverage, I'd be happy to help/advise. 

I've had success with tSQLt and GoEddie's code coverage tool on projects like this: https://github.com/lowlydba/dba-multitool/actions/workflows/sqlserver-unit.yml 

At the very least there is good comfort in knowing the procs can create and run without error across newer versions, even if 100% feature coverage isn't reasonable.

**Comment by BrentOzar** [comment]
The problem with automated testing with DBA scripts is simulating the output of DMVs. For example, how do you simulate the output of SELECT * FROM sys.databases? You can't edit the content of those actual databases, and we certainly wouldn't want to change the scripts themselves to point to placeholder views across thousands of lines of code.

**Comment by lowlydba** [comment]
You'd have to create the databases :) If you look at my linked sample what I am testing is DBA scripts that are often tricky, but again the main point is that something is better than nothing.

**Comment by BrentOzar** [comment]
Again -  there are just only so many hours in my day, and someone has to test your work. It would be amazingly awesome if unit tests worked flawlessly with no human intervention, and never gave false test results.

Something is only better than nothing *if it's reliable and people know how to troubleshoot it when it fails.* That's the part we're missing here - if one volunteer says, "I'll build something to help," but then can't guarantee it'll work, and can't guarantee that they'll be around to support it when it breaks, then it's not helping - it's hurting.

In my commercial work, like SQL ConstantCare, Paste the Plan, PollGab, etc, we absolutely have unit testing. However, that's because I have a full time employee who can be relied on to drop everything on a moment's notice and fix problems with the unit tests. That's not the case in a public open source project like this.
