### ISSUE TITLE
sp_BlitzLock error

### ISSUE THREAD

**Issue by AlexanderMaizanov** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3212]
When I run this command
[dbo].[sp_blitzlock] @databasename ='databasename'
I got this error: 
`Msg 8114, Level 16, State 5, Procedure sp_BlitzLock, Line 1762 [Batch Start Line 2]
Error converting data type nvarchar to bigint.`
This line `dow.database_id = @DatabaseName OR @DatabaseName IS NULL` in sp_BlitzLock causes the error. Must be changed to `dow.database_id = @DatabaseId OR @DatabaseName IS NULL`.

**Comment by BrentOzar** [comment]
Welcome to Github! When you file an issue, you wanna make sure there's not already an issue about what you're describing. In this case, it's here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3201

And that issue has already been fixed in the dev branch of the code. You can download that here: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzLock.sql

And it'll be in the next release. Cheers!
