### ISSUE TITLE
sp_Blitz - Add Check for Failing Agent Jobs

### ISSUE THREAD

**Issue by RichBenner** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3220]
**Is your feature request related to a problem? Please describe.**
As a consultant, I regularly run healthchecks but it doesn't pick up Agent jobs that are failing. Then we install the monitoring tool and often get spammed by agent failure alerts. It would be good if we could get alerted from Blitz that there are jobs that are failing so we can fix it.

**Describe the solution you'd like**
Add a check to sp_Blitz to alert for failing agent jobs.

**Describe alternatives you've considered**
We can run this as a script elsewhere, but it would be neater if it was rolled into sp_Blitz

**Are you ready to build the code for the feature?**
Yep, happy to. Only question is whether we have a "You have failing agent jobs" or whether we would list the jobs that are failing.

**Comment by BrentOzar** [comment]
Howdy sir! This has actually come up in the past, and my feeling has been, "If an Agent job is failing, it's dangerous to suddenly 'fix' it and trigger logic that might not have been run in forever."

I'll give you an example from one of my clients. A new DBA looked at a server, saw an Agent job had been failing for weeks. He investigated the query, 'fixed' the logic by changing a table name, and then the job started succeeding.

Days later, the developers were completely freaking out because all their web site pricing was wrong. Turns out they'd moved to a new table structure, and they didn't *want* the old logic running - but by 'fixing' the table names, the DBA had caused the jobs to affect the new tables.

So I'm really hesitant here - I don't think that fixing Agent jobs should be part of a health check like sp_Blitz. I think it belongs in an operational monitoring tool, so I think it's actually *good* that the monitoring tool picks it up. It's more of an application problem than a SQL Server engine problem.

Another reason why: how far back should sp_Blitz check for failures? Usually *lots* of jobs fail from time to time. Is it a problem that a job failed once a few days ago, and ran successfully since?

**Comment by RichBenner** [comment]
That's totally fair and I understand the pitfalls in suddenly 'fixing' an agent job that had already been failing. Does feel like a simple check like 'you've had agent jobs failing in the past week, go check it out' wouldn't be outside the realms of sp_Blitz. 

Seems like fixing the jobs is a completely separate issue, and one that would happen whether it was picked up by sp_Blitz or whether we waited for the alerts to come through the monitoring tool. I would imagine the attempted fix would have been the same either way, it's just the timing of the fix that differs here. This would be (for me) extremely useful in the consultant toolkit where we can add a line that we need to go check these out. At the moment, unless we run an external script, we just wouldn't know about it.

For the part about agent jobs not being part of sp_Blitz, they already are to a certain extent: 'agent jobs without failure emails', 'agent jobs not owned by sa', 'agent jobs at startup' etc. 

Regarding intermittent failures, I imagined this would have gone in the '200 - informational' section in sp_Blitz, similar to 'agent jobs without failure emails'. It's not a huge problem, but it's something that should be investigated further.

Ultimately, if it's not appropriate for this script then by all means, this issue can be closed. I just know that it would fix a particular pain point that I'm feeling at the moment.

**Comment by BrentOzar** [comment]
Yeah, but if it's too broad ("you've had Agent jobs failing in the last week") then EVERY server will trigger it, because everybody has jobs fail from time to time.

How about, this job has failed every time that it's run in the last week?

**Comment by RichBenner** [comment]
Sure, that works.

I'll get the check written and submitted the usual way.

**Comment by BrentOzar** [comment]
Thanks sir!

**Comment by BrentOzar** [comment]
It's been a month, so I'm going to go ahead and close this for now. If you want to submit a pull request with your changes, feel free to leave a note here though and I can reopen the issue. Thanks!
