### ISSUE TITLE
New Script: sp_help_revlogin

### ISSUE THREAD

**Issue by lowlydba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3231]
**Is your feature request related to a problem? Please describe.**
You know it, you love it, the classic [sp_help_revlogin](https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/security/transfer-logins-passwords-between-instances) - lets add it to the FRK! 

The support articles repo this lives in uses the MIT license for code.

**Describe the solution you'd like**
Include a copy of it in the FRK. It doesn't [change often](https://github.com/MicrosoftDocs/SupportArticles-docs/commits/main/support/sql/database-engine/security/transfer-logins-passwords-between-instances.md) and there isn't an easy official way to grab and install a copy right now since it lives embedded in a markdown file. 

Adding it to the kit would make it much easier to install and maintain (i.e. via the FRK bundle, DbaTools wrappers, etc.) and be a low-effort value add to the FRK.

**Describe alternatives you've considered**
We could just *not*. Which is fine. But I'm tired of manually copying and pasting this from the docs website at this point.

**Are you ready to build the code for the feature?**
Sure, happy to make the updates where needed to wrap this into the suite (along with the DbaTools updates as well).

**Comment by BrentOzar** [comment]
Thanks, but let’s hold off. There’s support work on my side anytime new scripts are added (because people will email me questions about them, assuming that I wrote everything). If you want the script on GitHub, your best bet would be to create your own repository for it. Thanks though!---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Feb 17, 2023, at 9:12 AM, John McCall ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
You know it, you love it, the classic sp_help_revlogin - lets add it to the FRK!
The support articles repo this lives in uses the MIT license for code.
Describe the solution you'd like
Include a copy of it in the FRK. It doesn't change often and there isn't an easy official way to grab and install a copy right now since it lives embedded in a markdown file.
Adding it to the kit would make it much easier to install and maintain (i.e. via the FRK bundle, DbaTools wrappers, etc.) and be a low-effort value add to the FRK.
Describe alternatives you've considered
We could just not. Which is fine. But I'm tired of manually copying and pasting this from the docs website at this point.
Are you ready to build the code for the feature?
Sure, happy to make the updates where needed to wrap this into the suite (along with the DbaTools updates as well).

**Comment by lowlydba** [comment]
Rightio, figured I'd give you first dibs.

I'll go ahead and [add](https://github.com/lowlydba/dba-multitool/issues/269) it to the DBA MultiTool suite I maintain (https://github.com/LowlyDBA/dba-multitool) which also has a DbaTools installer and an ansible equivalent module to wrap the stored proc into IaC automations.
