### ISSUE TITLE
sp_BlitzIndex: remove psychological terms

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3250]
When we first wrote sp_BlitzIndex, we used psychological terms to describe indexes.

Wording like "Self Loathing", "Abnormal Psychology", and "Aggressive Indexes" was confusing, though, and always required a lot of explanation to demystify it. These issues are tough enough for database pros to understand, let alone putting 'em through another layer of abstraction. 

In addition, this language can be off-putting for folks, and we'd rather use inclusive language.

So I'm going to:
* Keep links intact during changes (not change these terms in URLs)
* Change terms like sanity, insanity, addict, holic, phobic, medicated, etc to be more inclusive

This change was originally proposed by @eliprairie, but starting a new issue to track it because I'm going to do it slightly differently.

**Comment by SeanKilleen** [comment]
Updating this to track the individual suggestions so that we can do small, targeted PRs instead of #3251 that has been sitting stale for a bit with some merge conflict risk.

* [ ] General text: Insanity -> Problems #3423
* [ ] IndexSanity -> IndexIssues
* [ ] IndexPartitionSanity -> IndexPartitionIssue
* [ ] IndexSanitySize -> IndexIssuesSize
* [ ] index_sanity_id -> index_issue_id
* [ ] Multiple Index Personalities -> Key Duplication or Near-Duplication Issues
* [ ] Aggressive Indexes -> Locking Issues
* [ ] Index Hoarder -> High Number of Indexes
* [ ] Abnormal Psychology -> Current Index Structure Not Recommended
* [ ] Self Loathing Indexes -> Index Usage Problems
* [ ] Indexaphobia -> Missing Indexes
* [ ] Functioning Statistaholics -> Statistics Info
* [ ] Serial Forcer -> Serialization Issues
* [ ] Addicted to Nulls -> Many Nulls
* [ ] Addicted to strings -> Many strings
* [ ] Feature-Phobic Indexes -> Underutilized Features
