### ISSUE TITLE
sp_Blitz @ProductVersionMinor for SQL Server 2016 might need updated from 5026 to 6300

### ISSUE THREAD

**Issue by sm8680** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3268]
**Version of the script**
8.14 - 20230420

**What is the current behavior?**
 (@ProductVersionMajor = 13 AND @ProductVersionMinor < 5026) OR

I wasn't sure how your handling CU's for 2017 and higher whether your looking at insuring the the cu is within x amount.  Version 16 hasn't been added but that might be considered to new.

**Comment by BrentOzar** [comment]
Howdy! I'm not exactly sure what you're saying is broken, but here's the relevant part of sp_Blitz:

```
							IF (@ProductVersionMajor = 15 AND @ProductVersionMinor < 2000) OR
							   (@ProductVersionMajor = 14 AND @ProductVersionMinor < 1000) OR
							   (@ProductVersionMajor = 13 AND @ProductVersionMinor < 5026) OR

```

I found that by searching in code for what you were saying is a problem. The cool thing about open source is that you can just open it up when you're not sure how something is being handled.

Can you take a look through there and tell me if you spot any issues, and then be more specific with your request? Thanks!

(I'm being a little sarcastic because I'm live coding this on Twitch, but I do appreciate the issue.)

**Comment by BrentOzar** [comment]
CUs have never been tied to a support date. Only SPs were.

For support end dates, check https://sqlserverupdates.com - I have 'em on a grid on the front page there.

We don't put current date checking in sp_Blitz, and I'd rather avoid adding that in. You wouldn't believe the craziness I've seen with people's date/time settings on servers - my favorite was a server whose date always had to be set in the year 2005 in order to maintain support with an old application. <sigh> Wackos.

Marking this as closed.

**Comment by sm8680** [comment]
Could you consider updating SQL Server 2016 version 13 from 5026 to 6300?

**Comment by BrentOzar** [comment]
Oh sure - if you want to do a pull request for that, go for it. Thanks!
