### ISSUE TITLE
sp_BlitzCache should not change the line endings of the query text

### ISSUE THREAD

**Issue by eschnepel** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3330]
**Version of the script**
SELECT @Version = '8.16', @VersionDate = '20230820';

**What is the current behavior?**
sp_BlitzCache changes the line endings of the query text. if the query text contains a line comment and you try to coy and paste the cell into a new editor window, the rest of the text after the first line comment is commented out.

**If the current behavior is a bug, please provide the steps to reproduce.**
the query reported contains a line comment ("-- comment text"). copy it, open a new editor, paste it.

**What is the expected behavior?**
the line endings should be preserved

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This is independent from the SQL Server version. I have not tried previous versions.

I have create a patch already.

**Comment by eschnepel** [comment]
created pull request #3332

**Comment by eschnepel** [comment]
but when not using excel and you want to copy and past the code into a SSMS new editor window, you need the line endings preserved. Otherwise a code like
``` SQL
DELETE
FROM SomeTable
-- line comment
WHERE ThirdColumn = 'Value'
```
would end up as 
``` SQL
DELETE FROM SomeTable -- line comment WHERE ThirdColumn = 'Value'
```

copy and past and execute. Preserving line comments can save employments.

Also the truncation to any character length is wrong here. 

For the excel use case there is a flag to explicit change this behavior. Without the flag the text should be kept as it is.

**Comment by BrentOzar** [comment]
There are a couple of problems with the copy/paste approach:
* Query contents get shortened due to length
* Dynamic SQL doesn't work due to the parameters
* Queries with IF/ELSE branches only show some of the content (the branches they went down)

Because of that, I really don't encourage folks to think that the query they see in there is the complete query. It's just a quick visual example of the kind of code they're dealing with.

**Comment by eschnepel** [comment]
sure, but... 
* also the restriction to shorten the query to (I think) 32000 length should be removed as written above. For being able to copy lengthy content I used to encapsulate the content into a XML node as you are doing also for other stuff.
* true Dynamic SQL has to be - like any other query - evaluated in the execution / session context (this includes parameters).
* we are a team of developers with shared responsibility for many databases and in each database many code objects  (views, functions and procedures). I have setup a regular job for the sp_Blitz* procedures and a reporting environment basis on the output tables to let each developer look into the databases they are responsible for. Showing a `PrevioslyButNoLongerFormattedAndNowScrambledOneLineSqlStatementWhichContainsDescriptiveOrDebugOneLineCommentsWhereYouNoLongerKnowTheEndOfTheComment` is a pain for the user and comparable to reading a sentence without spaces. For those who want scrambled content there is a flag to get the desired result.

**Comment by BrentOzar** [comment]
I hear you, but we're not changing the existing behavior of the code without a really compelling reason. This code has been this way for a decade.

What's the problem you're trying to solve? If you're trying to copy/paste the code from sp_BlitzCache's output, I've been really clear that I don't recommend that because the output is not necessarily correct. Do you have any other use cases?

**Comment by eschnepel** [comment]
Well ... then there is a personal/team-use-case to keep the fork open and use that for updating to new versions. I have no other choice.

**Comment by BrentOzar** [comment]
No problem! That's one of the cool things about open source.
