### ISSUE TITLE
sp_BlitzCache: increase maintainability with code deduplication in all-sorts block

### ISSUE THREAD

**Issue by eschnepel** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3338]
**Is your feature request related to a problem? Please describe.**
In the all-sort block
* the excel update statements are mentioned 8 times in different if cases.
* output select statement is mentioned twice (at the end of both all-sorts if's).

**Describe the solution you'd like**
By moving them after the end-if for both all sort ifs it is mentioned only once with a clear intent.

**Describe alternatives you've considered**
I like clean code. There is no alternative.

**Are you ready to build the code for the feature?**
pull request will be added.

**Comment by eschnepel** [comment]
Hi again,... thinking of it, because the pattern name is the only difference between each pattern in that all-sort part of the procedure it is even possible to further reduce the code duplication by introducing a generic pattern sql string and adding this multiple times to the AllSortSql string while replacing a generic string to the concrete pattern name inline. I can create a pull request if you like...

**Comment by BrentOzar** [comment]
Howdy, and thanks for the pull request.

I want to share where I'm coming from: right now, we've got a working sp_BlitzCache. It gets downloaded hundreds of times per day, from all over the world.

When a new version comes out and it has a bug, I personally get flooded with hundreds of emails. I have to do the support on it, and often I'm trying to do other stuff, like work with clients or spend time with my family. The timing can kinda suck, and it massively adds to my stress level. Often, the person who contributed the broken code isn't around to help, either, hahaha.

So when someone proposes changes to it, I have to:

- Review the code changes
- Understand what it's trying to fix
- Test the old and new versions side by side to make sure they produce the same results
- Repeat that test on several versions of SQL Server (because they have different DMV contents, like in this case, some have memory grants & spills, and some don't)

On a set of changes like this, we're talking about an hour or two of work. I'm literally booked 100% right now (thus me working on this at 4AM Pacific), so any time I spend doing this stuff either has to come out of billable client work, or my family time. 

So, back to your pull requests on this one. You've checked in two separate pull requests related to this ticket already, #3339 and #3341, and I'm looking at a [big wall of changes](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3341/files). I can see that you're willing to put in hours of work to change it, and that's great! But... I gotta be honest, I'm not willing to put in hours of work to test it.

I want to be fair to both of us, so lemme ask:

- Do your changes cause it to run faster? (As in, can you measure it?)
- Do they add new features that users will notice?

**Comment by BrentOzar** [comment]
I haven't heard back from you, and I'm going to close this for now. It's absolutely nothing personal - I just want to make sure everyone's time is put to the best use on this project.
