### ISSUE TITLE
[sp_Blitz] Streamline IFI code in checks 192 and 193

### ISSUE THREAD

**Issue by Montro1981** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3362]
**Version of the script**
Version: 8.16
VersionDate:  2023-08-20

**What is the current behavior?**
Not truly a bug, but two checks doing almost the same thing but with different outputs.
Check 192 checks if Instant File Initialization Is Not Enabled (SQL2016 SP1 and up)
Check 193 checks if Instant File Initialization Is Enabled (SQL2014 SP2 and up and RDS)

**What is the expected behavior?**
In my mind check 193 needs to check RDS only and also output if IFI is not enabled (like check 192).
And check 192 should be SQL2014 SP2 and up and also output if IFI is enabled (check 193).

**Comment by BrentOzar** [comment]
Hahaha, this is funny.

According to [this documentation page](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-server-services-transact-sql?view=azuresqldb-current), IFI is shown in the instant_file_initialization_enabled column of sys.dm_server_services in these versions:

> Applies to: SQL Server (Starting with SQL Server 2012 (11.x) SP4, and SQL Server 2016 (13.x) SP1 and later).

I don't believe this is correct - I find it hard to believe they'd backport it to 2012 SP4, but not any SP of 2014. However, if that column is available, I'd rather rely on that column's contents because it's much faster to query than going through the error log on servers that have been up for a long time.

According to [this documentation page](https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-instant-file-initialization), IFI is logged in the error log in these versions:

> SQL Server (Starting with SQL Server 2012 (11.x) SP4, SQL Server 2014 (12.x) SP2 and SQL Server 2016 (13.x) and later).

So I'm thinking the easiest way to do this is to say:

* If the instant_file_initialization_enabled column is available in sys.dm_server_services, use that
* Else, if we're on RDS, use rdsadmin.dbo.rds_read_error_log
* Else, use sys.xp_readerrorlog

**Comment by Montro1981** [comment]
Fixed the mess I made with the permission checks 🫠

Time to pick this up.

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.
