### ISSUE TITLE
sp_BlitzLock failed on Azure SQL Managed Instances

### ISSUE THREAD

**Issue by LukaszSwiatekMeniga** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3384]
**Version of the script**
Version = 8.15
VersionDate = 20230613

**What is the current behavior?**
During execution PROCEDURE [dbo].[sp_BlitzLock] I got the error:

```
@TargetSessionType is NULL, assigning for non-Azure instance
@TargetSessionType assigned as event_file for non-Azure
Grab the initial set of xml to parse at Oct 20 2023  1:12:51:777PM
Msg 40538, Level 16, State 3, Procedure dbo.sp_BlitzLock, Line 913 [Batch Start Line 0]
A valid URL beginning with 'https://' is required as value for any filepath specified.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Code:
```
USE master
go
EXEC [dbo].[sp_BlitzLock]
```

**What is the expected behavior?**
Successful execution.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Azure SQL Managed Instance
```
SELECT @@VERSION:
Microsoft SQL Azure (RTM) - 12.0.2000.8   Jul 12 2023 14:19:03   Copyright (C) 2022 Microsoft Corporation 
```

**Comment by BrentOzar** [comment]
You're two releases behind on sp_BlitzLock. Please try again with the current version and we'll go from there.

**Comment by LukaszSwiatekMeniga** [comment]
Done, script upgraded to:
Version = '8.17', VersionDate = '20231010'
I have this same error:

```
@TargetSessionType is NULL, assigning for non-Azure instance
@TargetSessionType assigned as event_file for non-Azure
Grab the initial set of xml to parse at Oct 20 2023  1:30:06:930PM
Msg 40538, Level 16, State 3, Procedure dbo.sp_BlitzLock, Line 971 [Batch Start Line 2]
A valid URL beginning with 'https://' is required as value for any filepath specified.
```

**Comment by BrentOzar** [comment]
OK, great! Around line 148, look for this code:

```
        @Azure bit =
            CASE
                WHEN
                (
                    SELECT
                        CONVERT
                        (
                            integer,
                            SERVERPROPERTY('EngineEdition')
                        )
                ) = 5
                THEN 1
                ELSE 0
            END,

```
And change it to:

`                ) IN (5, 8, 9)
`

That'll test if the method we're using for Azure SQL DB will also work for Managed Instance. (Disclaimer: I don't have access to an MI right now, so that's why I'm suggesting it. Microsoft changes behaviors in Azure all the time, so this is something that you'll need to help with debugging & testing on.)

Then, run it with @Debug = 1, and copy/paste the entire contents of the Messages tab into here and that may help to diagnose what's going on. Thanks!

**Comment by LukaszSwiatekMeniga** [comment]
Done.
EXEC [dbo].[sp_BlitzLock] @Debug=1
Current error:
```
Msg 50000, Level 11, State 1, Procedure dbo.sp_BlitzLock, Line 326 [Batch Start Line 0]
A session with the name system_health does not exist or is not currently active.
```

**Comment by LukaszSwiatekMeniga** [comment]
This message was from the Messages tab. 

I was the only one.
Screenshot: 
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/78018976/35df3712-d644-4526-a0dc-d03009485d81)

**Comment by erikdarlingdata** [comment]
@LukaszSwiatekMeniga I think you're getting something crossed here. Perhaps the script is installed in a local database as well as the master database or something, or the system_health Extended Event is deleted/disabled.

When I test this on one of my available Mangled Instances like, I get this:

<img width="857" alt="image" src="https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/8bfa1155-b3f7-48e2-85f7-730a2ee05b0f">

When I run it and specify to look at the ring buffer (which is the only thing to look at on a Mangled Instance), it runs to completion without error:

<img width="713" alt="image" src="https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/2136037/1ed5f929-74aa-41ac-a0ea-c4c332bb1baa">

You would only see the error you're hitting if you're:
1. Using old code from a different database context (maybe)
2. Using new code on a Mangled Instance that has the system_health extended event disabled (probably)

**Comment by LukaszSwiatekMeniga** [comment]
I've checked it.
This code generates an error:

```
USE master;
GO

EXEC dbo.sp_BlitzLock @TargetSessionType = 'ring', 
                      @Debug = 1;   
```              


![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/78018976/6193de7a-5b8f-4f28-a014-919f6d8a048e)
 but when I change the procedure code:
 
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/78018976/0e26642d-7ce1-45d7-a44d-15009169d4cf)

it works fine.

**Comment by erikdarlingdata** [comment]
@LukaszSwiatekMeniga There was an issue I created and submitted a fix for a while back so that [Managed Instance wouldn't go to that section of code](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3279).

This is why it's been mentioned a few times to make sure you're using the newest version of the script in the right database context. 

In another comment, you said:

> 1. I have a dedicated database for DBA tools, not master.
> 2. system_health extended event is enabled.
> 
> I'll check your recommendations soon.

But in your last comment, you have:

> I've checked it. This code generates an error:
> 
> ```
> USE master;
> GO
> 
> EXEC dbo.sp_BlitzLock @TargetSessionType = 'ring', 
>                       @Debug = 1;   
> ```

So, pretty and please, double check that stuff. It feels like the bug you're filing has already ben fixed, and you maybe have an older version in one of your databases that needs to be updated.

Thanks!
