### ISSUE TITLE
sp_blitz shows NULL for Power Plan

### ISSUE THREAD

**Issue by PasswordIsMyPassword** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3386]
Version: Oct 10, 2023

**What is the current behavior?**
Since the Oct version was installed, if you run sp_blitz with @CheckServerInfo = 1, the row for Power Plan shows Detail = NULL

**If the current behavior is a bug, please provide the steps to reproduce.**
execute sp_blitz @CheckServerInfo = 1

**What is the expected behavior?**

The detail column show show what the power plan is.
ie: Your server has 1.8GHz CPUs, and is in high performance power mode 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Versions i have confirmed. 2012, 2016, 2017, 2019, 2022
It worked previous to the Oct 2023 release.

**Comment by Montro1981** [comment]
Probable cause issue #3377.
And likely fixed by pull request #3379.

You can grab the fix from my fix repo here:
https://github.com/Montro1981/SQL-Server-First-Responder-Kit/tree/SQL-Server-First-Responder-Kit_3377-xp_readreg

Direct link to the file:
https://github.com/Montro1981/SQL-Server-First-Responder-Kit/blob/SQL-Server-First-Responder-Kit_3377-xp_readreg/sp_Blitz.sql
