### ISSUE TITLE
sp_BlitzLock in Azure SQLMI not working due to Azure changes

### ISSUE THREAD

**Issue by FatimaBrunson** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3392]
**Version of the script** 
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
--Version = '8.17', VersionDate = '20231010';

**What is the current behavior?**
-- Script is erroring out and giving the below error message
![image](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/assets/102535401/633b73f1-e322-4ac0-8563-cf32fcac3410)

**If the current behavior is a bug, please provide the steps to reproduce.**
-- Opened a New Query window in my Azure SQLMI. Executed "sp_BlitzLock" and "sp_BlitzLock @DatabaseName = [NameOfDB]". Below is the error that came from running both scripts

**What is the expected behavior?**
--This script checks for and analyzes deadlocks from the system health session or a custom extended event path

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
--Azure Managed Instance. OS: Server 2022 version 10.0. I've also tried to run the sp_BlitzLock in OS Server 2019 Azure SQLMI with no luck.  I've ran the sp_BlitzLock in a SQLExpress server and that worked just fine.

**Comment by BrentOzar** [comment]
It looks like it's related to this: https://techcommunity.microsoft.com/t5/azure-sql-blog/improving-extended-events-in-azure-sql/ba-p/3980918

Microsoft "improved" Extended Events for Managed Instances without telling anyone until AFTER the changes were already made. Classic Azure stuff.

I don't have a Managed Instance up and running, and it'll cost me money to light one up. I'm going to leave this open so that if someone has an MI, and they want to help volunteer to troubleshoot the code, they can. Or, Fatima, if you'd like to troubleshoot it, you're welcome to - I just can't provide any assistance here when Microsoft makes these kinds of changes on the fly.

**Comment by erikdarlingdata** [comment]
@FatimaBrunson  This isn't new or unexpected. When you use MI, you need to hit the ring buffer portion of the system health extended event session:

`EXEC dbo.sp_BlitzLock @TargetSessionType = 'ring'`

I do think that `sp_BlitzLock` should make that clear either in the help section or raising a custom error with an example execution to get it working in MI. I'll work on things to that end. This has come up a few times now.

**Comment by BrentOzar** [comment]
Looks good! Thanks for the pull request. Merging into the dev branch, will be in the next release with credit to you in the release notes.
