### ISSUE TITLE
sp_BlitzFirst: Why is Wait Time per Core per Sec negative sometimes?

### ISSUE THREAD

**Issue by aroques** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3428]
**Version of the script**
Look in the stored procedure, and it'll have a version date & number near the top. Put that in here. If it's not the current version (dated in the last month), then upgrade to the current version and test that before reporting a bug - we fix a lot of stuff in each new build. We'll flat out close bug reports for older builds.
**Version date:** 20230820
**Version number:** 8.16

**What is the current behavior?**
Sometimes the value of Wait Time per Core per Sec is negative. That can't be correct.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
0 or a positive value. 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
**Product:** Microsoft SQL Server Enterprise: Core-based Licensing (64-bit)
**Operating System:** Windows Server 2016 Standard (10.0)
**Version:** 14.0.3465.1

I don't know if this previously worked.

**Comment by BrentOzar** [comment]
Which versions of SQL Server and which OS are affected by this issue?

**Comment by aroques** [comment]
> Which versions of SQL Server and which OS are affected by this issue?

I updated the issue to have more detailed information. If that's not sufficient, then please let me know. Thanks for the quick response!

**Comment by BrentOzar** [comment]
Thanks for adding it! I haven't seen that behavior on current SPs/CUs for SQL Server. What's happening is that SQL Server actually lowers some wait time DMVs from time to time - saying that there's been 1 hour of CXPACKET waits, then saying wait, there's only been 59 minutes. That'll result in negative wait time.

I totally agree that it can't be correct, heh. Unfortunately, there's nothing I can do about it from a DMV perspective, and I do want to leave those negatives in because it makes it clear that the numbers are unreliable due to a bug in SQL Server.

**Comment by aroques** [comment]
> Thanks for adding it! I haven't seen that behavior on current SPs/CUs for SQL Server. What's happening is that SQL Server actually lowers some wait time DMVs from time to time - saying that there's been 1 hour of CXPACKET waits, then saying wait, there's only been 59 minutes. That'll result in negative wait time.
> 
> I totally agree that it can't be correct, heh. Unfortunately, there's nothing I can do about it from a DMV perspective, and I do want to leave those negatives in because it makes it clear that the numbers are unreliable due to a bug in SQL Server.

Good to know, thanks Brent!
