### ISSUE TITLE
sp_BlitzQueryStore: Is the 'Database Level Statistics' check obviously bugged or just ugly?

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3457]
This is a very simple issue. [Look at the code](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L5641) for the  'Database Level Statistics' check. It is indented unlike any other nearby block and is the only one to lack an `IF EXISTS` block beforehand. I take this as an obvious sign that something is amiss. I see no evidence that the block itself is buggy, but at the very least it's an extremely odd stylistic choice to put that block where it is. Am I missing something special about this check?

I'm happy to fix this myself if it is just a style issue, but I want a second opinion first.

**Version of the script**
`SELECT @Version = '8.19', @VersionDate = '20240222';`

**Comment by BrentOzar** [comment]
Let's leave the style issues as-is. The problem I've had with people "fixing style issues" is that they've introduced other typos or logic changes in the code. 

If something is genuinely causing bugs/errors/problems, by all means, open an issue describing the bug/error/problem, but otherwise let's hold off just because someone on the other side of the screen has to test the changes.
