### ISSUE TITLE
sp_BlitzQueryStore: Let's make the commenting style consistent

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3470]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add a new feature to `sp_BlitzQueryStore`. The commenting style is extremely inconsistent, so I do not know how to comment my code! I find similar issues when I notice that a temp table has no comments (examples [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L1048) and [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzQueryStore.sql#L915)) and feel like fixing that myself.

**Describe the solution you'd like**
The most common form is currently `/*Foo*/` so I'd say to apply that everywhere other than the multi-line block comments.

Aside from this style, we currently also have `--Foo`, `-- Foo`, `/*foo*/`, `/* Foo */`, and
```sql
/*
I am a single sentence on a single line. This comment block has no other lines of text.
*/
```
but I see no reason to pick those over `/*Foo*/`, which seems to be the most common.

Note that I am not suggesting building any kind of style guide. I suspect that once this change is made, anyone else who wants to write a comment in `sp_BlitzQueryStore` will be able to infer the commenting style from the code surrounding their change.

**Describe alternatives you've considered**
[Brent seems to prefer](https://www.brentozar.com/archive/2021/04/never-ever-ever-start-t-sql-comments-with-two-dashes/) `/* Foo */` over `/*Foo*/`, so we could go with that.

**Are you ready to build the code for the feature?**
I've already done it. I just need to split it out from a PR where I got carried away and changed too much.

**Comment by BrentOzar** [comment]
If this is just comment changes, let's hold off.

I know it sounds like I'm being pedantic here, but I'm literally a volunteer on the other side of the screen, trying to keep up with my day job while helping the community.

I'm worried about instances like this: https://doublepulsar.com/inside-the-failed-attempt-to-backdoor-ssh-globally-that-got-caught-by-chance-bbfe628fafdd

Where someone purposely (or accidentally) checks in something that's accidentally bad, or malicious. Because of that, I try to only focus on code changes that fix actual bugs, or add significant functionality. Going forward, let's focus on that. Thanks for understanding, and I really do wish I had more time to test things like this, but...
