### ISSUE TITLE
sp_BlitzQueryStore: Make the various calls to SERVERPROPERTY less repetitive and capture the current database's compatibility level in a variable

### ISSUE THREAD

**Issue by ReeceGoding** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3474]
**Is your feature request related to a problem? Please describe.**
We use the following many times in `sp_BlitzQueryStore`, but do not store them in variables:
```sql
CONVERT(NVARCHAR(128), SERVERPROPERTY ('EDITION')),
PARSENAME(CONVERT(NVARCHAR(128), SERVERPROPERTY ('PRODUCTVERSION')), 4),
CONVERT(INT, SERVERPROPERTY ('ENGINEEDITION'));
```
How about we assign them to well-named variables and make the code a little less repetitive and a little more readable? While we're at it, capturing the current database's compatibility level would make one of the check for Azure nicer.

**Describe the solution you'd like**
I'm thinking something like
```sql
DECLARE
	@edition NVARCHAR(128), /*Used to check if we are on Azure or not*/
	@major_version NVARCHAR(128), /*Used to see what checks we can do*/
	@engine_edition INT, /*Used to check which Azure we are on*/
	@current_database_compatibility_level INT; /*Used to check which Azure we are on*/

/*Assigns various repeated SERVERPROPERTY calls to variables*/
SELECT
	@edition = CONVERT(NVARCHAR(128), SERVERPROPERTY ('EDITION')),
	@major_version = PARSENAME(CONVERT(NVARCHAR(128), SERVERPROPERTY ('PRODUCTVERSION')), 4),
	@engine_edition = CONVERT(INT, SERVERPROPERTY ('ENGINEEDITION'));

/*Grabs current database's compatibility level*/
SELECT @current_database_compatibility_level = [compatibility_level]
FROM sys.databases
WHERE [name] = DB_NAME()
OPTION (RECOMPILE);
```
followed by using these variables in the appropriate places. The only trap is that you cannot use them at the very start of the code for `sp_BlitzQueryStore` because that code is for installing the procedure.

**Describe alternatives you've considered**
Just leaving it alone might be a good idea. I don't have the resources to test this myself and it's a much more risky change than anything else that I've recently proposed.

**Are you ready to build the code for the feature?**
 I've already done it. I just need to split it out from a PR where I got carried away and changed too much.

**Comment by BrentOzar** [comment]
If this isn't fixing a real problem or adding functionality, let's hold off.

I know it sounds like I'm being pedantic here, but I'm literally a volunteer on the other side of the screen, trying to keep up with my day job while helping the community.

I'm worried about instances like this: https://doublepulsar.com/inside-the-failed-attempt-to-backdoor-ssh-globally-that-got-caught-by-chance-bbfe628fafdd

Where someone purposely (or accidentally) checks in something that's accidentally bad, or malicious. Because of that, I try to only focus on code changes that fix actual bugs, or add significant functionality. Going forward, let's focus on that. Thanks for understanding, and I really do wish I had more time to test things like this, but...
