### ISSUE TITLE
DROP TABLE IF EXISTS  is use, but Blitzindex should be compatibel with SQL Server 2014  and below

### ISSUE THREAD

**Issue by EMeisel** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3520]
**Version of the script**
SELECT @Version = '8.19', @VersionDate = '20240222';

**What is the current behavior?**
Not running on SQL-Server 2014 and below 
Because  on line  1448 and 1466  
drop TABLE if exists 
is used
which is only introduced in 2016 

**If the current behavior is a bug, please provide the steps to reproduce.**
Test it under SQL 2014 or below

**What is the expected behavior?**

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQl-Server version 2008 to 2014

**Comment by BrentOzar** [comment]
Sure, did you want to submit a pull request with the changes you’d like to see?---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn May 19, 2024, at 1:50 PM, EMeisel ***@***.***> wrote:﻿
Version of the script
SELECT @Version = '8.19', @VersionDate = '20240222';
What is the current behavior?
Not running on SQL-Server 2014 and below
Because  on line  1448 and 1466
drop TABLE if exists
is used
which is only introduced in 2016
If the current behavior is a bug, please provide the steps to reproduce.
Test it under SQL 2014 or below
What is the expected behavior?
Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?
SQl-Server version 2008 to 2014
