### ISSUE TITLE
Running sp_blitz with outputtype

### ISSUE THREAD

**Issue by EdwardQuicksall** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3558]
**Version of the script**
@Version = '8.21', @VersionDate = '20240701';.

**What is the current behavior?**
EXEC sp_Blitz @outputtype = 'markdown'

I receive
 Msg 9421, Level 16, State 1, Procedure sp_Blitz, Line 10249 [Batch Start Line 1]
XML parsing: line 75, character 203, illegal name character

**What is the expected behavior?**
THe Markdown xml

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL 13.0.6430.49

First time running sp_blitz.

**Comment by BrentOzar** [comment]
Hi, Brent here. It just worked okay here, which makes me think there's something about your environment that's using characters that can't be outputted in XML.

If it's your first time running sp_Blitz, stick with the default parameters for now. Troubleshooting this will be pretty ambitious, and I don't wanna bother you with that because it'll involve some work on your end. Just stick with the regular output. Cheers!
