### ISSUE TITLE
sp_BlitzIndex - When no missing index is found in the filtered result, an empty table is displayed instead of "No missing indexes".

### ISSUE THREAD

**Issue by mikaelljunghorn** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3573]
**Is your feature request related to a problem? Please describe.**
Not a real problem. Only a cosmetic such.

**Describe the solution you'd like**
When the missing indexes result has been filtered and no missing indexes are to be returned, I would like to see the text "No missing indexes" instead of an empty table.

**Describe alternatives you've considered**
-

**Are you ready to build the code for the feature?**
Are you ready to commit time to this project? Have you got existing code you can help contribute to solve the problem?
Yes and yes.

**Comment by BrentOzar** [comment]
We're already doing something similar in the existing code, it just doesn't appear to be working:

![Screenshot 2024-10-08 at 2 37 45 AM](https://github.com/user-attachments/assets/4a73686b-c839-4319-8126-61b010d81a65)

The bug appears to be that the IF TOP 1 query at the start doesn't have the same filter as the SELECT query around lines 3102-3105. So the bug is:

* The IF on 3073 finds missing indexes
* The SELECT on 3076 doesn't return any rows, because the WHERE filter on 3102-3015 rules them out
* The ELSE on 3109-3110 doesn't fire

It seems like the better solution is to take the filters on lines 3102-3105, and just use those in the IF statement on 3073. Did I capture that right? That way, we don't need the additional temp table.

**Comment by mikaelljunghorn** [comment]
Hi Brent,

I'm not sure if it's that easy as we have the CTE in the beginning of the query?
In that case it seems we need to run the whole query twice to get the correct result?
But please correct me if I'm not thinking this through.

![image](https://github.com/user-attachments/assets/287e9672-f136-48ca-abc1-1d749b483e45)

We have the CTE on 3076 which is referenced on 3098-3101 and twice on 3106.

**Comment by BrentOzar** [comment]
Gotcha - yeah, it's sounding like this is more work than it's worth. Is it okay with you if we don't have the "no missing indexes" result line?

**Comment by mikaelljunghorn** [comment]
Sure! It's not a show stopper so yes.
I'll just add _my_ hack locally if my craving for "No missing Indexes" gets to big :-)
