### ISSUE TITLE
sp_Blitz: Check 73  - 'No Failsafe Operator Configured' is skipped when run as sysadmin

### ISSUE THREAD

**Issue by Tisit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3577]
**Version of the script**
8.21 - top Github commit

**What is the current behavior?**
Check 73  - 'No Failsafe Operator Configured' is skipped when run as sysadmin

**If the current behavior is a bug, please provide the steps to reproduce.**
Have no failsafe operator configured. Run sp_Blitz as sysadmin. Observe the finding not reported.

**What is the expected behavior?**
The check is not skipped unless explicitly specified

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
I'm sure this affects any SQL Server version, but I'm using following:
Microsoft SQL Server 2019 (RTM-CU25-GDR) (KB5036335) - 15.0.4360.2 (X64)   Mar 19 2024 00:23:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: )

###############################################
Not sure, if creating pull request for this immediately is fine for you. It will be basically the same pull request I made previously with fix for the other check removed.

**Comment by BrentOzar** [comment]
Awesome! Thanks for doing this. Yeah the same fix is totally fine, just standalone.---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Oct 8, 2024, at 3:15 PM, Tisit ***@***.***> wrote:﻿
Version of the script
8.21 - top Github commit
What is the current behavior?
Check 73  - 'No Failsafe Operator Configured' is skipped when run as sysadmin
If the current behavior is a bug, please provide the steps to reproduce.
Have no failsafe operator configured. Run sp_Blitz as sysadmin. Observe the finding not reported.
What is the expected behavior?
The check is not skipped unless explicitly specified
Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?
I'm sure this affects any SQL Server version, but I'm using following:
Microsoft SQL Server 2019 (RTM-CU25-GDR) (KB5036335) - 15.0.4360.2 (X64)   Mar 19 2024 00:23:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0  (Build 19045: )
###############################################
Not sure, if creating pull request for this immediately is fine for you. It will be basically the same pull request I made previously with fix for the other check removed.
