### ISSUE TITLE
sp_Blitz - Check for user of mirroring / Hadr_endpoint 

### ISSUE THREAD

**Issue by HBollah** [BrentOzarULTD/SQL-Server-First-Responder-Kit#366]
Would it be possible to add a couple of checks for mirroring and Hadr_endpoint to see if these are not owned by the sa account please? I've been tidying up the users on a server ready to go into production, tried to drop one and wouldn't let me do it. This was because the user was the owner of the Hadr_endpoint.

**Comment by PerfektNerd** [comment]
Something like you'd get if you ran this?

```
USE master;
SELECT 
     SUSER_NAME(principal_id) AS endpoint_owner,
     name AS endpoint_name
FROM sys.database_mirroring_endpoints;
```

**Comment by HBollah** [comment]
Sorry, but I'm being really dumb here. Couldn't find the button for creating a new branch to check the code out and put in what I have created. I've even looked at the 101 Pull request 101

I've add the code in the next comment below. I have tested this on 2012 (11.0.6020.0) where the accounts didn't match and it showed up when the sp_blitzwas executed. I have also run this on 2014 (12.0.5000.0) where the accounts did match and it didn't show in sp_blitz results.

Hasn't been tested on a single node SQL instance.

**Comment by HBollah** [comment]
`IF @ProductVersionMajor >= 11
						AND NOT EXISTS ( SELECT  1
										 FROM    #SkipChecks
										 WHERE   DatabaseName IS NULL AND CheckID = 789 )

	IF SERVERPROPERTY('IsHadrEnabled') = 1
		BEGIN
			IF (SELECT SUSER_NAME(principal_id) FROM sys.database_mirroring_endpoints) <> (SELECT service_account FROM sys.dm_server_services WHERE servicename like 'SQL Server (%')
				BEGIN
					INSERT    INTO [#BlitzResults]
									( [CheckID] ,
									  [Priority] ,
									  [FindingsGroup] ,
									  [Finding] ,
									  [URL] ,
									  [Details] )
					SELECT
							789 AS [CheckID] ,
							200 AS [Priority] ,
							'High Availability' AS [FindingsGroup] ,
							'HA endpoint owned by user' AS [Finding] ,
							'http://BrentOzar.com/go/ha' AS [URL] ,
							( 'meaning if their login is disabled or not available due to Active Directory problems, the HA will stop working.'
							   ) AS [Details]

				END
		END`

**Comment by BrentOzar** [comment]
Got it! Merged, going to make a few tweaks and then release an updated sp_Blitz today with this in it. Thanks for your work!

**Comment by BrentOzar** [comment]
Explaining the tweaks for posterity:

I removed the IsHadrEnabled check because endpoints go back to SQL Server 2005 with database mirroring. 

I did keep the IF @ProductVersionMajor check, but switched it to >= 10 because sys.dm_server_services only appeared in 2008. (It'd be nice to include this check in 2005, but hey, 2005 isn't supported anyway.)

I rewrote it so that instead of doing an if-exists checks, it selects from the endpoints and server services DMVs so that we can list who owns which endpoint.

Which makes it sound like I did a lot of work but it was fun, as opposed to the crappy work I did for the Markdown ticket this week.
