### ISSUE TITLE
sp_BlitzFirst - Move the "What's running right now?" to its own stored procedure

### ISSUE THREAD

**Issue by rwhoward** [BrentOzarULTD/SQL-Server-First-Responder-Kit#407]
I'd like to move the "What's running right now?" section out from sp_BlitzFirst into its own stored procedure.

2 reasons for this recommendation come to mind.
1. It would be useful to run on its own.  This can be worked around by running `@ExpertMode=1, @Seconds=1` but it generates a lot of extra data and takes a little bit longer to execute
2. Code reuse.  It's already called twice (4 if you count versions independently), so if a bug is found or a new feature is added it has to be changed in multiple locations.

**Comment by BrentOzar** [comment]
Thanks for suggesting this as an issue first! I've tossed it into the Slack channel to see what the community thinks too.

Normally I want them all in one window because I want all of this data at the same time when I'm doing troubleshooting.

About #1 - the what's-running-now section returns nearly immediately, so I think you're saying the problem is just that it continues to run afterward to gather more data, right?

**Comment by rwhoward** [comment]
Correct.  That first check is near instant but it then returns several more data sets over several seconds.
And just to clarify, having it all in one place is great and I have no intention of changing that.  My plan was to have BlitzFirst call this second stored procedure so that it's output remains the same.

Did you get any feedback from the community?  If it's not a terrible idea I'll go ahead and do it as long as I'm not responsible for naming it.

**Comment by BrentOzar** [comment]
Nobody seemed to have any big objections, and it makes sense to me too.

One trick about having sp_BlitzFirst calling this - it shouldn't fail if the other (new) stored proc doesn't exist. It should just only call it with the default options if the proc actually exists.

Dang, I was hoping you'd name it, hahaha! How about sp_BlitzWho?

**Comment by DaveDustin** [comment]
I really like the idea of breaking it out too.  

> Dang, I was hoping you'd name it, hahaha! How about sp_BlitzWho?

sp_BlitzWhoIsActive?  Nah, a trademark infrigment lawsuit is not really helpful.

sp_BlitzCurrentActivity?

**Comment by BlitzErik** [comment]
Wasn't BlitzNow a runner up for names? It's appropriate, but not
particularly... Well, anything other than appropriate.

On Aug 24, 2016 10:04 PM, "DaveDustin" <notifications@github.com> wrote:

I really like the idea of breaking it out too.

Dang, I was hoping you'd name it, hahaha! How about sp_BlitzWho?

sp_BlitzWhoIsActive? Nah, a trademark infrigment lawsuit is not really
helpful.

sp_BlitzCurrentActivity?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/407#issuecomment-242261797>,
or mute the thread

**Comment by PerfektNerd** [comment]
I like sp_BlitzWho!
