### ISSUE TITLE
Check SQL Server logins for security.

### ISSUE THREAD

**Issue by devondba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#446]
I'd like to request a feature for sp_Blitz.

A small check that uses master.sys.sql_logins to check for passwords the same as the username, logins without CHECK_POLICY and/or CHECK_EXPIRATION.

I wonder if this would be of use in the tool as it is something to check for when picking up a new instance to look after or to monitor for change.

I've written and tested in 2014, I'll test back to 2008 as requested and hopefully it will be of use.

**Comment by BrentOzar** [comment]
Hi, and thanks for the suggestion.

We're avoiding adding security checks in sp_Blitz. I do think there's a great opening in the SQL Server community for an open source security auditing tool, by sp_Blitz isn't it.

If you're passionate about security, how about starting a new script that focuses on that? im not a security guru by any means (I avoid it as much as I can) but my guess is that it'd need to be PowerShell or another OS-level tool (maybe even a C# app) since you'll need Os checks that won't be available in TSQL.

If you're interested in that, we can have a separate discussion about what it's like to start and evangelize an open source tool - you can email me at help@brentozar.com, or hop into the Slack channel for #FirstResponderKit and other folks can chime in too.

**Comment by devondba** [comment]
Thanks Brent, I understand (wipes tears away). The script currently only checks those three things mentioned for SQL logins but I like the idea of building up a PoSh script for a more thorough job. I'm far from a security expert but this could be good oportunity for learning!

I'll join the slack channel and see what happens :)

Thanks

Martyn

P.S. Just for interest, example output so far:

![image](https://cloud.githubusercontent.com/assets/22236764/18587443/015d1702-7c1a-11e6-9ffd-76c10cb2c545.png)

**Comment by GregWhiteDBA** [comment]
I would be up for contributing @devondba

**Comment by PerfektNerd** [comment]
As would I, @devondba :)

**Comment by GregWhiteDBA** [comment]
Started a project:
https://github.com/GregWhiteDBA/SQLSecurityAudit

**Comment by devondba** [comment]
Sorry guys, I seem to have missed the updates, I've added the following to your post Greg:

"Hi folks and thanks for the posetive responses to the topic.

I've set up a GitHub repositiory, added a little read me wtih my thoughts and uploaded the code I've written so far. GregWhiteDBA, it does use that function you found on stackoverflow.

Please feel free to head over to [https://github.com/devondba/SQLServerSecurityAudit] and contribute, the c# idea is nice too, initially I was thinking of just keeping it SQL and SSRS then PoSh but it could be quite sweet in C#"
