### ISSUE TITLE
sp_BlitzFirst @AsOf feature not working

### ISSUE THREAD

**Issue by PhilAitch** [BrentOzarULTD/SQL-Server-First-Responder-Kit#499]
Using SQL Server 2012 .... I'm trying to run sp_BlitzFirst to get the results from the "BlitzFirst_Results" table I've created but I'm getting the following error msg:
Conversion failed when converting date and/or time from character string.
I changed the SP to print the command it's trying to execute, which is as follows:
IF EXISTS(SELECT * FROM [DBA_Admin].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') SELECT CheckDate, [Priority], [FindingsGroup], [Finding], [URL], CAST([Details] AS [XML]) AS Details,[HowToStopIt], [CheckID], [StartTime], [LoginName], [NTUserName], [OriginalLoginName], [ProgramName], [HostName], [DatabaseID],[DatabaseName], [OpenTransactionCount], [QueryPlan], [QueryText] FROM [DBA_Admin].[dbo].[BlitzFirst_Results] WHERE CheckDate >= DATEADD(mi, -15, '2016-10-12 14:10:00.0000000 +00:00') AND CheckDate <= DATEADD(mi, 15, '2016-10-12 14:10:00.0000000 +00:00') /_ORDER BY CheckDate, Priority , FindingsGroup , Finding , Details_/;

I did the same thing with the old "sp_AskBrent" stored procedure and it worked. The command it generated was:
IF EXISTS(SELECT * FROM [DBA_Admin].INFORMATION_SCHEMA.SCHEMATA WHERE QUOTENAME(SCHEMA_NAME) = '[dbo]') SELECT CheckDate, [Priority], [FindingsGroup], [Finding], [URL], CAST([Details] AS [XML]) AS Details,[HowToStopIt], [CheckID], [StartTime], [LoginName], [NTUserName], [OriginalLoginName], [ProgramName], [HostName], [DatabaseID],[DatabaseName], [OpenTransactionCount], [QueryPlan], [QueryText] FROM [DBA_Admin].[dbo].[BlitzFirst_Results] WHERE CheckDate >= DATEADD(mi, -15, 'Oct 12 2016 2:10PM') AND CheckDate <= DATEADD(mi, 15, 'Oct 12 2016 2:10PM') /_ORDER BY CheckDate, Priority , FindingsGroup , Finding , Details_/;

As you can see, it's the format of the date in the DATEADD parts of the query that's causing the problem.

Any ideas?

**Comment by BrentOzar** [comment]
**Do you want to request a *feature* or report a *bug*?**
Answer: bug

**What is the current behavior?**
When you run sp_BlitzFirst with the @AsOf parameter, it returns an error. (The below repro scripts use a brand new table.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
sp_BlitzFirst @OutputDatabaseName = 'DBAtools', @OutputSchemaName = 'dbo', @OutputTableName = 'Test_20161012'
GO
sp_BlitzFirst @OutputDatabaseName = 'DBAtools', @OutputSchemaName = 'dbo', @OutputTableName = 'Test_20161012'
GO
sp_BlitzFirst @OutputDatabaseName = 'DBAtools', @OutputSchemaName = 'dbo', @OutputTableName = 'Test_20161012', @AsOf = '2016-10-12T10:16'

Result:
Msg 8114, Level 16, State 5, Procedure sp_BlitzFirst, Line 0 [Batch Start Line 4]
Error converting data type varchar to datetimeoffset.

**What is the expected behavior?**
Should query DBAtools.dbo.Test_20161012 and return data as of 2016/10/12 10:16AM.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Yes, worked in sp_BlitzFirst before converting the output tables to the new datetimeoffset format.

**Comment by PhilAitch** [comment]
I got this working by changing @AsOf DATETIMEOFFSET = NULL , to @AsOf DATETIME = NULL ,
in sp_BlitzFirst (as in the old sp_AskBrent) but I guess that isn't the real solution.

**Comment by BlitzErik** [comment]
This looks to be closed.
