### ISSUE TITLE
sp_BlitzCache - export to excel returns two results

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#655]
**Do you want to request a *feature* or report a *bug*?**
Bug, maybe?

**What is the current behavior?**
When you run with @ExportToExcel = 1, you get two result sets

![image](https://cloud.githubusercontent.com/assets/11590415/21290870/6c2ba7b6-c499-11e6-8aba-8428a744933a.png)

**What is the expected behavior?**
I thought this only returned the top result.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All

**Comment by BlitzErik** [comment]
This is easy enough to fix by just adding `RETURN;` after the export to excel call.

**Comment by BrentOzar** [comment]
That's as designed - the first result set is for copy/pasting into Excel, and the bottom result set has all the fields (including query plans).

**Comment by hamlynt** [comment]
Came to report a bug, but I see this is intended behaviour. Thanks for clarifying. 

There are also different column names used for the two output sets. This could be intentional to avoid long column names in Excel, except that sometimes the Excel output columns use the longer "average" while the standard output is shortened to "avg"?

Excel output column > Standard output column
ExecutionCount > # Executions
Average Reads > Avg Reads
Average Writes > Avg Writes
MinGrantKB > Minimum Memory Grant KB
AvgMaxMemoryGrant > Average Max Memory Grant
