### ISSUE TITLE
sp_BlitzFirst WaitEvents Delta View math question

### ISSUE THREAD

**Issue by goforebroke** [BrentOzarULTD/SQL-Server-First-Responder-Kit#686]
**Do you want to request a *feature* or report a *bug*?**
more of a question not a feature request or bug (maybe)
**What is the current behavior?**
I have a question about your BlitzFirst Delta Views (Waits). If I use your example and provide a date along with a 10 minute interval I get the results below..

CXPACKET 91 20931

If I use another time frame while still using a 10 minute interval I get the results below

CXPACKET -29 33341

Does the 1st result mean that over the 1st 10 minute period that I had 91 minutes worth of CXPacket waits and the 2nd result mean there were little or no CXPacket waits?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com
N/A
**What is the expected behavior?**
N/A
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
N/A

**Comment by BrentOzar** [comment]
I did some quick checks and I couldn't repro that. If you want to post your table contents in the form of a spreadsheet, that might help troubleshoot it.

**Comment by goforebroke** [comment]
Brent,

Here a sample of data from the Jan 29th between 10:45PM and 11:15PM

[WaitStats.xlsx](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/742731/WaitStats.xlsx)

I used the parameters below when querying the delta view

DECLARE @CheckDateStart VARCHAR(50) = '2017-01-29 23:00 -07:00';
DECLARE @CheckDateEnd VARCHAR(50) = DATEADD(MI, 10, CAST(@CheckDateStart AS DATETIMEOFFSET));

CXPACKET	-53	33720

**Comment by BrentOzar** [comment]
OK, great. If you filter that data for only CXPACKET, you'll see something interesting: the CXPACKET numbers aren't actually going up. They're jumping around:

2017-01-30 05:45:00.3404871 +00:00	258551338
2017-01-30 05:50:00.8457437 +00:00	257743502
2017-01-30 05:55:00.8638286 +00:00	263160817
2017-01-30 06:00:00.9889854 +00:00	259233704

That's really intriguing - I'd love to know why a SQL Server didn't report continuously ascending wait type numbers, or if it's maybe a bug in the collection mechanism - but for now I'll need to take a pass on this. You could try digging into your SQL Server's sys.dm_os_wait_stats to see if the numbers consistently go up, for example.

Short term, though, I'd just look at larger collection intervals - trend at the hourly level rather than 5 minutes. If you're troubleshooting at a granular minute-by-minute level, you're best off with a paid monitoring product that also diagnoses which queries are using the most resources, for example.

**Comment by goforebroke** [comment]
Sounds good thank you... I will reduce the interval...
