### ISSUE TITLE
sp_BlitzCache: Self-imposed code review

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#692]
sp_BlitzCache is pretty complicated in places. There are things I really want to figure out, especially in the XML processing.

- Sometimes the updates don't work -- do all of them need to be broken out, like the Operator checks?
- Should I be matching on sqlhandle or queryhash?
- General check that things work as expected
- Look for typos, copy/paste artifacts etc.

I'm sure there will be more, but this is the stuff that comes to mind.

**Comment by BlitzErik** [comment]
Another thing to check during the review is unnecessary XML parsing. Here's an example.

There's no logical difference in this case where we're looking for a spatial index in use. The `WHERE` clause guarantees that in every result, the row will be 1. If we hard code 1 or use exists, both results are the same.

```
WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
SELECT qs.SqlHandle,
	   n.fn.exist('(@IndexKind[.="Spatial"])')
FROM   #relop qs
CROSS APPLY relop.nodes('/p:RelOp//p:Object') n(fn)
WHERE n.fn.exist('(@IndexKind[.="Spatial"])') = 1;

WITH XMLNAMESPACES('http://schemas.microsoft.com/sqlserver/2004/07/showplan' AS p)
SELECT qs.SqlHandle,
	   1
FROM   #relop qs
CROSS APPLY relop.nodes('/p:RelOp//p:Object') n(fn)
WHERE n.fn.exist('(@IndexKind[.="Spatial"])') = 1;
```

![image](https://cloud.githubusercontent.com/assets/11590415/23769626/069f159c-04de-11e7-85b5-d9062984a736.png)

But look at the difference in the plans. There's no 'reuse' or folding of the exists check. It happens twice, which makes the top query more expensive (65/35 batch costs). Plus, there's an extra branch to re-run the exists. That's pretty dumb.

![image](https://cloud.githubusercontent.com/assets/11590415/23769664/1fcd2194-04de-11e7-81a3-2e14e897371f.png)

**Comment by BlitzErik** [comment]
An interesting thing to note...

The way things go now, lots of warnings don't end up being associated with stored procedures, only the statements within them. Here's an example:

![image](https://cloud.githubusercontent.com/assets/11590415/23772355/ac018524-04e8-11e7-8433-fdaba736bc51.png)

Do we want to add warnings at the proc level? That could end up with a lot of warnings, but on the other hand...

**Comment by peschkaj** [comment]
Commenting to put these thoughts down somewhere more permanent than emails between us.

> Sometimes the updates don't work -- do all of them need to be broken out, like the Operator checks?

A lot of the original operator checks are broken out for one of two reasons (both of which are true):

1. Because the original author couldn't figure out how to get them to work as a single block
2. Because he could and it was terribly slow

> Unnecessary XML parsing

This is entirely due to my laziness at the time of writing the code. 

> Do we want to add warnings at the proc level?

I had a longer term goal to correlate statement warnings back up with procedure warnings but had not gotten around to it yet. It shouldn't be too difficult to create an intermediate temporary table that contains all of the statement hashes for each procedure and then do some kind of "join" between them.

**Comment by BlitzErik** [comment]
I took a good bite out of this. Will open another if I start finding things again.
