### ISSUE TITLE
PowerShell install/update script

### ISSUE THREAD

**Issue by mrthomsmith** [BrentOzarULTD/SQL-Server-First-Responder-Kit#788]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Manual execution of scripts to create and alter stored procs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com**
N/A

**What is the expected behavior?**
Executing the PowerShell script will create/alter the stored procs on the specified server and database, defaults to master database on the local default instance.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Requires SqlServer PowerShell module installed.

**Comment by BrentOzar** [comment]
Howdy sir. Thanks for the PR, but we'd rather avoid PowerShell scripts for now. If you want, check out http://dbatools.io - they've got a big PowerShell library that does things like install community scripts. They've got an Install-SqlWhoIsActive command already, so it might be easy to extend that to install these scripts. Plus, since these are available via the web in GitHub, you could even have it install the latest branch automatically. I bet folks would love that.
