### ISSUE TITLE
sp_DatabaseRestore @RestoreTo Parameter

### ISSUE THREAD

**Issue by digitalohm** [BrentOzarULTD/SQL-Server-First-Responder-Kit#871]
Type: Freature

Description: Adding the @RestoreTo parameter to allow us to specify the date and time to restore UP to.

**Comment by BrentOzar** [comment]
Sure, makes sense. I wouldn't name it RestoreTo, since that could also be interpreted as a file destination. I'd call it @StopAt to match the restore command's syntax.

You're clear to go ahead and start developing it. Here's the contribution guidelines:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/master/CONTRIBUTING.md

Do you want to write the code? (If not, we'll close the issue, just making sure you're committing to writing it.)

**Comment by digitalohm** [comment]
Yes I'll take care of writing it :)

**Comment by digitalohm** [comment]
Just an update:

I added the @StopAt parameter and did some brief testing on my dev server.

I also updated some of the comments, as well as fixed an error I left around from the last iteration :(

I'm working on a way to test.  Just a generic script that creates a database, a table, inserts data, takes full backup, changes data, takes diff backup, changes data, and takes log backups throughout the process for maybe 5 minutes?  (5 minutes seems like a long time to test something though).  I was hoping to create the pull request once this was finished.

The branch is available at:
https://github.com/digitalohm/SQL-Server-First-Responder-Kit/tree/sp_DatabaseRestore_Issue_871

**Comment by digitalohm** [comment]
I wrote a short script that will execute the Ola backups for a full, diff, and 10 logs, then it takes a random entry from the log files that were backed up, and uses that for the @StopAt parameter. 

Where should I include this script?  Is there a directory in the repository for holding scripted tests?

💃

**Comment by BlitzErik** [comment]
I don't know a better way to link to it, but here:
