### ISSUE TITLE
Easier onboarding intro for script users

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/SQL-Server-First-Responder-Kit#950]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When you download the scripts, we're not bundling an easy explanation doc that explains what the scripts do. I think the readme.md is a great start - might just be a matter of PDFing that as part of the build process.

Could include list of script execution calls, and then explain the columns in what they're looking at.

**Comment by BlitzErik** [comment]
Thinking about this, have a look at the TestBed file [here](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/tree/dev/Documentation/Development) for example calls.

**Comment by BlitzErik** [comment]
@BrentOzar I found a [command line tool](https://superuser.com/questions/689056/how-can-i-convert-github-flavored-markdown-to-a-pdf#722374) called `grip` that can work some Magick with Markdown files. 

If you run `grip <path\to.md -b>` it'll open the file in your browser, and from there you can print to pdf. Attached the output. 

Does this work for you, or did you want something simpler?

[sp_BlitzGuide.pdf](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1934087/sp_BlitzGuide.pdf)

**Comment by BlitzErik** [comment]
Looking at the output, the links aren't clickable as a PDF, but... I can export it to HTML and it is.

I can't put a .html file in here, but if you change the extension on this one, it works and the links are clickable.

[sp_BlitzGuide.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/1934092/sp_BlitzGuide.txt)

**Comment by BlitzErik** [comment]
This is a stinkbomb! Alright, here's what I've tried:
- Converting the README to html then to pdf
- Converting the README to pdf

Programs I've tried:
- wkhtmltopdf
- pandoc
- grip
- Like 30 different websites
- Skipped Adobe because they wanted a credit card

Going directly from md to pdf doesn't pan out. The internal links all point to links on Github. That's not helpful at all.

Going to html creates mostly working links (but Back To Top doesn't work, just stays where you are). But then going to pdf breaks the links. 

Outcomes:
 - grip makes really nice looking html, but it seems like that's not what you wanna distribute. The PDFs it makes don't have working links, and printing/saving the html as pdf bombs too.
 
- wkhtmltopdf sucks, useless

 - pandoc sucks, useless

Not sure if:
- There might be more complicated stuff to try with CSS that I'm just not wrapping my head around on Saturday morning.

**Comment by BrentOzar** [comment]
Ouch. So, wanna close it for now? I'm down with closing it - we can always revisit it later if we stumble across something amazing.

**Comment by BlitzErik** [comment]
Yeah, I'm out of quick ideas.
