### ISSUE TITLE
sp_BlitzIndex No Rows Returned vs "No missing indexes"

### ISSUE THREAD

**Issue by djlaney3** [BrentOzarULTD/SQL-Server-First-Responder-Kit#984]
sp_BlitzIndex
@Version = '5.5';
@VersionDate = '20170701';

More of a question, when viewing the results, the second dataset returned is usually the "missing indexes" section.  On occasion, I get an empty dataset (column headers are visible, but no missing index rows).  Normally, if no indexes are missing, the "No missing indexes" message shows in the "finding" column.  Do you know why I would get an empty dataset instead of the no missing indexes message?  All other returned datasets appear normal.

**Comment by BrentOzar** [comment]
Sure, do a search in the code for "No missing indexes" and you'll see the relevant section. It sounds like you've got some rows in #MissingIndexes, but they don't meet the minimum benefit threshold:

/* Minimum benefit threshold = 100k/day of uptime OR since table creation date, whichever is lower*/
AND (magic_benefit_number / CASE WHEN cd.create_days < @DaysUptime THEN cd.create_days ELSE @DaysUptime END)
