### ISSUE TITLE
Feature sp_DatabaseRestore - Add parameter for creating the restore script and not executing the commands

### ISSUE THREAD

**Issue by DatStone** [BrentOzarULTD/SQL-Server-First-Responder-Kit#989]
request a *feature* 

**What is the current behavior?**
Now it is possible to debug with a code '1'
But this deliver not the excpected restore script. 
Debug is when you have troubels

**What is the expected behavior?**
With this extra parameter you can decide to run the restore or to create the restore script.

**Comment by BrentOzar** [comment]
Ah, interesting! Makes sense. I wouldn't want to use @Debug = 1 for this because Debug is really more about debugging, not about building a restore script. (It'd be a little confusing to tell users, "To build a restore string, run it with Debug = 1, and then sift through all the informational outputs.")

How about you use the same parameter name as Ola's scripts - @Execute = Y or N, default to Y. If Y, we do the work and don't print out the statements. If N, we print out the restore statements only, and we don't execute them. (Totally unrelated to Debug = 1.)

Any thoughts on that? If that works for you, you're clear to start coding it. Let us know if you have any questions though - this kind of thing is a lot of work, and you wanna think through it before you get started. Thanks!

**Comment by DatStone** [comment]
I will use your proposition and use the same parameter name as Ola's scripts - @execute = Y or N, default to Y.
It was also my vision to use @debug only for debug info.

**Comment by BlitzErik** [comment]
We haven't heard back from you on this in a couple months, so I'm going to go ahead and close this out.

If you decide you want to code it in the future, feel free to reopen the issue when you have something ready.

Thanks!
