### ISSUE TITLE
sp_AllNightLog PollDiskForNewDatabases doesn't support customizable paths

### ISSUE THREAD

**Issue by jstanford-kcura** [BrentOzarULTD/SQL-Server-First-Responder-Kit#993]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When using a customizable folder path in the branch of Hallengren's scripts referenced here:
https://github.com/olahallengren/sql-server-maintenance-solution/issues/14

Backups go to the correct location.  However, the polling code doesn't find the files, because is uses the following code to find new databases:
`DIR /b "\\<backup server name>\Backups\**INSTANCENAME**\**DATABASENAME**\"`

**What is the expected behavior?**
Ideally, this procedure should follow the same conventions for folder paths.

**Comment by BrentOzar** [comment]
Thinking through this - we need the directory listing to happen at whatever point the directory path has database names. These are all valid @RestorePath values:

- \\FILESERVER\FOLDERNAME\ - which means Ola's default file path handling will still append folders for instance name, AG name, cluster name, etc - this one is going to be tricky since some databases in the folder may be part of an AG (and therefore have a folder) whereas others may not
- \\FILESERVER\FOLDERNAME\**DATABASENAME**
- \\FILESERVER\FOLDERNAME\**INSTANCENAME**\**DATABASENAME**
- \\FILESERVER\FOLDERNAME\**DATABASENAME**\**INSTANCENAME**
