### ISSUE TITLE
sp_allNightLog Delete databases from the secondary server that are deleted from primary

### ISSUE THREAD

**Issue by scorellis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#998]
Feature Request:

If a database has been deleted on the primary, it should be deleted on the secondary also.

idea for a solution #1: Linked server check from Secondary to Primary and remove any databases that are not found on the primary.

#2 Check the master.dbo.commandlog or possibly msdb.dbo.restore_worker  to see if a log backup has been seen in the past x hours.  

(I prefer solution #2) 

This would require additional flag(s) in the procedure call, i.e. @DeleteOrphansInterval = x (which could be in hours.)  One flag works for me, if someone sets a flag to delete orphaned databases at some interval then one would expect the databases to be deleted at that interval. Right? 

Either of these could go horribly wrong if the code is run on the wrong server, ever.

**Comment by BlitzErik** [comment]
The second one would be more in line with not having the servers ever talk to each other.

This could go horribly wrong if:
- Someone accidentally deletes a workspace 
- A large workspace needs to be restored to an earlier point in time 
- A workspace goes into a state where log backups aren't possible for > some_threshold 
- The DR server loses sight of the network share for > some_threshold
- The primary server loses sight of the network share for > some_threshold

I'd be hesitant to automate this off the bat. Since so much (including failover) is going to be manual for the time being, this probably should be as well.

**Comment by BrentOzar** [comment]
I like the @DeleteOrphansInterval idea, although we gotta come up with a more self-explanatory parameter name. We also need to code #958 first - the ability to skip databases - because you might have some databases you don't want deleted. (For example, DBA utility databases, Management Data Warehouse, monitoring tools, etc.)

**Comment by scorellis** [comment]
To Respond to Erik:
This could go horribly wrong if:

1.  Someone accidentally deletes a database (let's use the term "database, not everyone knows kCura Relativity calls databases "workspaces", interchangeably).
           standard SOP should not be to go to the secondary to get it.  We have to get it from backup.
2.  A large database needs to be restored to an earlier point in time
          the minimum wait before auto-deleting restoring should be three days - we can enforce that in code. 
3.  A database goes into a state where log backups aren't possible for > some_threshold
           Again, three days.  If the log backups aren't firing for three days and we don't notice, then that's bad, and maybe the restoring database gets removed, but we shouldn't be trying to solve the problem of me not watching my alerts here. 
4.  The DR server loses sight of the network share for > some_threshold
        3 days.
5.  The primary server loses sight of the network share for > some_threshold
         3 days :) 

Brent, Regarding the parameter name: 
@minWaitToDeleteRestoringDBs (int, Days) (enforced default minimum = 3)   Description: The minimum time that a database on the primary can go without a log backup before it is removed from the secondary by the restoring job.

**Comment by BrentOzar** [comment]
Yeah, I agree that 3-4 days makes sense. It solves the "stuff broke on Friday and we didn't realize it until Monday" problem.

Coding note: when we build this, we'll need additional logic in sp_AllNightLog @PollDiskForNewDatabases = 1. Right now, it's looking at the list of folder names, and it would simply pick the database back up again since it's still got a folder in the backup share. We would want to code #958 first, and then whenever we delete databases, add them to the list of databases to be ignored.

This will also introduce some complexity in monitoring - it produces a scenario where we remove a database from the primary (say it goes cold and the client stops paying), it gets deleted later from the secondaries, then a week or two later, the client calls and asks for it to be added back in. We'll need to remove it from the exclusion policy.

That's totally doable - just thinking through the complexity.

**Comment by BlitzErik** [comment]
Gonna close this for now. Feel free to reopen when you're ready to start coding.

Thanks!
